/* =========================================================================
   Epistemology Lens Switch: what counts as evidence?
   -------------------------------------------------------------------------
   One fictional case (a reported rise in "low-level disruption" at Meadowbank
   Academy) and three epistemological starting points. The learner declares a
   position and then makes three decisions that build a study from it:

       1. what the research object is
       2. what question can legitimately be asked
       3. which method follows

   Two further decisions - what counts as evidence, and what claim the study
   could support - are held back behind "Specify the rest of the study". They
   are the same decisions as before and carry the same prose; they are simply
   not part of the first pass, because the cascade from object to method is
   already the whole argument and a learner who has seen it once can run a
   second lens in half the time.

   THE EDUCATIONAL MODEL
   ---------------------
   Every decision offers the same four options, and no option is labelled with
   the position it belongs to. Each option carries a `home` lens. Coherence is
   simply the number of decisions whose home matches the declared position.

   That is deliberately a weak model, and the tool says so: coherence is the
   minimum a design has to clear, not a measure of quality. The teaching work
   is done by the prose attached to each option - what it commits you to, and
   what tension it creates when it is taken under a different position.

   The fourth option throughout (`home: "individual"`) belongs to none of the
   three declared positions. It relocates the problem inside individual pupils
   and is included because it is the design a school is most likely to fund.
   Students should be able to name it, not just avoid it.

   WHAT THIS IS NOT
   ----------------
   Three positions is a simplification of a contested landscape, and the tool
   does not rank them. Each lens profile carries what it makes visible AND what
   it costs. "In tension" never means "forbidden": good mixed designs combine
   positions deliberately and say how they hold them together.

   No real school, policy, dataset or document is described. All figures are
   invented for teaching. No data leave the browser: no storage, no network.
   ========================================================================= */

(function () {
  "use strict";

  /* =======================================================================
     The three starting points
     ===================================================================== */

  var LENSES = [
    {
      id: "measure",
      name: "Realist / positivist",
      creed:
        "There is a real pattern of behaviour in those classrooms. It exists " +
        "whether or not anyone writes it down, and the job of research is to " +
        "measure it as accurately as possible and find what predicts it.",
      object: "a real, countable pattern of behaviour",
      visible:
        "How much, where, and what covaries with what - with a stated degree " +
        "of uncertainty",
      recedes:
        "Who decided what counts as an incident, and what the act of " +
        "recording does",
      action:
        "Change the conditions that predict the count: class size, timetable " +
        "position, staff deployment",
      canSay:
        "Something quantified and comparable: how often, in which lessons, " +
        "with what association to measurable features of those lessons, and " +
        "how confident you are in each figure.",
      cannotSay:
        "Whether the January rise in the log reflects a change in pupils or a " +
        "change in referring. Observation starting now cannot reach backwards " +
        "into a record collected under a different rule.",
      hides:
        "That the observation schedule has to encode somebody's definition of " +
        "disruption before the first lesson is watched. Once the schedule is " +
        "agreed, the definitional question stops being askable inside the " +
        "study."
    },
    {
      id: "mechanism",
      name: "Critical realist",
      creed:
        "Something real is going on that is not identical with what anyone " +
        "can observe. Reality is stratified: the events recorded are only a " +
        "part of what happened, and what happened is only a part of what had " +
        "the power to happen. Our concepts of it are fallible and socially " +
        "produced, and there is still something there.",
      object: "a real tendency, generated by mechanisms that are not directly observable",
      visible:
        "What would have had to be the case for this pattern to appear, and " +
        "the conditions under which the tendency shows itself",
      recedes:
        "Precise quantities, and the temptation to stop once a plausible " +
        "story fits",
      action:
        "Change the mechanism: revise the referral rule, stabilise the rooms, " +
        "support the new staff",
      canSay:
        "That a specific mechanism, operating under specified conditions, " +
        "would generate this pattern - together with the evidence for it, the " +
        "cases where it failed to appear, and what would have counted against " +
        "it.",
      cannotSay:
        "How much of the rise each mechanism accounts for. Retroduction " +
        "identifies candidates and rules some out; it does not partition " +
        "variance, and pretending otherwise is where this position most often " +
        "goes wrong.",
      hides:
        "How easily a mechanism story becomes unfalsifiable. The discipline " +
        "here is the negative case: the departments where the same conditions " +
        "held and the pattern did not appear."
    },
    {
      id: "construct",
      name: "Social constructionist",
      creed:
        "\"Disruption\" is not found in the room, it is assembled - in the " +
        "policy text, in the referral form, in the staffroom account, in the " +
        "pupil's description of being written up. The job of research is to " +
        "study that assembling and what it makes possible.",
      object: "a category actively assembled in talk, records and institutional practice",
      visible:
        "How an interaction becomes an attributable act by a named pupil, and " +
        "who is authorised to make that conversion",
      recedes:
        "The quantitative question the governors asked - is it getting worse, " +
        "and by how much",
      action:
        "Change what the category does: rewrite the referral form, open up who " +
        "may contest a referral, ask what the policy authorises",
      canSay:
        "How the category is produced here, what work it does, which subject " +
        "positions it makes available to staff and pupils, and what follows " +
        "institutionally from being placed in it.",
      cannotSay:
        "Whether behaviour is worse than last year. Not because the question " +
        "is uninteresting but because this design has taken the measure apart " +
        "rather than using it, and cannot then lean on it.",
      hides:
        "That something happened in the lesson. Analysing how a category is " +
        "assembled is not a claim that the interactions it names are " +
        "fictional, but it is easy to slide into writing as though they were."
    }
  ];

  /* The fourth, undeclared position. Named so that students can recognise it
     rather than merely score badly on it. */
  var INDIVIDUAL = {
    id: "individual",
    name: "Person-centred realism (a fourth position)",
    note:
      "This locates the problem inside a minority of pupils - a coherent " +
      "research programme, and the design a school is most likely to fund. It " +
      "is not entailed by any of the three positions on offer, and nothing in " +
      "the case points to it."
  };

  /* =======================================================================
     The five decisions
     -------------------------------------------------------------------
     Options are always in the order measure / mechanism / construct /
     individual, but they are never labelled with their home position: in a
     real research meeting nobody announces which epistemology an option
     belongs to either.

     DECISIONS is kept in its original authored order. SEQUENCE below decides
     the order they are *presented* in, so that the three that make up the
     first pass come first without the data having to be shuffled.
     ===================================================================== */

  var DECISIONS = [
    {
      id: "object",
      row: "Research object",
      label: "What is the research object?",
      hint:
        "Everything else follows from this. Choose what you are taking " +
        "\"disruption at Meadowbank\" to be.",
      options: [
        {
          home: "measure",
          text:
            "A pattern of pupil behaviour that is really there, which the " +
            "school's records measure imperfectly.",
          commits:
            "The record and the thing are now different, so your first " +
            "methodological problem is measurement error, and your first task " +
            "is a better instrument than the referral log.",
          tension:
            "It takes the definition of disruption as settled before the " +
            "study starts, which is precisely what the other two positions " +
            "want to hold open."
        },
        {
          home: "mechanism",
          text:
            "A real tendency in this school which may or may not show itself " +
            "in the log, produced by mechanisms nobody can observe directly.",
          commits:
            "What you can see is now only part of what is happening, so your " +
            "task becomes reasoning backwards from the pattern to what would " +
            "have had to be the case for it to appear.",
          tension:
            "It commits you to entities - tendencies, mechanisms - that no " +
            "observation will ever show you directly, which a design built " +
            "only on what can be measured has no way of licensing."
        },
        {
          home: "construct",
          text:
            "A category that staff, pupils, forms and policies actively " +
            "assemble, and which organises who gets held responsible.",
          commits:
            "Disruption is now the output of a process you are studying " +
            "rather than the input to your study. The referral form stops " +
            "being a measure and becomes data.",
          tension:
            "It refuses to take the incident count at face value, so it " +
            "cannot then be used to answer \"how much\" - and \"how much\" is " +
            "what the school asked."
        },
        {
          home: "individual",
          text:
            "A stable characteristic of a minority of pupils that the school " +
            "has not yet identified.",
          commits:
            "The unit of analysis is now the pupil, the design is a screening " +
            "design and the intervention is aimed at individuals. All of that " +
            "was settled before a single datum was collected.",
          tension:
            "The location of the problem - inside pupils rather than in the " +
            "lesson, the policy, the building or the record - has been chosen " +
            "in advance rather than found."
        }
      ]
    },
    {
      id: "question",
      row: "Legitimate question",
      label: "What question can legitimately be asked?",
      hint:
        "A question is legitimate here if the object you declared is the kind " +
        "of thing it could be a question about.",
      options: [
        {
          home: "measure",
          text:
            "How much disruption is there, is it rising, and what predicts " +
            "variation between lessons?",
          commits:
            "You have committed to a quantity that exists to be estimated, " +
            "and to lessons as comparable units.",
          tension:
            "\"How much\" presupposes a settled unit of counting. If the " +
            "object of study is how that unit gets made, this question asks " +
            "you to assume your answer."
        },
        {
          home: "mechanism",
          text:
            "What would have to be the case for disruption to become likely " +
            "here, and under what conditions does that tendency show itself?",
          commits:
            "You are now after an explanation rather than an estimate, and " +
            "you have accepted that the answer may not be visible in any " +
            "single dataset.",
          tension:
            "It asks about something that could be true even where the " +
            "records show nothing, which a design that equates the real with " +
            "the recorded cannot accommodate."
        },
        {
          home: "construct",
          text:
            "How does something come to be counted as disruption here, by " +
            "whom, and what does that counting make possible?",
          commits:
            "The referral is now the phenomenon rather than the measurement, " +
            "and \"by whom\" makes authority part of the question.",
          tension:
            "It brackets the question of whether behaviour changed, which is " +
            "the question a design aimed at measuring or explaining a real " +
            "pattern was set up to answer."
        },
        {
          home: "individual",
          text:
            "Which pupils are responsible, and what distinguishes them from " +
            "the rest?",
          commits:
            "Responsibility has been made a property of persons before " +
            "anything has been established about the lesson, the policy or the " +
            "record.",
          tension:
            "It answers a question nobody in the case asked, and its answer " +
            "will be a list of names whatever the underlying situation turns " +
            "out to be."
        }
      ]
    },
    {
      id: "evidence",
      row: "What counts as evidence",
      label: "What counts as evidence?",
      hint:
        "Not \"what data could you get\" but \"what would you accept as " +
        "bearing on the question\".",
      options: [
        {
          home: "measure",
          text:
            "Standardised observation counts from sampled lessons, plus " +
            "behaviour ratings with known reliability.",
          commits:
            "Evidence must be repeatable and comparable across observers. " +
            "Anything that cannot be scored the same way twice is excluded.",
          tension:
            "A schedule with high inter-observer agreement is agreement about " +
            "a definition. It cannot be evidence about how that definition " +
            "came to be the one in use."
        },
        {
          home: "mechanism",
          text:
            "The incident series, plus the conditions - timetable, rooms, " +
            "staff turnover, the policy change - and the departments where the " +
            "pattern did not appear.",
          commits:
            "Negative cases have become evidence, which is what stops a " +
            "mechanism story from being merely plausible.",
          tension:
            "It mixes counts, documents and accounts without a single " +
            "standard of measurement, which a design built on comparability " +
            "cannot combine."
        },
        {
          home: "construct",
          text:
            "The talk and the paperwork: the wording of the behaviour policy, " +
            "completed referral forms, staffroom accounts, and how pupils " +
            "describe being written up.",
          commits:
            "Documents are now actions rather than descriptions, and the " +
            "focus-group phrase \"it depends whose lesson it is\" becomes a " +
            "finding rather than noise.",
          tension:
            "None of it can tell you how often anything happened, so a study " +
            "that needs a rate cannot be built on it."
        },
        {
          home: "individual",
          text:
            "Screening scores for every pupil, matched to their referral " +
            "history.",
          commits:
            "Evidence is now individual-level and cross-sectional. The " +
            "lesson, the teacher and the policy have left the dataset " +
            "entirely.",
          tension:
            "Matching scores to referrals will produce an association " +
            "whatever generated the referrals, because pupils who are " +
            "referred more are, by construction, the ones the score is " +
            "compared against."
        }
      ]
    },
    {
      id: "method",
      row: "Method",
      label: "Which method follows?",
      hint:
        "The method is downstream. Check that it is a way of getting at the " +
        "object you declared, not simply a technique you are comfortable with.",
      options: [
        {
          home: "measure",
          text:
            "Structured observation of a stratified sample of lessons with " +
            "inter-observer agreement, then multilevel regression on " +
            "lesson-level predictors.",
          commits:
            "You will get defensible numbers about the period you observe, " +
            "and nothing at all about the period already logged.",
          tension:
            "Counting under a fixed schedule settles in advance the thing " +
            "your declared object treats as unsettled."
        },
        {
          home: "mechanism",
          text:
            "A comparative case design: the interrupted incident series " +
            "alongside paired high- and low-referring departments, reasoning " +
            "back to candidate mechanisms and testing each against the cases " +
            "where the pattern is absent.",
          commits:
            "You will end with a shortlist of mechanisms and an account of " +
            "what would have counted against each, rather than an effect size.",
          tension:
            "Retroduction infers to unobservables, which a design that admits " +
            "only measured quantities cannot warrant."
        },
        {
          home: "construct",
          text:
            "Discourse and documentary analysis: what the policy text " +
            "authorises, how the referral form converts an interaction into an " +
            "act by a named pupil, and the repertoires staff and pupils use to " +
            "account for it.",
          commits:
            "The analysis is of how accounts are built and what they do, not " +
            "of how often words appear. Frequency of a word is not the finding.",
          tension:
            "It produces no rate, no comparison group and no estimate, so it " +
            "cannot support a design whose question was quantitative."
        },
        {
          home: "individual",
          text:
            "Administer the screening instrument to all 900 pupils and " +
            "correlate scores with logged incidents.",
          commits:
            "Every pupil in the school is now assessed in order to explain a " +
            "change that began with a policy revision.",
          tension:
            "The correlation you find is partly built in: the referral log is " +
            "both the thing being explained and part of what identifies the " +
            "pupils of interest."
        }
      ]
    },
    {
      id: "claim",
      row: "Defensible claim",
      label: "What claim could the study support?",
      hint:
        "Choose the strongest sentence this design would actually license.",
      options: [
        {
          home: "measure",
          text:
            "\"Recorded incidents are higher in lessons with these features; " +
            "the association is of this size, with this uncertainty.\"",
          commits:
            "Note what the sentence is about: recorded incidents. Writing " +
            "\"disruption\" instead of \"recorded incidents\" would be the " +
            "single most common way this design is oversold.",
          tension:
            "It reports an association in a measure your declared object " +
            "treats as something to be explained or unpicked, not relied on."
        },
        {
          home: "mechanism",
          text:
            "\"The rise is plausibly generated by the January referral rule " +
            "interacting with room instability and inexperienced staff; here " +
            "is the evidence for it, and here is what would have counted " +
            "against it.\"",
          commits:
            "You have claimed a mechanism and made it vulnerable in the same " +
            "sentence. Dropping the second half turns this into a story.",
          tension:
            "It asserts something unobservable, which the evidence standard " +
            "you accepted does not reach."
        },
        {
          home: "construct",
          text:
            "\"Disruption at Meadowbank is assembled through these practices; " +
            "the category does this work, and these are its consequences for " +
            "who gets held responsible.\"",
          commits:
            "A claim about practices and their effects, not about frequency. " +
            "It is falsifiable in its own terms: someone can show the " +
            "practices work otherwise.",
          tension:
            "It is a claim about how the measure is produced, which is not an " +
            "answer to a question about what the measure measures."
        },
        {
          home: "individual",
          text:
            "\"This percentage of pupils score above threshold and account " +
            "for this share of logged incidents.\"",
          commits:
            "True, probably, and almost content-free: a minority always " +
            "accounts for most referrals, including in a school where nothing " +
            "changed.",
          tension:
            "It answers at the level of persons a question that was asked " +
            "about a school, a policy and a record."
        }
      ]
    }
  ];

  /* Presentation order: object, question, method make the first pass; evidence
     and claim are added by "Specify the rest of the study". Values are indices
     into DECISIONS, so `state.answers` stays aligned with the authored data. */
  var SEQUENCE = [0, 1, 3, 2, 4];
  var CORE_COUNT = 3;

  /* How many decisions are on offer right now. */
  function shownCount(state) {
    return state.extended ? SEQUENCE.length : CORE_COUNT;
  }

  /* The DECISIONS indices currently on offer, in presentation order. */
  function shownIndices(state) {
    return SEQUENCE.slice(0, shownCount(state));
  }

  /* Two completed lenses unlock the challenge: the two unsupportable claims
     are only arguable once the learner has more than one design to test them
     against. */
  var CLAIMS_UNLOCK_AT = 2;

  /* =======================================================================
     The challenge claims
     ===================================================================== */

  var CLAIMS = [
    {
      id: "worse",
      text:
        "\"Behaviour in lessons deteriorated by 58% between the autumn and " +
        "spring terms.\"",
      answer: "none",
      verdict: "No design on this page supports it.",
      why:
        "The 58% is a rise in referrals, and the rule about when to refer " +
        "changed in the middle of the period. A mechanism study can say the " +
        "rule is a candidate cause of that rise, which is the opposite of this " +
        "sentence. The word doing the damage is \"behaviour\", where the data " +
        "say \"referrals\"."
    },
    {
      id: "newstaff",
      text:
        "\"Recorded incidents are higher in lessons taught by staff in their " +
        "first year at the school.\"",
      answer: "measure",
      verdict: "The realist/positivist design supports it.",
      why:
        "It is a claim about an association in a measure, stated as an " +
        "association and no more. Notice how careful the wording has to be: " +
        "\"recorded incidents\", not \"disruption\", and no suggestion about " +
        "why. It says nothing about whether new staff manage classes " +
        "differently or refer differently."
    },
    {
      id: "rule",
      text:
        "\"The rise was generated by the January referral rule becoming the " +
        "default response, in departments already destabilised by the room " +
        "move.\"",
      answer: "mechanism",
      verdict: "The critical realist design supports it - conditionally.",
      why:
        "This is a mechanism claim with its conditions attached, which is what " +
        "retroduction produces. It earns the word \"generated\" only if the " +
        "study also reports the departments where the same rule and the same " +
        "disruption to rooms did not produce a rise. Without the negative " +
        "cases it is a plausible story."
    },
    {
      id: "produced",
      text:
        "\"Being 'a disruptive pupil' at Meadowbank is partly produced by the " +
        "referral form, not simply recorded by it.\"",
      answer: "construct",
      verdict: "The social constructionist design supports it.",
      why:
        "The form requires a named pupil, a category from a drop-down list and " +
        "a single act; an interaction between several people in a badly " +
        "timetabled room cannot be entered. What comes out the other side is an " +
        "attributable act by an individual. That is a claim about what a " +
        "document does."
    },
    {
      id: "screen",
      text:
        "\"Screening would identify the pupils causing the increase, so the " +
        "school should fund it.\"",
      answer: "none",
      verdict: "No design on this page supports it, and it contains two " +
        "separate leaps.",
      why:
        "The first half assumes the increase has pupil-level causes, which is " +
        "the conclusion, not the premise - and the most obvious candidate cause " +
        "in the case is a policy. The second half is a resource decision, and " +
        "no study licenses one on its own. Even a perfect screening study " +
        "would find an association between scores and referrals, not the cause " +
        "of a change."
    }
  ];

  var CLAIM_OPTIONS = [
    { value: "measure", label: "The realist/positivist design" },
    { value: "mechanism", label: "The critical realist design" },
    { value: "construct", label: "The social constructionist design" },
    { value: "none", label: "None of these designs, as specified" }
  ];

  /* =======================================================================
     Opening prediction feedback
     ===================================================================== */

  var OPENING = {
    nothing: {
      tone: "caution",
      verdict: "Only one of them will count incidents.",
      text:
        "Counting presupposes that the unit of counting is settled. Two of " +
        "the three positions treat that settlement as the thing to be " +
        "explained, so counting is not available to them as a first move."
    },
    writeup: {
      tone: "caution",
      verdict: "The difference starts a long way before the write-up.",
      text:
        "By the time there are findings to interpret, the decisive choices " +
        "have already been made: what was collected, from whom, under what " +
        "definition. Two of these teams will not have a dataset the other " +
        "would recognise as data."
    },
    method: {
      tone: "caution",
      verdict: "Half right, and the half that is missing is the important one.",
      text:
        "The methods do differ. But the method is downstream: it is a way of " +
        "getting at an object that has already been specified. Change what " +
        "the object is and the method follows automatically."
    },
    object: {
      tone: "good",
      verdict: "That is the argument here.",
      text:
        "Watch it happen in the specification: change nothing but the first " +
        "row and the legitimate question, the admissible evidence, the method " +
        "and the defensible claim all move with it - because they were never " +
        "independent of it."
    }
  };

  /* =======================================================================
     Helpers
     ===================================================================== */

  function make(tag, className, text) {
    var node = document.createElement(tag);
    if (className) { node.className = className; }
    if (text !== undefined) { node.textContent = text; }
    return node;
  }

  function clear(node) {
    while (node.firstChild) { node.removeChild(node.firstChild); }
  }

  function lensById(id) {
    return LENSES.filter(function (lens) { return lens.id === id; })[0] || null;
  }

  function homeName(home) {
    if (home === "individual") { return INDIVIDUAL.name; }
    var lens = lensById(home);
    return lens ? lens.name : home;
  }

  /* =======================================================================
     Wiring
     ===================================================================== */

  var shell = InteractiveShell.attach("#lens-switch");
  if (!shell) { return; }

  var $ = function (selector, scope) {
    return (scope || document).querySelector(selector);
  };
  var $$ = function (selector, scope) {
    return Array.prototype.slice.call((scope || document).querySelectorAll(selector));
  };

  var openingForm = $("#opening-form");
  var openingError = $("[data-opening-error]");
  var openingFeedback = $("[data-opening-feedback]");
  var labSection = $("#lab-section");

  var lensChoices = $("[data-lens-choices]");
  var lensNote = $("[data-lens-note]");
  var decisionsSet = $("[data-decisions]");
  var decisionList = $("[data-decision-list]");
  var extendWrap = $("[data-extend-wrap]");

  var specBody = $("[data-spec-body]");
  var coherenceLine = $("[data-coherence]");
  var choiceFeedback = $("[data-choice-feedback]");
  var appraisal = $("[data-appraisal]");
  var appraisalBody = $("[data-appraisal-body]");
  var comparison = $("[data-comparison]");
  var comparisonBody = $("[data-comparison-body]");
  var comparisonNote = $("[data-comparison-note]");

  var claimsSection = $("#claims");
  var claimsForm = $("#claims-form");
  var claimsList = $("[data-claims-list]");
  var claimsFeedback = $("[data-claims-feedback]");

  var INITIAL = {
    stage: "predict",
    lens: null,
    answers: [null, null, null, null, null],
    /* Position within SEQUENCE, not an index into DECISIONS. */
    step: 0,
    extended: false,
    finished: false,
    completed: {}
  };
  var state = null;

  /* True once every decision currently on offer has an answer. */
  function allAnswered() {
    return shownIndices(state).every(function (index) {
      return state.answers[index] !== null;
    });
  }

  /* --- Lens chooser ------------------------------------------------------ */

  function buildLensChoices() {
    clear(lensChoices);
    LENSES.forEach(function (lens) {
      var label = make("label", "lens-option");
      var input = document.createElement("input");
      input.type = "radio";
      input.name = "lens";
      input.value = lens.id;
      input.addEventListener("change", function () {
        chooseLens(lens.id);
      });
      var body = make("span", "lens-option__body");
      body.appendChild(make("span", "lens-option__name", lens.name));
      body.appendChild(make("span", "lens-option__object", "Object: " + lens.object));
      label.appendChild(input);
      label.appendChild(body);
      lensChoices.appendChild(label);
    });
  }

  function chooseLens(id) {
    var lens = lensById(id);
    var complete = allAnswered();
    state.lens = id;
    lensNote.textContent = lens.creed;
    decisionsSet.hidden = false;
    if (complete) {
      state.finished = true;
      recordBuild();
    }
    render();
    shell.announce(
      "Starting point: " + lens.name + ". " +
      (complete
        ? "Specification re-appraised against the new position."
        : "Now make decision " + (state.step + 1) + " of " + shownCount(state) + "."),
      { immediate: true });
  }

  /* --- Decisions --------------------------------------------------------- */

  /* One <li> per decision, built in presentation order. `position` is the
     index within SEQUENCE and is what state.step refers to; `index` is the
     index into DECISIONS and is what state.answers refers to. */
  function buildDecisions() {
    clear(decisionList);
    SEQUENCE.forEach(function (index, position) {
      var decision = DECISIONS[index];
      var item = make("li", "decision-item");
      item.setAttribute("data-index", String(index));

      /* Collapsed summary. A button rather than a link because it changes
         state on this page and nothing is navigated. */
      var summary = make("button", "decision__summary");
      summary.type = "button";
      summary.addEventListener("click", function () {
        state.step = position;
        render();
        focusDecision(position);
      });
      item.appendChild(summary);

      var group = make("fieldset", "decision");
      var legend = make("legend", "decision__legend");
      legend.setAttribute("data-legend", "");
      group.appendChild(legend);
      group.appendChild(make("p", "decision__hint", decision.hint));

      decision.options.forEach(function (option, optionIndex) {
        var label = make("label", "control--choice decision__option");
        var input = document.createElement("input");
        input.type = "radio";
        input.name = "decision-" + decision.id;
        input.value = String(optionIndex);
        input.addEventListener("change", function () {
          state.answers[index] = optionIndex;
          renderStage();
          renderNav();
          shell.announce(
            decision.row + " set. " + option.commits);
        });
        label.appendChild(input);
        label.appendChild(make("span", null, option.text));
        group.appendChild(label);
      });

      var nav = make("div", "decision__nav");

      var back = make("button", "button button--secondary", "Previous");
      back.type = "button";
      back.addEventListener("click", function () {
        state.step = Math.max(0, position - 1);
        render();
        focusDecision(state.step);
      });
      nav.appendChild(back);

      var next = make("button", "button button--primary", "Next");
      next.type = "button";
      next.setAttribute("data-next", "");
      next.addEventListener("click", function () {
        if (position < shownCount(state) - 1) {
          state.step = position + 1;
          render();
          focusDecision(state.step);
        } else {
          state.finished = true;
          recordBuild();
          render();
          appraisal.hidden = false;
          shell.announce("Specification complete. Appraisal below the table.",
            { immediate: true });
        }
      });
      nav.appendChild(next);

      group.appendChild(nav);
      item.appendChild(group);
      decisionList.appendChild(item);
    });
  }

  function focusDecision(position) {
    var group = decisionList.children[position];
    if (!group) { return; }
    var first = group.querySelector(".decision input[type=radio]");
    if (first) { first.focus(); }
  }

  /* --- Rendering ---------------------------------------------------------- */

  function render() {
    renderDecisions();
    renderStage();
    renderNav();
    renderExtend();
    renderClaimsGate();
  }

  function renderDecisions() {
    var total = shownCount(state);
    SEQUENCE.forEach(function (index, position) {
      var decision = DECISIONS[index];
      var item = decisionList.children[position];
      if (!item) { return; }

      /* Decisions beyond the current pass are not in the document flow at
         all, so nothing on offer is disabled-but-visible. */
      item.hidden = position >= total;

      var group = item.querySelector(".decision");
      var summary = item.querySelector(".decision__summary");
      var open = position === state.step && !item.hidden;
      group.hidden = !open;
      summary.hidden = open;

      item.querySelector("[data-legend]").textContent =
        (position + 1) + " of " + total + ". " + decision.label;

      var answer = state.answers[index];
      if (!open) {
        clear(summary);
        var head = make("span", "decision__summary-row");
        head.appendChild(make("span", null, (position + 1) + ". " + decision.row));
        head.appendChild(make("span", "decision__summary-action",
          answer === null ? "Open" : "Change"));
        summary.appendChild(head);
        summary.appendChild(make("span", "decision__summary-value",
          answer === null
            ? "not yet chosen"
            : decision.options[answer].text));
      }

      // Keep the radios in step with state after a reset or worked example.
      $$("input[type=radio]", group).forEach(function (input) {
        input.checked = answer !== null && Number(input.value) === answer;
      });
    });
  }

  function renderNav() {
    var total = shownCount(state);
    SEQUENCE.forEach(function (index, position) {
      var item = decisionList.children[position];
      if (!item) { return; }
      var next = item.querySelector("[data-next]");
      var back = item.querySelector(".decision__nav .button--secondary");
      back.disabled = position === 0;
      next.disabled = state.answers[index] === null;
      next.textContent = position === total - 1
        ? "See what this study can claim"
        : "Next";
    });
  }

  /* The offer to add the last two decisions appears only once the first pass
     is complete, so it never competes with the decision in hand. */
  function renderExtend() {
    extendWrap.hidden = state.extended || !state.lens || !allAnswered();
  }

  /* The challenge needs more than one design to test the claims against. */
  function renderClaimsGate() {
    var runs = Object.keys(state.completed).length;
    var wasHidden = claimsSection.hidden;
    claimsSection.hidden = runs < CLAIMS_UNLOCK_AT;
    if (wasHidden && !claimsSection.hidden) {
      shell.announce(
        "Two lenses run. The challenge is now open at the bottom of the page.",
        { immediate: true });
    }
  }

  function renderStage() {
    renderSpec();
    renderChoiceFeedback();
    renderAppraisal();
    renderComparison();
  }

  function renderSpec() {
    clear(specBody);
    shownIndices(state).forEach(function (index) {
      var decision = DECISIONS[index];
      var answer = state.answers[index];
      var row = make("tr");
      var th = make("th", null, decision.row);
      th.setAttribute("scope", "row");
      row.appendChild(th);

      var td = make("td");
      if (answer === null) {
        td.textContent = "not yet chosen";
        td.setAttribute("data-empty", "yes");
      } else {
        var option = decision.options[answer];
        td.appendChild(make("span", "spec__text", option.text));
        var flag = make("span", "spec__flag");
        var coherent = state.lens && option.home === state.lens;
        flag.textContent = !state.lens
          ? "no position declared"
          : coherent ? "follows from your position" : "in tension: " + homeName(option.home);
        flag.setAttribute("data-state",
          !state.lens ? "none" : coherent ? "ok" : "tension");
        td.appendChild(flag);
      }
      row.appendChild(td);
      specBody.appendChild(row);
    });

    if (!state.lens) {
      coherenceLine.textContent =
        "Declare a starting point above and the specification will be " +
        "appraised against it.";
      coherenceLine.setAttribute("data-state", "none");
      return;
    }

    var made = 0;
    var matched = 0;
    shownIndices(state).forEach(function (index) {
      var answer = state.answers[index];
      if (answer === null) { return; }
      made += 1;
      if (DECISIONS[index].options[answer].home === state.lens) { matched += 1; }
    });

    coherenceLine.textContent = made === 0
      ? "No decisions made yet."
      : matched + " of your " + made + (made === 1 ? " decision follows" : " decisions follow") +
        " from " + lensById(state.lens).name.toLowerCase() + " premises." +
        (matched === made
          ? " Internally coherent so far - which is the minimum, not the aim."
          : " A design can be defensible and mixed; it cannot be defensible and " +
            "silent about the mixture.");
    coherenceLine.setAttribute("data-state",
      made === 0 ? "none" : matched === made ? "ok" : "tension");
  }

  function renderChoiceFeedback() {
    clear(choiceFeedback);
    var index = SEQUENCE[state.step];
    var answer = state.answers[index];
    if (answer === null) { return; }
    var decision = DECISIONS[index];
    var option = decision.options[answer];
    var coherent = state.lens && option.home === state.lens;

    var box = make("div", "verdict");
    box.setAttribute("data-tone", !state.lens ? "neutral" : coherent ? "good" : "caution");
    box.appendChild(make("h4", "verdict__title",
      "Decision " + (state.step + 1) + ": what this commits you to"));
    box.appendChild(make("p", "verdict__body", option.commits));

    if (state.lens && !coherent) {
      var lens = lensById(state.lens);
      var note = "You declared " + lens.name.toLowerCase() +
        ", which takes the object to be " + lens.object + ". " +
        "This choice belongs to " + homeName(option.home).toLowerCase() + ". " +
        option.tension;
      if (option.home === "individual") {
        note += " " + INDIVIDUAL.note;
      }
      box.appendChild(make("p", "verdict__body", note));
    }
    choiceFeedback.appendChild(box);
  }

  function renderAppraisal() {
    if (!state.finished || !state.lens) {
      appraisal.hidden = true;
      return;
    }
    appraisal.hidden = false;
    clear(appraisalBody);

    var lens = lensById(state.lens);
    var indices = shownIndices(state);
    var total = indices.length;
    var matched = 0;
    var offLens = [];
    indices.forEach(function (index) {
      var option = DECISIONS[index].options[state.answers[index]];
      if (option.home === state.lens) {
        matched += 1;
      } else {
        offLens.push(DECISIONS[index].row.toLowerCase() + " (" + homeName(option.home).toLowerCase() + ")");
      }
    });

    appraisalBody.setAttribute("data-tone", matched === total ? "good" : "caution");
    appraisalBody.appendChild(make("h5", "verdict__title",
      matched === total
        ? "A coherent " + lens.name.toLowerCase() + " study"
        : "A mixed study: " + matched + " of " + total + " decisions from " + lens.name.toLowerCase()));

    if (matched < total) {
      appraisalBody.appendChild(make("p", "verdict__body",
        "Off-position decisions: " + offLens.join("; ") + ". A design like " +
        "this can be perfectly good - most real research is impure - but the " +
        "report has to say what it is doing at each of those points."));
    }

    appraisalBody.appendChild(make("p", "verdict__body",
      "What it could claim: " + lens.canSay));
    appraisalBody.appendChild(make("p", "verdict__body",
      "What it could not claim: " + lens.cannotSay));
    appraisalBody.appendChild(make("p", "verdict__body",
      "What it makes hard to see: " + lens.hides));
    appraisalBody.appendChild(make("p", "verdict__note",
      "Where it points: " + lens.action + ". The intervention follows from the object, not from the " +
        "findings - the findings only tell you how much of it to do."));
  }

  function recordBuild() {
    if (!state.lens || !allAnswered()) { return; }
    var indices = shownIndices(state);
    var matched = 0;
    indices.forEach(function (index) {
      if (DECISIONS[index].options[state.answers[index]].home === state.lens) { matched += 1; }
    });
    state.completed[state.lens] = {
      matched: matched,
      total: indices.length,
      answers: state.answers.slice()
    };
  }

  function renderComparison() {
    var ids = Object.keys(state.completed);
    if (!ids.length) {
      comparison.hidden = true;
      return;
    }
    comparison.hidden = false;
    clear(comparisonBody);

    LENSES.forEach(function (lens) {
      if (!state.completed[lens.id]) { return; }
      var record = state.completed[lens.id];
      var row = make("tr");
      var th = make("th");
      th.setAttribute("scope", "row");
      th.appendChild(make("span", "spec__text", lens.name));
      th.appendChild(make("span", "spec__flag",
        record.matched === record.total
          ? "coherent build"
          : "mixed build: " + record.matched + " of " + record.total));
      row.appendChild(th);
      row.appendChild(make("td", null, lens.object));
      row.appendChild(make("td", null, lens.visible));
      row.appendChild(make("td", null, lens.recedes));
      row.appendChild(make("td", null, lens.action));
      comparisonBody.appendChild(row);
    });

    comparisonNote.textContent = ids.length < 2
      ? "One lens run. Use \"Run another lens on this case\" to build a second " +
        "study from the same evidence, then compare the two."
      : "Same school, same log, same policy change, same focus groups. The rows " +
        "differ because the first decision differed. Ask which column your own " +
        "discipline trains you to fill in first, and what that habit costs.";
  }

  /* --- Actions ------------------------------------------------------------ */

  $('[data-action="worked"]').addEventListener("click", function () {
    var lensId = state.lens || "mechanism";
    var input = $('input[name="lens"][value="' + lensId + '"]');
    if (input) { input.checked = true; }
    state.lens = lensId;
    lensNote.textContent = lensById(lensId).creed;
    decisionsSet.hidden = false;
    state.answers = DECISIONS.map(function (decision) {
      var found = 0;
      decision.options.forEach(function (option, index) {
        if (option.home === lensId) { found = index; }
      });
      return found;
    });
    state.step = shownCount(state) - 1;
    state.finished = true;
    recordBuild();
    render();
    shell.announce(
      "Worked example loaded: a coherent " + lensById(lensId).name.toLowerCase() +
      " study, every decision taken from the same premises.",
      { immediate: true });
  });

  /* Adds evidence and claim to the pass in hand. The build is re-recorded so
     the comparison table reports the count the learner actually made. */
  $('[data-action="extend"]').addEventListener("click", function () {
    state.extended = true;
    state.finished = false;
    state.step = CORE_COUNT;
    render();
    focusDecision(CORE_COUNT);
    shell.announce(
      "Two decisions added. Decision " + (CORE_COUNT + 1) + " of " +
      SEQUENCE.length + ": what counts as evidence.",
      { immediate: true });
  });

  $('[data-action="another"]').addEventListener("click", function () {
    state.answers = [null, null, null, null, null];
    state.step = 0;
    state.extended = false;
    state.finished = false;
    state.lens = null;
    $$('input[name="lens"]').forEach(function (input) { input.checked = false; });
    lensNote.textContent =
      "Choose a starting point. Which one is right is not a question a study " +
      "design can settle.";
    decisionsSet.hidden = true;
    appraisal.hidden = true;
    render();
    shell.announce(
      "Cleared. Declare a different starting point and build a second study " +
      "from the same case. Completed lenses are kept in the comparison table.",
      { immediate: true });
  });

  /* --- Opening prediction -------------------------------------------------- */

  function showFeedback(container, tone, verdict, text) {
    clear(container);
    container.setAttribute("data-tone", tone);
    var p = make("p");
    p.appendChild(make("strong", "feedback__verdict", verdict));
    if (text) { p.appendChild(document.createTextNode(" " + text)); }
    container.appendChild(p);
    container.hidden = false;
  }

  function lockForm(form) {
    $$("input, button, select", form).forEach(function (c) { c.disabled = true; });
  }

  function unlockForm(form) {
    $$("input, button, select", form).forEach(function (c) { c.disabled = false; });
    form.reset();
  }

  function unlockLab() {
    state.stage = "explore";
    labSection.hidden = false;
    render();
    shell.announce("Lens switch open. Declare a starting point to begin.",
      { immediate: true });
  }

  openingForm.addEventListener("submit", function (event) {
    event.preventDefault();
    var answer = $('input[name="opening"]:checked', openingForm);
    if (!answer) {
      openingError.textContent =
        "Choose an answer before opening the lens switch.";
      openingError.hidden = false;
      return;
    }
    openingError.hidden = true;
    var feedback = OPENING[answer.value];
    showFeedback(openingFeedback, feedback.tone, feedback.verdict, feedback.text);
    lockForm(openingForm);
    unlockLab();
    $("#lab-heading").focus();
  });

  $('[data-action="skip-opening"]').addEventListener("click", function () {
    openingError.hidden = true;
    showFeedback(openingFeedback, "neutral",
      "Prediction skipped - demonstration mode.", "");
    lockForm(openingForm);
    unlockLab();
  });

  /* --- The challenge -------------------------------------------------------- */

  function buildClaims() {
    clear(claimsList);
    CLAIMS.forEach(function (claim, index) {
      var group = make("fieldset", "prediction__group");
      var legend = make("legend", "prediction__legend",
        "Claim " + (index + 1) + ". " + claim.text);
      group.appendChild(legend);
      CLAIM_OPTIONS.forEach(function (option) {
        var label = make("label", "control--choice");
        var input = document.createElement("input");
        input.type = "radio";
        input.name = "claim-" + claim.id;
        input.value = option.value;
        label.appendChild(input);
        label.appendChild(make("span", null, option.label));
        group.appendChild(label);
      });
      claimsList.appendChild(group);
    });
  }

  var CLAIM_LABELS = {};
  CLAIM_OPTIONS.forEach(function (option) { CLAIM_LABELS[option.value] = option.label; });

  claimsForm.addEventListener("submit", function (event) {
    event.preventDefault();
    var answers = CLAIMS.map(function (claim) {
      var picked = $('input[name="claim-' + claim.id + '"]:checked', claimsForm);
      return picked ? picked.value : null;
    });

    if (answers.indexOf(null) !== -1) {
      showFeedback(claimsFeedback, "caution", "One judgement per claim, please.",
        "A blank is not a verdict, and the interesting disagreements only " +
        "show up when everything has been committed to.");
      return;
    }

    var right = 0;
    CLAIMS.forEach(function (claim, index) {
      if (answers[index] === claim.answer) { right += 1; }
    });

    clear(claimsFeedback);
    claimsFeedback.setAttribute("data-tone", right >= 4 ? "good" : "caution");

    var lead = make("p");
    lead.appendChild(make("strong", "feedback__verdict",
      right + " of 5 judgements match the designs as specified."));
    lead.appendChild(document.createTextNode(
      " Read the two \"none of these designs\" items even if you got them " +
      "right: they are where the exercise is."));
    claimsFeedback.appendChild(lead);

    var list = make("ol", "claims__results");
    CLAIMS.forEach(function (claim, index) {
      var li = make("li");
      var agreed = answers[index] === claim.answer;
      li.setAttribute("data-agreed", agreed ? "yes" : "no");
      var head = make("p", "claims__result-head");
      head.appendChild(make("strong", null,
        "Claim " + (index + 1) + ": " + claim.verdict));
      head.appendChild(document.createTextNode(
        agreed ? " That is what you said."
          : " You said: " + CLAIM_LABELS[answers[index]].toLowerCase() + "."));
      li.appendChild(head);
      li.appendChild(make("p", null, claim.why));
      list.appendChild(li);
    });
    claimsFeedback.appendChild(list);
    claimsFeedback.hidden = false;

    shell.announce("Five claims judged. " + right + " match the designs as specified.",
      { immediate: true });
  });

  /* --- Reset and start-up ---------------------------------------------------- */

  shell.onReset(function () {
    state = JSON.parse(JSON.stringify(INITIAL));
    unlockForm(openingForm);
    openingFeedback.hidden = true;
    openingError.hidden = true;
    labSection.hidden = true;
    $$('input[name="lens"]').forEach(function (input) { input.checked = false; });
    lensNote.textContent =
      "Choose a starting point. Which one is right is not a question a study " +
      "design can settle.";
    decisionsSet.hidden = true;
    appraisal.hidden = true;
    claimsForm.reset();
    claimsFeedback.hidden = true;
    claimsSection.hidden = true;
    render();
  });

  buildLensChoices();
  buildDecisions();
  buildClaims();

  shell.reset({ silent: true });
  shell.announce(
    "Ready. Answer the question above to open the lens switch.",
    { immediate: true });
})();
