/* =========================================================================
   Twin-Study Simulator
   -------------------------------------------------------------------------
   Students set the true variance components, generate clearly fictional twin
   and sibling pairs, read the correlations off, and estimate ACE back out
   with Falconer's formulae. Then they switch on assumption violations and
   watch the estimates go wrong in specific, predictable directions while the
   truth stays where it was put.

   THE EDUCATIONAL MODEL
   ---------------------
   Each person's phenotype is

       P = a·A + c·C + e·E + m·M

   where A is additive genetic value, C the environment shared by a pair, E
   the non-shared environment, and M measurement error. The squared
   coefficients are the variance components and sum to 1.

   Pair resemblance is generated by how much of A and C the two members share:

       MZ twins     share A completely (r = 1) and C completely
       DZ twins     share A on average one half, and C completely
       Full sibs    share A on average one half, and C completely
                    (they differ from DZ twins only through the violations)

   E and M are never shared. Expected correlations are therefore

       r(MZ) = a² + c²
       r(DZ) = 0.5·a² + c²

   and Falconer's estimates run the other way:

       h²  = 2·(r_MZ − r_DZ)
       c²  = 2·r_DZ − r_MZ
       e²  = 1 − r_MZ            (which absorbs measurement error)

   VIOLATIONS
   ----------
   Three are offered, each with a specific, directional consequence:

     unequal environments   MZ pairs share more C than DZ pairs. Inflates
                            r(MZ) only, so h² is overestimated and c²
                            underestimated.
     assortative mating     parents resemble each other, so DZ pairs share
                            more than half of A. Raises r(DZ), so the doubled
                            difference shrinks and h² is UNDERestimated.
     gene-environment       A and C correlate, so genetic and shared-
     correlation            environmental influence cannot be cleanly
                            separated; the model attributes the covariance to
                            whichever term the formula reaches first.

   Everything is generated with a seeded generator; the seed is shown and
   settable so a class demonstration is exactly reproducible.

   WHAT HERITABILITY IS NOT
   ------------------------
   Stated on the page, in the debrief and here: h² is the proportion of
   VARIANCE IN A POPULATION attributable to genetic variance in THAT
   population under THOSE environmental conditions. It is not the proportion
   of any individual's trait caused by genes; it says nothing about whether a
   trait can be changed; and it changes when the environment changes, without
   any gene changing. The tool includes a control that demonstrates the last
   point directly.

   No data leave the browser. There is no storage and no network request.
   ========================================================================= */

(function () {
  "use strict";

  var PAIRS_PER_GROUP = 250;

  var GROUPS = [
    { id: "mz", name: "Identical (MZ) twins", shareA: 1.0, shareC: 1.0 },
    { id: "dz", name: "Fraternal (DZ) twins", shareA: 0.5, shareC: 1.0 },
    { id: "sib", name: "Non-twin siblings", shareA: 0.5, shareC: 1.0 }
  ];

  /* =======================================================================
     Seeded randomness
     ===================================================================== */

  function mulberry32(seed) {
    var a = seed >>> 0;
    return function () {
      a += 0x6d2b79f5;
      var t = a;
      t = Math.imul(t ^ (t >>> 15), t | 1);
      t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  function makeNormal(random) {
    var u = Math.max(random(), 1e-9);
    var v = random();
    return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
  }

  /* =======================================================================
     Generation
     ===================================================================== */

  function clamp(value, low, high) {
    return Math.max(low, Math.min(high, value));
  }

  /**
   * Generate pairs for one group.
   * @param {function} random
   * @param {object} group
   * @param {object} truth   { a2, c2, e2, m2 }
   * @param {object} violations { unequalEnv, assortative, gxeCorr }
   */
  function generateGroup(random, group, truth, violations) {
    var a = Math.sqrt(truth.a2);
    var c = Math.sqrt(truth.c2);
    var e = Math.sqrt(truth.e2);
    var m = Math.sqrt(truth.m2);

    // Violation 1: MZ pairs share more of C than DZ/sibling pairs do.
    var shareC = group.shareC;
    if (violations.unequalEnv > 0 && group.id !== "mz") {
      shareC = clamp(group.shareC - violations.unequalEnv, 0, 1);
    }

    // Violation 2: assortative mating raises the genetic sharing of pairs who
    // are not identical, because the parents themselves resemble each other.
    var shareA = group.shareA;
    if (violations.assortative > 0 && group.id !== "mz") {
      shareA = clamp(group.shareA + violations.assortative * 0.5, 0, 1);
    }

    // Non-twin siblings additionally share less environment than twins do:
    // they are not the same age and are not in the same class or cohort.
    if (group.id === "sib") {
      shareC = clamp(shareC - 0.25, 0, 1);
    }

    var one = [];
    var two = [];

    for (var i = 0; i < PAIRS_PER_GROUP; i += 1) {
      // Shared and unshared parts of A.
      var aCommon = makeNormal(random);
      var aUnique1 = makeNormal(random);
      var aUnique2 = makeNormal(random);
      var a1 = Math.sqrt(shareA) * aCommon + Math.sqrt(1 - shareA) * aUnique1;
      var a2v = Math.sqrt(shareA) * aCommon + Math.sqrt(1 - shareA) * aUnique2;

      // Shared and unshared parts of C.
      var cCommon = makeNormal(random);
      var cUnique1 = makeNormal(random);
      var cUnique2 = makeNormal(random);
      var c1 = Math.sqrt(shareC) * cCommon + Math.sqrt(1 - shareC) * cUnique1;
      var c2v = Math.sqrt(shareC) * cCommon + Math.sqrt(1 - shareC) * cUnique2;

      // Violation 3: gene-environment correlation. The shared environment
      // partly follows the genetic value, so A and C are no longer
      // independent and the two cannot be cleanly apportioned.
      if (violations.gxeCorr > 0) {
        var r = violations.gxeCorr;
        c1 = r * a1 + Math.sqrt(1 - r * r) * c1;
        c2v = r * a2v + Math.sqrt(1 - r * r) * c2v;
      }

      one.push(
        a * a1 + c * c1 + e * makeNormal(random) + m * makeNormal(random));
      two.push(
        a * a2v + c * c2v + e * makeNormal(random) + m * makeNormal(random));
    }

    return { one: one, two: two };
  }

  function correlation(x, y) {
    var n = x.length;
    var mx = x.reduce(function (a, b) { return a + b; }, 0) / n;
    var my = y.reduce(function (a, b) { return a + b; }, 0) / n;
    var sxy = 0;
    var sxx = 0;
    var syy = 0;
    for (var i = 0; i < n; i += 1) {
      var dx = x[i] - mx;
      var dy = y[i] - my;
      sxy += dx * dy;
      sxx += dx * dx;
      syy += dy * dy;
    }
    return sxx > 0 && syy > 0 ? sxy / Math.sqrt(sxx * syy) : 0;
  }

  function generate(settings) {
    var random = mulberry32(settings.seed);
    var result = {};
    GROUPS.forEach(function (group) {
      var pairs = generateGroup(random, group, settings.truth, settings.violations);
      result[group.id] = {
        pairs: pairs,
        r: correlation(pairs.one, pairs.two)
      };
    });
    return result;
  }

  /** Falconer's estimates from the observed twin correlations. */
  function falconer(rMz, rDz) {
    var h2 = clamp(2 * (rMz - rDz), 0, 1);
    var c2 = clamp(2 * rDz - rMz, 0, 1);
    var e2 = clamp(1 - rMz, 0, 1);
    return { h2: h2, c2: c2, e2: e2 };
  }

  /* =======================================================================
     Helpers
     ===================================================================== */

  function fmt(value, places) {
    return value === null || value === undefined || isNaN(value)
      ? "—"
      : value.toFixed(places === undefined ? 2 : places);
  }

  function make(tag, className, text) {
    var node = document.createElement(tag);
    if (className) {
      node.className = className;
    }
    if (text !== undefined) {
      node.textContent = text;
    }
    return node;
  }

  function clear(node) {
    while (node.firstChild) {
      node.removeChild(node.firstChild);
    }
  }

  /* =======================================================================
     Wiring
     ===================================================================== */

  var shell = InteractiveShell.attach("#twins");
  if (!shell) {
    return;
  }

  var page = document;
  var $ = function (selector, scope) {
    return (scope || page).querySelector(selector);
  };

  var scatterChart = $("[data-scatter]");
  var scatterTable = $("[data-scatter-table]");
  var readout = $("[data-readout]");
  var estimateTable = $("[data-estimate-table]");
  var estimateNote = $("[data-estimate-note]");
  var violationNote = $("[data-violation-note]");
  var seedInput = $("#seed-input");

  var openingForm = $("#opening-form");
  var openingError = $("[data-opening-error]");
  var openingFeedback = $("[data-opening-feedback]");
  var skipOpening = $('[data-action="skip-opening"]');
  var mainSection = $("#simulator-section");

  var challengeForm = $("#challenge-form");
  var challengeFeedback = $("[data-challenge-feedback]");
  var envButton = $('[data-action="equalise"]');
  var envNote = $("[data-env-note]");

  /* The default has a substantial shared-environment share on purpose. The
     "equalise everyone's environment" demonstration works by removing C and
     showing h² rise as a consequence of the denominator shrinking — and if C
     starts small there is nothing to remove and the rise is too slight to
     make the point. With C at 0.35 the estimate moves by around 0.20. */
  var INITIAL = {
    seed: 4471,
    truth: { a2: 0.40, c2: 0.35, e2: 0.20, m2: 0.05 },
    violations: { unequalEnv: 0, assortative: 0, gxeCorr: 0 },
    envEqualised: false
  };
  var state = null;
  var data = null;
  var rangeSyncs = [];

  function bindRange(input, options) {
    var settings = options || {};
    var output = page.querySelector('output[for="' + input.id + '"]');
    function sync() {
      var value = Number(input.value);
      if (output) {
        output.textContent = settings.format ? settings.format(value) : String(value);
      }
      input.setAttribute(
        "aria-valuetext", (settings.describe || settings.format || String)(value));
      if (settings.onInput) {
        settings.onInput(value);
      }
    }
    input.addEventListener("input", sync);
    rangeSyncs.push(sync);
    return sync;
  }

  function syncRanges() {
    rangeSyncs.forEach(function (sync) { sync(); });
  }

  /* --- The variance components -------------------------------------------
     Three sliders for A, C and E; measurement error is separate. They are
     renormalised so the four always sum to 1, and the normalised values are
     what the page reports as the truth. */

  function normaliseTruth() {
    var raw = state.truth;
    var total = raw.a2 + raw.c2 + raw.e2 + raw.m2;
    if (total <= 0) {
      return { a2: 0.25, c2: 0.25, e2: 0.25, m2: 0.25 };
    }
    return {
      a2: raw.a2 / total,
      c2: raw.c2 / total,
      e2: raw.e2 / total,
      m2: raw.m2 / total
    };
  }

  ["a2", "c2", "e2", "m2"].forEach(function (key) {
    bindRange($("#" + key + "-range"), {
      format: function (value) {
        return (value / 100).toFixed(2);
      },
      describe: function (value) {
        return (value / 100).toFixed(2) + " before renormalising";
      },
      onInput: function (value) {
        state.truth[key] = value / 100;
        regenerate();
        render();
      }
    });
  });

  [
    ["unequalEnv", "#unequal-range"],
    ["assortative", "#assortative-range"],
    ["gxeCorr", "#gxe-range"]
  ].forEach(function (entry) {
    bindRange($(entry[1]), {
      format: function (value) {
        return (value / 100).toFixed(2);
      },
      describe: function (value) {
        return value === 0 ? "assumption held" : "violation set to " + (value / 100).toFixed(2);
      },
      onInput: function (value) {
        state.violations[entry[0]] = value / 100;
        regenerate();
        render();
      }
    });
  });

  seedInput.addEventListener("change", function () {
    var value = parseInt(seedInput.value, 10);
    if (isNaN(value)) {
      seedInput.value = String(state.seed);
      return;
    }
    state.seed = value;
    regenerate();
    render();
    shell.announce("Seed " + value + ". New sample drawn.", { immediate: true });
  });

  $('[data-action="resample"]').addEventListener("click", function () {
    state.seed = (state.seed * 1103515245 + 12345) % 2147483647;
    if (state.seed < 0) {
      state.seed += 2147483647;
    }
    seedInput.value = String(state.seed);
    regenerate();
    render();
    shell.announce(
      "New sample of " + PAIRS_PER_GROUP + " pairs per group, seed " +
        state.seed + ".",
      { immediate: true });
  });

  function regenerate() {
    data = generate({
      seed: state.seed,
      truth: normaliseTruth(),
      violations: state.violations
    });
  }

  /* --- Rendering ------------------------------------------------------------ */

  function render() {
    if (mainSection.hidden) {
      return;
    }
    var truth = normaliseTruth();
    renderScatter();
    renderReadout(truth);
    renderEstimates(truth);
    renderViolationNote(truth);
  }

  function renderScatter() {
    var NS = "http://www.w3.org/2000/svg";
    var SIZE = 150;
    var GAP = 12;
    var TOP = 18;

    clear(scatterChart);
    scatterChart.setAttribute(
      "viewBox", "0 0 " + (GROUPS.length * (SIZE + GAP)) + " " + (SIZE + TOP + 22));

    GROUPS.forEach(function (group, index) {
      var left = index * (SIZE + GAP);
      var entry = data[group.id];

      var title = document.createElementNS(NS, "text");
      title.setAttribute("x", String(left + SIZE / 2));
      title.setAttribute("y", "12");
      title.setAttribute("text-anchor", "middle");
      title.setAttribute("class", "chart__label");
      title.textContent = group.id.toUpperCase();
      scatterChart.appendChild(title);

      var frame = document.createElementNS(NS, "rect");
      frame.setAttribute("x", String(left));
      frame.setAttribute("y", String(TOP));
      frame.setAttribute("width", String(SIZE));
      frame.setAttribute("height", String(SIZE));
      frame.setAttribute("class", "chart__track");
      scatterChart.appendChild(frame);

      // Points, clipped to +/- 3 SD.
      var points = [];
      for (var i = 0; i < entry.pairs.one.length; i += 1) {
        var x = clamp(entry.pairs.one[i], -3, 3);
        var y = clamp(entry.pairs.two[i], -3, 3);
        points.push(
          "M " + (left + ((x + 3) / 6) * SIZE).toFixed(1) + " " +
          (TOP + (1 - (y + 3) / 6) * SIZE).toFixed(1) + " l 0.01 0");
      }
      var dots = document.createElementNS(NS, "path");
      dots.setAttribute("d", points.join(" "));
      dots.setAttribute("class", "scatter__points");
      scatterChart.appendChild(dots);

      var label = document.createElementNS(NS, "text");
      label.setAttribute("x", String(left + SIZE / 2));
      label.setAttribute("y", String(TOP + SIZE + 16));
      label.setAttribute("text-anchor", "middle");
      label.setAttribute("class", "chart__count");
      label.textContent = "r = " + fmt(entry.r);
      scatterChart.appendChild(label);
    });

    clear(scatterTable);
    GROUPS.forEach(function (group) {
      var row = make("tr");
      var th = make("th", null, group.name);
      th.setAttribute("scope", "row");
      row.appendChild(th);
      row.appendChild(make("td", null, String(PAIRS_PER_GROUP)));
      row.appendChild(make("td", null, fmt(data[group.id].r)));
      scatterTable.appendChild(row);
    });
  }

  function renderReadout(truth) {
    clear(readout);
    [
      ["True A (additive genetic)", fmt(truth.a2)],
      ["True C (shared environment)", fmt(truth.c2)],
      ["True E (non-shared)", fmt(truth.e2)],
      ["True measurement error", fmt(truth.m2)]
    ].forEach(function (pair) {
      var cell = make("div");
      cell.appendChild(make("dt", null, pair[0]));
      cell.appendChild(make("dd", null, pair[1]));
      readout.appendChild(cell);
    });
  }

  function renderEstimates(truth) {
    var rMz = data.mz.r;
    var rDz = data.dz.r;
    var est = falconer(rMz, rDz);

    clear(estimateTable);
    [
      ["A — additive genetic (h²)", truth.a2, est.h2],
      ["C — shared environment (c²)", truth.c2, est.c2],
      ["E — non-shared + error (e²)", truth.e2 + truth.m2, est.e2]
    ].forEach(function (row) {
      var tr = make("tr");
      var th = make("th", null, row[0]);
      th.setAttribute("scope", "row");
      tr.appendChild(th);
      tr.appendChild(make("td", null, fmt(row[1])));
      tr.appendChild(make("td", null, fmt(row[2])));
      var diff = row[2] - row[1];
      tr.appendChild(
        make("td", null,
          (diff > 0 ? "+" : "") + fmt(diff) +
          (Math.abs(diff) < 0.06 ? " (close)"
            : diff > 0 ? " (overestimate)" : " (underestimate)")));
      estimateTable.appendChild(tr);
    });

    estimateNote.textContent =
      "Falconer's estimates: h² = 2(r_MZ − r_DZ) = 2(" + fmt(rMz) + " − " +
      fmt(rDz) + ") = " + fmt(est.h2) + "; c² = 2r_DZ − r_MZ = " + fmt(est.c2) +
      "; e² = 1 − r_MZ = " + fmt(est.e2) + ". Note that e² absorbs measurement " +
      "error: anything unreliable in the measure is counted as non-shared " +
      "environment by this model.";
  }

  function renderViolationNote(truth) {
    var v = state.violations;
    var notes = [];

    if (v.unequalEnv > 0) {
      notes.push(
        "Unequal environments: identical twins are sharing more of their " +
        "environment than fraternal twins are. That raises r(MZ) without " +
        "raising r(DZ), and since h² is twice the gap, it inflates the " +
        "genetic estimate and shrinks the shared-environment estimate. The " +
        "equal-environments assumption is the one twin studies are most often " +
        "criticised for, and this is what its failure does."
      );
    }
    if (v.assortative > 0) {
      notes.push(
        "Assortative mating: parents resemble each other on the trait, so " +
        "fraternal twins and siblings share more than half their additive " +
        "genetic value. That raises r(DZ), narrows the gap, and makes h² an " +
        "UNDERestimate — the opposite direction from the previous violation, " +
        "which is why the two can partly mask each other."
      );
    }
    if (v.gxeCorr > 0) {
      notes.push(
        "Gene–environment correlation: the environment a pair experiences now " +
        "depends partly on their genetic value. A and C are no longer " +
        "independent, so the covariance between them has to be assigned " +
        "somewhere, and the model assigns it to the genetic term by " +
        "construction. \"Heritable\" here includes the environments that " +
        "people's own characteristics helped bring about."
      );
    }

    if (!notes.length) {
      notes.push(
        "All three assumptions currently hold, which is why the estimates are " +
        "close to the truth. Real twin studies cannot switch them on and off, " +
        "and cannot see the truth column at all."
      );
    }

    violationNote.textContent = notes.join(" ");
    violationNote.setAttribute(
      "data-tone",
      v.unequalEnv + v.assortative + v.gxeCorr > 0 ? "warn" : "good");
  }

  /* --- The environment demonstration ---------------------------------------
     Heritability changes when the environment changes, with no gene changing.
     Pressing the button collapses shared-environment variance towards zero,
     which raises h² — because h² is a ratio, and the denominator shrank. */

  envButton.addEventListener("click", function () {
    // Capture the estimate before the change, so the note can quote the real
    // figures rather than an assumed starting point.
    var beforeH2 = falconer(data.mz.r, data.dz.r).h2;

    state.envEqualised = !state.envEqualised;
    if (state.envEqualised) {
      state.truth.c2 = 0.02;
      state.truth.e2 = INITIAL.truth.e2;
    } else {
      state.truth.c2 = INITIAL.truth.c2;
      state.truth.e2 = INITIAL.truth.e2;
    }
    $("#c2-range").value = String(Math.round(state.truth.c2 * 100));
    $("#e2-range").value = String(Math.round(state.truth.e2 * 100));
    syncRanges();
    regenerate();
    render();

    var truth = normaliseTruth();
    var est = falconer(data.mz.r, data.dz.r);
    envNote.textContent = state.envEqualised
      ? "Shared-environment variance has been almost removed — imagine every " +
        "family given the same resources. No gene has changed, and the " +
        "genetic slider has not moved. Heritability has gone from " +
        fmt(beforeH2) + " to " + fmt(est.h2) + ", because h² is a ratio and " +
        "the denominator just shrank. A high heritability can therefore be a " +
        "sign that environments have been made more equal, which is close to " +
        "the reverse of how the number is usually reported."
      : "Shared-environment variance restored. Heritability has gone from " +
        fmt(beforeH2) + " back to " + fmt(est.h2) + ". The genes never moved " +
        "in either direction.";
    envNote.hidden = false;
    envButton.textContent = state.envEqualised
      ? "Restore the original environment"
      : "Equalise everyone's environment";

    shell.announce(
      "Environment " + (state.envEqualised ? "equalised" : "restored") +
        ". Heritability estimate now " + fmt(est.h2) + ".",
      { immediate: true });
  });

  /* --- Opening prediction ---------------------------------------------------- */

  var OPENING = {
    individual: {
      tone: "warn",
      verdict: "No — and this is the single most common error about it.",
      text:
        "Heritability is a property of variance in a population, not of a " +
        "person. \"h² = 0.5\" does not mean half of anybody's trait was caused " +
        "by their genes. There is no coherent way to divide one individual's " +
        "characteristic into a genetic half and an environmental half: they " +
        "had one set of genes and one life, and both were necessary for all " +
        "of it."
    },
    population: {
      tone: "good",
      verdict: "Yes.",
      text:
        "The proportion of variance in a particular population, measured in " +
        "particular environments at a particular time. Change the population " +
        "or the range of environments and the number changes, without any " +
        "gene changing. The tool has a control that demonstrates exactly that."
    },
    fixed: {
      tone: "warn",
      verdict: "No.",
      text:
        "Heritability says nothing about malleability. Height is highly " +
        "heritable and has risen substantially in a century through nutrition. " +
        "Requiring spectacles is a highly heritable trait with a trivially " +
        "effective environmental intervention."
    },
    genes: {
      tone: "caution",
      verdict: "Not quite.",
      text:
        "It does not tell you which genes, how many, or what they do. It is a " +
        "variance ratio estimated from resemblance between relatives, and it " +
        "is entirely compatible with thousands of variants of tiny effect, " +
        "with none of them identified."
    }
  };

  openingForm.addEventListener("submit", function (event) {
    event.preventDefault();
    var answer = $('input[name="opening"]:checked', openingForm);
    if (!answer) {
      openingError.textContent =
        "Choose an answer before the simulator opens. This is the definition " +
        "everything else depends on.";
      openingError.hidden = false;
      return;
    }
    openingError.hidden = true;
    var feedback = OPENING[answer.value];
    showFeedback(openingFeedback, feedback.tone, feedback.verdict, feedback.text);
    lockForm(openingForm);
    mainSection.hidden = false;
    regenerate();
    render();
    $("#simulator-heading").focus();
    shell.announce("Simulator unlocked.", { immediate: true });
  });

  skipOpening.addEventListener("click", function () {
    openingError.hidden = true;
    showFeedback(
      openingFeedback, "neutral", "Prediction skipped — demonstration mode.",
      "");
    lockForm(openingForm);
    mainSection.hidden = false;
    regenerate();
    render();
    shell.announce("Simulator unlocked.", { immediate: true });
  });

  /* --- Challenge -------------------------------------------------------------- */

  challengeForm.addEventListener("submit", function (event) {
    event.preventDefault();
    var answer = $('input[name="challenge"]:checked', challengeForm);
    if (!answer) {
      showFeedback(challengeFeedback, "caution", "Choose an answer first.", "");
      return;
    }
    var correct = answer.value === "unequal";
    showFeedback(
      challengeFeedback,
      correct ? "good" : "caution",
      correct ? "Yes." : "Not this one.",
      "Set the unequal-environments slider above zero on its own and watch " +
        "the estimate table: h² rises above the truth and c² falls below it. " +
        "That violation raises the MZ correlation without touching the DZ " +
        "correlation, and h² is twice the gap between them. Assortative mating " +
        "pushes the other way, so a study with both violations can report a " +
        "heritability that looks unremarkable while being wrong twice over."
    );
    shell.announce("Challenge answered.", { immediate: true });
  });

  function showFeedback(container, tone, verdict, text) {
    clear(container);
    container.setAttribute("data-tone", tone);
    var paragraph = make("p");
    paragraph.appendChild(make("strong", "feedback__verdict", verdict));
    if (text) {
      paragraph.appendChild(document.createTextNode(" " + text));
    }
    container.appendChild(paragraph);
    container.hidden = false;
  }

  function lockForm(form) {
    Array.prototype.forEach.call(
      form.querySelectorAll("input, button"),
      function (control) { control.disabled = true; });
  }

  function unlockForm(form) {
    Array.prototype.forEach.call(
      form.querySelectorAll("input, button"),
      function (control) { control.disabled = false; });
    form.reset();
  }

  /* --- Reset -------------------------------------------------------------------- */

  shell.onReset(function () {
    state = JSON.parse(JSON.stringify(INITIAL));

    unlockForm(openingForm);
    openingFeedback.hidden = true;
    openingError.hidden = true;
    mainSection.hidden = true;

    challengeForm.reset();
    challengeFeedback.hidden = true;
    envNote.hidden = true;
    envButton.textContent = "Equalise everyone's environment";

    seedInput.value = String(state.seed);
    $("#a2-range").value = String(Math.round(state.truth.a2 * 100));
    $("#c2-range").value = String(Math.round(state.truth.c2 * 100));
    $("#e2-range").value = String(Math.round(state.truth.e2 * 100));
    $("#m2-range").value = String(Math.round(state.truth.m2 * 100));
    $("#unequal-range").value = "0";
    $("#assortative-range").value = "0";
    $("#gxe-range").value = "0";

    regenerate();
    syncRanges();
  });

  /* --- Start-up ------------------------------------------------------------------ */

  shell.reset({ silent: true });
  shell.announce(
    "Ready. Answer the definition question above to open the simulator.",
    { immediate: true });
})();
