/* =========================================================================
   The Alpha Trap
   -------------------------------------------------------------------------
   Students build a scale from a fictional item bank and watch Cronbach's
   alpha respond. Because several items are deliberate paraphrases of one
   another, alpha can be pushed high by repetition alone — at which point the
   scale is revealed to correlate poorly with a simulated outcome.

   THE EDUCATIONAL MODEL
   ---------------------
   Every item is standardised (mean 0, variance 1) and generated by four
   independent standard-normal sources:

       X_i = g_i * G  +  f_i * F(facet)  +  w_i * W(wording family)  +  e_i

     G  a general "academic conscientiousness" factor shared by all items;
     F  a factor specific to one of the five content areas;
     W  a factor shared only by items that paraphrase each other — the
        wording-specific variance that produces a bloated specific factor;
     e  item-specific error, sized so the four coefficients give unit
        variance.

   Because the items are standardised, the correlation between two of them is

       r_ij = g_i g_j  +  f_i f_j [same area]  +  w_i w_j [same wording family]

   and Cronbach's alpha follows from the correlation matrix in the usual way.
   For standardised items the raw and standardised forms of alpha coincide;
   this file computes it from the total-score variance, which is the more
   familiar expression:

       alpha = (k / (k - 1)) * (1 - k / Var(T))

   The simulated outcome — fictional tutor-rated dependability — is

       Y = a * G  +  b * (F1 + F2 + F3 + F4 + F5) / sqrt(5)  +  noise

   so it responds to the general factor AND to breadth of content coverage,
   but is completely indifferent to wording-specific variance. Adding
   paraphrases therefore inflates Var(T) — the denominator of the validity
   coefficient — while contributing nothing to its numerator. That single
   asymmetry is the whole demonstration.

   DELIBERATE SIMPLIFICATIONS
   --------------------------
   * No sampling error. Every figure is the value the model implies for a
     population, not an estimate from a sample. A real alpha carries a
     confidence interval; the page says so, and the teaching notes say so.
   * Items are treated as continuous and standardised, so no distinction is
     drawn between alpha, standardised alpha and ordinal alpha.
   * A single wording family per content area, which makes the structure
     legible to a student in a seminar. Real item pools are messier.
   * Loadings are chosen so that the target of Round 1 is unreachable without
     repetition (the widest scale with no repeated wording reaches 0.844).
     That is a property of these numbers, not of alpha in general, and it is
     there to make the trap reliable in a classroom.

   No data leave the browser. There is no storage and no network request.
   ========================================================================= */

(function () {
  "use strict";

  /* =======================================================================
     1. The model
     ===================================================================== */

  /* Loadings for the two kinds of item. Squares must not exceed 1; the
     remainder is item-specific error.
       distinct:   0.55^2 + 0.32^2          = 0.405, error 0.595
       paraphrase: 0.45^2 + 0.30^2 + 0.62^2 = 0.677, error 0.323
     The implied correlations are:
       two paraphrases of each other          0.677
       same area, differently worded          0.344
       same area, both distinct               0.405
       different areas                        0.203 to 0.303          */
  var LOADINGS = {
    distinct: { general: 0.55, facet: 0.32, wording: 0 },
    paraphrase: { general: 0.45, facet: 0.30, wording: 0.62 }
  };

  /* The simulated outcome's loadings. `facets` is spread across the five
     content factors, so an item earns outcome-relevant variance only through
     the general factor and its own content area. */
  var CRITERION = { general: 0.55, facets: 0.55 };

  var FACETS = [
    { id: "planning", name: "Planning ahead", short: "Planning" },
    { id: "orderliness", name: "Orderliness", short: "Orderliness" },
    { id: "persistence", name: "Persistence", short: "Persistence" },
    { id: "punctuality", name: "Punctuality", short: "Punctuality" },
    { id: "focus", name: "Resisting distraction", short: "Distraction" }
  ];

  /* Wording families. Items sharing one of these are near-paraphrases: the
     name is what the redundancy panel calls the family in plain English. */
  var FAMILIES = {
    "plan-ahead": "planning the week in advance",
    "tidy-notes": "keeping tidy notes",
    "keep-going": "carrying on when bored",
    deadline: "meeting deadlines",
    "phone-away": "putting the phone away"
  };

  /* The item bank. Written for this tool; no published instrument is
     reproduced. `family: null` means the item has no near-duplicate. */
  var ITEMS = [
    { id: "P1", facet: "planning", family: null, text: "I work out what a piece of coursework will involve before I start it." },
    { id: "P2", facet: "planning", family: null, text: "I break large pieces of work into smaller stages." },
    { id: "P3", facet: "planning", family: "plan-ahead", text: "I plan my study week in advance." },
    { id: "P4", facet: "planning", family: "plan-ahead", text: "I decide in advance what I will study each week." },
    { id: "P5", facet: "planning", family: "plan-ahead", text: "I map out my week's studying before the week begins." },

    { id: "O1", facet: "orderliness", family: null, text: "I can find a document from last term without hunting for it." },
    { id: "O2", facet: "orderliness", family: null, text: "My study space is set up so that I can start work straight away." },
    { id: "O3", facet: "orderliness", family: "tidy-notes", text: "I keep my lecture notes tidy and organised." },
    { id: "O4", facet: "orderliness", family: "tidy-notes", text: "My lecture notes are kept in good order." },

    { id: "R1", facet: "persistence", family: null, text: "I keep working on a difficult problem after my first attempt fails." },
    { id: "R2", facet: "persistence", family: null, text: "I finish optional reading that I have started." },
    { id: "R3", facet: "persistence", family: "keep-going", text: "I keep going with a task even when it stops being interesting." },
    { id: "R4", facet: "persistence", family: "keep-going", text: "I carry on with work even once it has become boring." },
    { id: "R5", facet: "persistence", family: "keep-going", text: "I stick with a task after the interest has worn off." },

    { id: "T1", facet: "punctuality", family: null, text: "I arrive at seminars before they start." },
    { id: "T2", facet: "punctuality", family: "deadline", text: "I hand in coursework on time." },
    { id: "T3", facet: "punctuality", family: "deadline", text: "I submit assignments by the deadline." },
    { id: "T4", facet: "punctuality", family: "deadline", text: "I get my written work in before the due date." },
    { id: "T5", facet: "punctuality", family: "deadline", text: "My coursework is handed in on or before its deadline." },
    { id: "T6", facet: "punctuality", family: "deadline", text: "I meet submission deadlines for my written work." },

    { id: "F1", facet: "focus", family: null, text: "I can work in a busy room without losing the thread." },
    { id: "F2", facet: "focus", family: null, text: "I return to what I was doing quickly after an interruption." },
    { id: "F3", facet: "focus", family: "phone-away", text: "I put my phone out of reach while studying." },
    { id: "F4", facet: "focus", family: "phone-away", text: "I keep my phone somewhere I cannot pick it up when I am working." }
  ];

  var ITEM_BY_ID = {};
  ITEMS.forEach(function (item) {
    item.loadings = item.family ? LOADINGS.paraphrase : LOADINGS.distinct;
    ITEM_BY_ID[item.id] = item;
  });

  /* Round targets. Round 1's 0.85 is deliberately just above the 0.844 that
     the widest no-repeated-wording scale can reach, so the target cannot be
     met without repetition. Round 2 asks for a defensible scale instead of a
     maximal one. */
  var ROUND_ONE = { targetAlpha: 0.85, minItemsToAdvance: 6 };
  var ROUND_TWO = {
    minAlpha: 0.70,
    minItems: 8,
    maxItems: 12,
    requiredFacets: FACETS.length
  };

  /* Worked examples, both computed rather than described: the alpha-chasing
     shortcut, and a scale that satisfies Round 2. */
  var EXAMPLES = {
    round1: ["T2", "T3", "T4", "T5", "T6"],
    round2: ["P1", "P2", "O1", "O2", "R1", "R2", "T1", "T2", "F1", "F2"]
  };

  /* =======================================================================
     2. Psychometrics
     ===================================================================== */

  /**
   * Model-implied correlation between two items.
   * @param {object} a
   * @param {object} b
   * @returns {number}
   */
  function itemCorrelation(a, b) {
    var r = a.loadings.general * b.loadings.general;
    if (a.facet === b.facet) {
      r += a.loadings.facet * b.loadings.facet;
    }
    if (a.family && a.family === b.family) {
      r += a.loadings.wording * b.loadings.wording;
    }
    return r;
  }

  /**
   * Model-implied covariance between one item and the simulated outcome.
   * Both are standardised, so this is also their correlation.
   * @param {object} item
   * @returns {number}
   */
  function itemOutcomeCovariance(item) {
    return (
      CRITERION.general * item.loadings.general +
      (CRITERION.facets * item.loadings.facet) / Math.sqrt(FACETS.length)
    );
  }

  /**
   * Everything the page reports about one selection of items.
   * @param {string[]} ids
   * @returns {object}
   */
  function computeMetrics(ids) {
    var items = ids.map(function (id) {
      return ITEM_BY_ID[id];
    });
    var k = items.length;

    // Sum of the off-diagonal correlations, counted once per unordered pair.
    var pairSum = 0;
    var pairCount = 0;
    var i;
    var j;
    for (i = 0; i < k; i += 1) {
      for (j = i + 1; j < k; j += 1) {
        pairSum += itemCorrelation(items[i], items[j]);
        pairCount += 1;
      }
    }

    // Var(T) = sum of the whole correlation matrix; the diagonal is k ones.
    var varTotal = k + 2 * pairSum;
    var meanCorrelation = pairCount > 0 ? pairSum / pairCount : null;
    var alpha =
      k > 1 ? (k / (k - 1)) * (1 - k / varTotal) : null;

    // How many selected items sit in each wording family, so that a family
    // with two or more members can be called out as redundancy.
    var familyCounts = {};
    items.forEach(function (item) {
      if (item.family) {
        familyCounts[item.family] = (familyCounts[item.family] || 0) + 1;
      }
    });

    var duplicatePairs = 0;
    var repeatedFamilies = [];
    Object.keys(familyCounts).forEach(function (family) {
      var n = familyCounts[family];
      if (n > 1) {
        duplicatePairs += (n * (n - 1)) / 2;
        repeatedFamilies.push({ id: family, name: FAMILIES[family], count: n });
      }
    });
    repeatedFamilies.sort(function (a, b) {
      return b.count - a.count;
    });

    // Per-area counts, and how many of those items repeat another's wording.
    var facetCounts = {};
    FACETS.forEach(function (facet) {
      facetCounts[facet.id] = { total: 0, repeated: 0 };
    });
    items.forEach(function (item) {
      var cell = facetCounts[item.facet];
      cell.total += 1;
      if (item.family && familyCounts[item.family] > 1) {
        cell.repeated += 1;
      }
    });

    var breadth = FACETS.filter(function (facet) {
      return facetCounts[facet.id].total > 0;
    }).length;

    // r(T, Y). Var(Y) = 1 because Y is standardised, so the denominator is
    // the standard deviation of the total score alone.
    var outcome = null;
    if (k > 0) {
      var covariance = items.reduce(function (sum, item) {
        return sum + itemOutcomeCovariance(item);
      }, 0);
      outcome = covariance / Math.sqrt(varTotal);
    }

    return {
      ids: ids.slice(),
      k: k,
      alpha: alpha,
      meanCorrelation: meanCorrelation,
      varTotal: varTotal,
      breadth: breadth,
      facetCounts: facetCounts,
      familyCounts: familyCounts,
      duplicatePairs: duplicatePairs,
      repeatedFamilies: repeatedFamilies,
      outcome: outcome
    };
  }

  /**
   * Does this selection satisfy the Round 2 brief?
   * @param {object} metrics
   * @returns {object} { met:boolean, checks:[{label, met}] }
   */
  function roundTwoChecks(metrics) {
    var checks = [
      {
        label: "covers all five content areas",
        detail: metrics.breadth + " of " + ROUND_TWO.requiredFacets,
        met: metrics.breadth === ROUND_TWO.requiredFacets
      },
      {
        label: "no wording used twice",
        detail:
          metrics.duplicatePairs === 0
            ? "none"
            : metrics.duplicatePairs + " near-duplicate pairs",
        met: metrics.duplicatePairs === 0
      },
      {
        label:
          "between " + ROUND_TWO.minItems + " and " + ROUND_TWO.maxItems + " items",
        detail: metrics.k + " selected",
        met: metrics.k >= ROUND_TWO.minItems && metrics.k <= ROUND_TWO.maxItems
      },
      {
        label: "alpha at least " + formatStat(ROUND_TWO.minAlpha),
        detail: metrics.alpha === null ? "not yet" : formatStat(metrics.alpha),
        met: metrics.alpha !== null && metrics.alpha >= ROUND_TWO.minAlpha
      }
    ];

    return {
      met: checks.every(function (check) {
        return check.met;
      }),
      checks: checks
    };
  }

  /* =======================================================================
     3. Small helpers
     ===================================================================== */

  /**
   * Two decimal places by default, or an em dash when there is nothing to
   * report. Challenge 2 passes 3, because the smallest drop in the outcome
   * correlation it can produce is about 0.006 — real, but invisible at two
   * decimal places, where it would read as "0.62 to 0.62 (down)".
   * @param {number|null} value
   * @param {number} [places]
   * @returns {string}
   */
  function formatStat(value, places) {
    return value === null || value === undefined || isNaN(value)
      ? "—"
      : value.toFixed(places === undefined ? 2 : places);
  }

  function plural(n, singular, pluralForm) {
    return n === 1 ? singular : pluralForm || singular + "s";
  }

  /** Create an element with optional class and text. */
  function make(tag, className, text) {
    var node = document.createElement(tag);
    if (className) {
      node.className = className;
    }
    if (text !== undefined) {
      node.textContent = text;
    }
    return node;
  }

  function facetById(id) {
    return FACETS.filter(function (facet) {
      return facet.id === id;
    })[0];
  }

  /* =======================================================================
     4. Wiring
     ===================================================================== */

  var shell = InteractiveShell.attach("#alpha-trap");
  if (!shell) {
    return;
  }

  var root = shell.root;
  var page = document;

  var bank = root.querySelector("[data-item-bank]");
  var readout = root.querySelector("[data-readout]");
  var chart = root.querySelector("[data-chart]");
  var chartTable = root.querySelector("[data-chart-table]");
  var goalText = root.querySelector("[data-goal-text]");
  var meterFill = root.querySelector("[data-meter-fill]");
  var meterTarget = root.querySelector("[data-meter-target]");
  var meterCaption = root.querySelector("[data-meter-caption]");
  var redundancyPanel = root.querySelector("[data-redundancy]");
  var redundancyBody = root.querySelector("[data-redundancy-body]");
  var criterionPanel = root.querySelector("[data-criterion]");
  var criterionBody = root.querySelector("[data-criterion-body]");
  var outcomeCell = root.querySelector("[data-outcome-cell]");
  var advanceButton = root.querySelector('[data-action="advance"]');
  var exampleButton = root.querySelector('[data-action="example"]');
  var clearButton = root.querySelector('[data-action="clear"]');
  var stageTrack = page.querySelector("[data-stage-track]");

  var predictionForm = page.getElementById("prediction-form");
  var predictionError = page.querySelector("[data-prediction-error]");
  var predictionReadback = page.querySelector("[data-prediction-readback]");
  var skipPredictionButton = page.querySelector('[data-action="skip-prediction"]');

  var revealSection = page.getElementById("reveal");
  var revealBody = page.querySelector("[data-reveal-body]");
  var comparisonSection = page.getElementById("comparison");
  var comparisonBody = page.querySelector("[data-comparison-body]");
  var comparisonVerdict = page.querySelector("[data-comparison-verdict]");

  var diagnosisForm = page.getElementById("challenge-diagnosis");
  var diagnosisFeedback = page.querySelector("[data-diagnosis-feedback]");
  var transferForm = page.getElementById("challenge-transfer");
  var transferLocked = page.querySelector("[data-transfer-locked]");
  var transferBody = page.querySelector("[data-transfer-body]");
  var transferError = page.querySelector("[data-transfer-error]");
  var transferFeedback = page.querySelector("[data-transfer-feedback]");

  /* --- State ------------------------------------------------------------
     stage: predict -> round1 -> reveal -> round2 -> complete
     Every other piece of visible state is derived from this object, so
     reset() only has to restore it and re-render. */
  var INITIAL_STATE = {
    stage: "predict",
    selected: [],
    prediction: null,
    roundOne: null,
    roundTwo: null
  };

  var state = null;
  var checkboxes = {};

  /* --- Item bank --------------------------------------------------------
     Built from ITEMS so that an item's text, its content area and its
     psychometric parameters cannot drift apart. */

  function buildBank() {
    FACETS.forEach(function (facet) {
      var group = make("fieldset", "bank__group");
      group.appendChild(make("legend", null, facet.name));

      var list = make("ul", "bank__list");

      ITEMS.filter(function (item) {
        return item.facet === facet.id;
      }).forEach(function (item) {
        var row = make("li");
        var label = make("label", "item");
        var input = document.createElement("input");

        input.type = "checkbox";
        input.value = item.id;
        input.id = "item-" + item.id;
        input.addEventListener("change", onItemToggle);

        label.setAttribute("for", input.id);
        label.appendChild(input);
        label.appendChild(make("span", null, item.text));

        row.appendChild(label);
        list.appendChild(row);
        checkboxes[item.id] = input;
      });

      group.appendChild(list);
      bank.appendChild(group);
    });
  }

  function onItemToggle(event) {
    var id = event.target.value;
    if (event.target.checked) {
      if (state.selected.indexOf(id) === -1) {
        state.selected.push(id);
      }
    } else {
      state.selected = state.selected.filter(function (existing) {
        return existing !== id;
      });
    }
    render();
    announceSelection(id, event.target.checked);
  }

  function announceSelection(id, added) {
    var metrics = computeMetrics(state.selected);
    var parts = [
      (added ? "Added" : "Removed") + " an item.",
      metrics.k + " " + plural(metrics.k, "item") + " selected."
    ];
    if (metrics.alpha !== null) {
      parts.push("Alpha " + formatStat(metrics.alpha) + ".");
      parts.push(
        metrics.breadth + " of " + FACETS.length + " content areas covered."
      );
      if (metrics.duplicatePairs > 0) {
        parts.push(
          metrics.duplicatePairs +
            " near-duplicate " +
            plural(metrics.duplicatePairs, "pair") +
            "."
        );
      }
    }
    shell.announce(parts.join(" "));
  }

  function setSelection(ids) {
    state.selected = ids.slice();
    syncCheckboxes();
    render();
  }

  function syncCheckboxes() {
    ITEMS.forEach(function (item) {
      checkboxes[item.id].checked = state.selected.indexOf(item.id) !== -1;
    });
  }

  function setBankEnabled(enabled) {
    ITEMS.forEach(function (item) {
      checkboxes[item.id].disabled = !enabled;
    });
  }

  /* --- Rendering -------------------------------------------------------- */

  function render() {
    var metrics = computeMetrics(state.selected);
    renderReadout(metrics);
    renderMeter(metrics);
    renderChart(metrics);
    renderRedundancy(metrics);
    renderCriterion(metrics);
    renderGoal(metrics);
    renderStageTrack();
    renderActions(metrics);
  }

  function setMetric(name, value) {
    var cell = readout.querySelector('[data-metric="' + name + '"]');
    if (cell) {
      cell.textContent = value;
    }
  }

  function renderReadout(metrics) {
    setMetric("alpha", formatStat(metrics.alpha));
    setMetric("items", String(metrics.k));
    setMetric("rbar", formatStat(metrics.meanCorrelation));
    setMetric("breadth", metrics.breadth + " of " + FACETS.length);
    setMetric("duplicates", String(metrics.duplicatePairs));
    setMetric("outcome", formatStat(metrics.outcome));
  }

  function renderMeter(metrics) {
    var alpha = metrics.alpha === null ? 0 : Math.max(0, metrics.alpha);
    meterFill.style.width = (alpha * 100).toFixed(1) + "%";

    var target =
      state.stage === "round2" || state.stage === "complete"
        ? ROUND_TWO.minAlpha
        : ROUND_ONE.targetAlpha;
    meterTarget.style.left = (target * 100).toFixed(1) + "%";
    meterCaption.textContent = "target " + formatStat(target);
  }

  /* The chart repeats the table beneath it and is hidden from assistive
     technology, so it may use colour freely — but each bar still carries its
     own number as text, which is what makes it readable in greyscale. */
  function renderChart(metrics) {
    var NS = "http://www.w3.org/2000/svg";
    var ROW_HEIGHT = 34;
    var BAR_HEIGHT = 18;
    var UNIT = 34; // pixels per item; six items is the widest any area gets
    var BAR_X = 128;

    while (chart.firstChild) {
      chart.removeChild(chart.firstChild);
    }

    var defs = document.createElementNS(NS, "defs");
    var pattern = document.createElementNS(NS, "pattern");
    pattern.setAttribute("id", "alpha-trap-hatch");
    pattern.setAttribute("width", "6");
    pattern.setAttribute("height", "6");
    pattern.setAttribute("patternUnits", "userSpaceOnUse");
    pattern.setAttribute("patternTransform", "rotate(45)");
    var stripe = document.createElementNS(NS, "line");
    stripe.setAttribute("x1", "0");
    stripe.setAttribute("y1", "0");
    stripe.setAttribute("x2", "0");
    stripe.setAttribute("y2", "6");
    stripe.setAttribute("class", "chart__hatch");
    pattern.appendChild(stripe);
    defs.appendChild(pattern);
    chart.appendChild(defs);

    FACETS.forEach(function (facet, index) {
      var counts = metrics.facetCounts[facet.id];
      var y = 12 + index * ROW_HEIGHT;

      var label = document.createElementNS(NS, "text");
      label.setAttribute("x", String(BAR_X - 8));
      label.setAttribute("y", String(y + BAR_HEIGHT - 4));
      label.setAttribute("text-anchor", "end");
      label.setAttribute("class", "chart__label");
      label.textContent = facet.short;
      chart.appendChild(label);

      // A hairline baseline so an empty area still reads as an empty bar
      // rather than as a missing row.
      var baseline = document.createElementNS(NS, "line");
      baseline.setAttribute("x1", String(BAR_X));
      baseline.setAttribute("y1", String(y + BAR_HEIGHT));
      baseline.setAttribute("x2", String(BAR_X + 6 * UNIT));
      baseline.setAttribute("y2", String(y + BAR_HEIGHT));
      baseline.setAttribute("class", "chart__baseline");
      chart.appendChild(baseline);

      if (counts.total > 0) {
        var bar = document.createElementNS(NS, "rect");
        bar.setAttribute("x", String(BAR_X));
        bar.setAttribute("y", String(y));
        bar.setAttribute("width", String(counts.total * UNIT));
        bar.setAttribute("height", String(BAR_HEIGHT));
        bar.setAttribute("class", "chart__bar");
        chart.appendChild(bar);

        if (counts.repeated > 0) {
          var repeated = document.createElementNS(NS, "rect");
          repeated.setAttribute("x", String(BAR_X));
          repeated.setAttribute("y", String(y));
          repeated.setAttribute("width", String(counts.repeated * UNIT));
          repeated.setAttribute("height", String(BAR_HEIGHT));
          repeated.setAttribute("class", "chart__bar-repeat");
          chart.appendChild(repeated);
        }
      }

      var count = document.createElementNS(NS, "text");
      count.setAttribute("x", String(BAR_X + counts.total * UNIT + 8));
      count.setAttribute("y", String(y + BAR_HEIGHT - 4));
      count.setAttribute("class", "chart__count");
      count.textContent =
        counts.repeated > 0
          ? counts.total + " (" + counts.repeated + " repeated)"
          : String(counts.total);
      chart.appendChild(count);
    });

    renderChartTable(metrics);
  }

  function renderChartTable(metrics) {
    while (chartTable.firstChild) {
      chartTable.removeChild(chartTable.firstChild);
    }

    FACETS.forEach(function (facet) {
      var counts = metrics.facetCounts[facet.id];
      var row = make("tr");
      var header = make("th", null, facet.name);
      header.setAttribute("scope", "row");
      row.appendChild(header);
      row.appendChild(make("td", null, String(counts.total)));
      row.appendChild(make("td", null, String(counts.repeated)));
      chartTable.appendChild(row);
    });
  }

  function renderRedundancy(metrics) {
    var tone = "neutral";
    var text;

    if (metrics.k === 0) {
      text = "No items selected yet.";
    } else if (metrics.duplicatePairs === 0) {
      tone = "good";
      text =
        "None. No two selected items are paraphrases of each other, so alpha " +
        "is being earned by items that ask different questions.";
    } else {
      tone = metrics.duplicatePairs >= 6 ? "warn" : "caution";
      var families = metrics.repeatedFamilies
        .map(function (family) {
          return family.count + " items about " + family.name;
        })
        .join("; ");
      text =
        (tone === "warn" ? "Heavy. " : "Some. ") +
        metrics.duplicatePairs +
        " near-duplicate " +
        plural(metrics.duplicatePairs, "pair") +
        " (" +
        families +
        "). Repeated wording raises the average inter-item correlation, and " +
        "therefore alpha, without adding anything new to the scale.";
    }

    redundancyPanel.setAttribute("data-tone", tone);
    redundancyBody.textContent = text;
  }

  function renderCriterion(metrics) {
    if (criterionPanel.hidden) {
      return;
    }

    if (metrics.outcome === null) {
      criterionBody.textContent = "Select some items to see this.";
      criterionPanel.setAttribute("data-tone", "neutral");
      return;
    }

    var r = metrics.outcome;
    var tone = r >= 0.55 ? "good" : r >= 0.45 ? "caution" : "warn";
    var strength = r >= 0.55 ? "strong" : r >= 0.45 ? "moderate" : "modest";

    criterionBody.textContent =
      "r = " +
      formatStat(r) +
      " — a " +
      strength +
      " relationship. Alpha is " +
      formatStat(metrics.alpha) +
      ", so the two are telling you different things about this scale.";
    criterionPanel.setAttribute("data-tone", tone);
  }

  function renderGoal(metrics) {
    while (goalText.firstChild) {
      goalText.removeChild(goalText.firstChild);
    }

    if (state.stage === "predict") {
      goalText.textContent =
        "Record your prediction above to unlock the item bank.";
      return;
    }

    if (state.stage === "round1") {
      var reached =
        metrics.alpha !== null && metrics.alpha >= ROUND_ONE.targetAlpha;
      goalText.appendChild(
        document.createTextNode("Round 1 — push alpha to ")
      );
      goalText.appendChild(
        make("strong", null, formatStat(ROUND_ONE.targetAlpha))
      );
      goalText.appendChild(
        document.createTextNode(
          " or above, using any items you like. Currently "
        )
      );
      goalText.appendChild(make("strong", null, formatStat(metrics.alpha)));
      goalText.appendChild(
        document.createTextNode(reached ? " — target reached." : " — not yet.")
      );
      return;
    }

    if (state.stage === "reveal") {
      goalText.textContent =
        "Round 1 is locked. Read what you built below, then start Round 2.";
      return;
    }

    if (state.stage === "round2" || state.stage === "complete") {
      goalText.appendChild(
        document.createTextNode(
          state.stage === "complete"
            ? "Round 2 complete. Keep experimenting if you wish — the requirements were:"
            : "Round 2 — build a scale you would defend:"
        )
      );

      var list = make("ul", "goal__checks");
      roundTwoChecks(metrics).checks.forEach(function (check) {
        var entry = make("li");
        entry.textContent =
          check.label + " — " + check.detail + (check.met ? " (met)" : " (not yet)");
        entry.setAttribute("data-met", check.met ? "yes" : "no");
        list.appendChild(entry);
      });
      goalText.appendChild(list);
    }
  }

  function renderStageTrack() {
    var order = ["predict", "round1", "round2"];
    var currentStep =
      state.stage === "predict"
        ? "predict"
        : state.stage === "round1" || state.stage === "reveal"
        ? "round1"
        : "round2";

    order.forEach(function (step, index) {
      var node = stageTrack.querySelector('[data-stage-step="' + step + '"]');
      if (!node) {
        return;
      }
      var isCurrent = step === currentStep;
      var isDone = order.indexOf(currentStep) > index;

      if (isCurrent) {
        node.setAttribute("aria-current", "step");
      } else {
        node.removeAttribute("aria-current");
      }
      node.setAttribute("data-state", isDone ? "done" : isCurrent ? "current" : "todo");

      // "Completed" is stated in text, not carried by styling alone.
      var marker = node.querySelector(".stage-track__state");
      if (isDone && !marker) {
        marker = make("span", "stage-track__state visually-hidden", " (completed)");
        node.appendChild(marker);
      } else if (!isDone && marker) {
        node.removeChild(marker);
      }
    });
  }

  function renderActions(metrics) {
    var canAdvance = false;
    var label = "Reveal what I built";

    if (state.stage === "round1") {
      label = "Reveal what I built";
      canAdvance =
        metrics.alpha !== null &&
        (metrics.alpha >= ROUND_ONE.targetAlpha ||
          metrics.k >= ROUND_ONE.minItemsToAdvance);
    } else if (state.stage === "reveal") {
      label = "Start Round 2";
      canAdvance = true;
    } else if (state.stage === "round2") {
      label = "Check my scale";
      canAdvance = roundTwoChecks(metrics).met;
    } else if (state.stage === "complete") {
      label = "Round 2 checked";
      canAdvance = false;
    }

    advanceButton.textContent = label;
    advanceButton.disabled = !canAdvance;

    var bankLive = state.stage === "round1" || state.stage === "round2" ||
      state.stage === "complete";
    exampleButton.disabled = !bankLive;
    clearButton.disabled = !bankLive;
  }

  /* --- Stage transitions ------------------------------------------------ */

  function setStage(stage) {
    state.stage = stage;
    setBankEnabled(stage === "round1" || stage === "round2" || stage === "complete");
    render();
  }

  function startRoundOne() {
    setStage("round1");
    shell.announce(
      "Item bank unlocked. Round 1: push alpha to " +
        formatStat(ROUND_ONE.targetAlpha) +
        " or above.",
      { immediate: true }
    );
  }

  function revealRoundOne() {
    state.roundOne = computeMetrics(state.selected);

    outcomeCell.hidden = false;
    criterionPanel.hidden = false;

    buildReveal(state.roundOne);
    revealSection.hidden = false;

    setStage("reveal");

    shell.announce(
      "Round 1 locked. Alpha " +
        formatStat(state.roundOne.alpha) +
        ", covering " +
        state.roundOne.breadth +
        " of " +
        FACETS.length +
        " content areas, correlating " +
        formatStat(state.roundOne.outcome) +
        " with the simulated outcome.",
      { immediate: true }
    );

    // Send the reader to the explanation rather than leaving them to find it.
    page.getElementById("reveal-heading").focus();
  }

  function startRoundTwo() {
    setSelection([]);
    setStage("round2");
    shell.announce(
      "Round 2. Selection cleared. Build a scale that covers all five " +
        "content areas without repeating wording.",
      { immediate: true }
    );
  }

  function completeRoundTwo() {
    state.roundTwo = computeMetrics(state.selected);
    buildComparison(state.roundOne, state.roundTwo);
    comparisonSection.hidden = false;
    unlockTransferChallenge();
    setStage("complete");
    shell.announce(
      "Round 2 checked. Alpha " +
        formatStat(state.roundTwo.alpha) +
        " against Round 1's " +
        formatStat(state.roundOne.alpha) +
        ", but the outcome correlation rises from " +
        formatStat(state.roundOne.outcome) +
        " to " +
        formatStat(state.roundTwo.outcome) +
        ".",
      { immediate: true }
    );
    page.getElementById("comparison-heading").focus();
  }

  /* --- The reveal -------------------------------------------------------
     Feedback is written from what the student actually built, so a student
     who resisted the trap is not told they fell into it. */

  function buildReveal(metrics) {
    while (revealBody.firstChild) {
      revealBody.removeChild(revealBody.firstChild);
    }

    var narrow = metrics.breadth <= 2;
    var clean = metrics.duplicatePairs === 0;
    var lead;

    if (narrow && !clean) {
      lead =
        "You reached alpha " +
        formatStat(metrics.alpha) +
        " — and built a scale that measures " +
        (metrics.breadth === 1 ? "one" : "two") +
        " of the five content areas.";
    } else if (clean && metrics.breadth >= 4) {
      lead =
        "You resisted the shortcut: alpha " +
        formatStat(metrics.alpha) +
        " with no repeated wording and " +
        metrics.breadth +
        " of the five areas covered.";
    } else {
      lead =
        "You reached alpha " +
        formatStat(metrics.alpha) +
        ", with " +
        metrics.duplicatePairs +
        " near-duplicate " +
        plural(metrics.duplicatePairs, "pair") +
        " and " +
        metrics.breadth +
        " of the five content areas covered.";
    }
    revealBody.appendChild(make("p", "reveal__lead", lead));

    var figures = make("ul", "reveal__figures");
    [
      ["Alpha", formatStat(metrics.alpha)],
      ["Items", String(metrics.k)],
      ["Content areas", metrics.breadth + " of " + FACETS.length],
      ["Near-duplicate pairs", String(metrics.duplicatePairs)],
      ["Correlation with outcome", formatStat(metrics.outcome)]
    ].forEach(function (pair) {
      var entry = make("li");
      entry.appendChild(make("span", "reveal__figure-label", pair[0]));
      entry.appendChild(make("span", "reveal__figure-value", pair[1]));
      figures.appendChild(entry);
    });
    revealBody.appendChild(figures);

    // The paraphrases doing the work, quoted back.
    if (metrics.repeatedFamilies.length > 0) {
      var worst = metrics.repeatedFamilies[0];
      revealBody.appendChild(
        make(
          "p",
          null,
          "The " +
            worst.count +
            " items below are all in your scale. They are the same question " +
            "about " +
            worst.name +
            ", asked " +
            worst.count +
            " times. Between them they contribute " +
            (worst.count * (worst.count - 1)) / 2 +
            " of the " +
            String((metrics.k * (metrics.k - 1)) / 2) +
            " correlations that alpha is averaging."
        )
      );
      var quoted = make("ul", "reveal__items");
      metrics.ids
        .filter(function (id) {
          return ITEM_BY_ID[id].family === worst.id;
        })
        .forEach(function (id) {
          quoted.appendChild(make("li", null, "“" + ITEM_BY_ID[id].text + "”"));
        });
      revealBody.appendChild(quoted);
    }

    // What the outcome correlation means, with an explicit counterfactual.
    var balanced = computeMetrics(EXAMPLES.round2);
    revealBody.appendChild(
      make(
        "p",
        null,
        "Your scale correlates " +
          formatStat(metrics.outcome) +
          " with a simulated outcome that depends on the whole construct. " +
          "For comparison, a ten-item scale covering all five areas with no " +
          "repeated wording reaches alpha " +
          formatStat(balanced.alpha) +
          " — lower than " +
          (metrics.alpha >= balanced.alpha ? "yours" : "many published scales") +
          " — but correlates " +
          formatStat(balanced.outcome) +
          " with the same outcome. The lower-alpha scale is the better measure."
      )
    );

    revealBody.appendChild(
      make(
        "p",
        null,
        "Alpha rises with the number of items and with their average " +
          "correlation. Paraphrasing an item raises both at once, so it is " +
          "the cheapest possible way to buy a high alpha — and it buys " +
          "nothing else. The extra shared variance is specific to the " +
          "wording, and the outcome does not care about wording."
      )
    );

    if (state.prediction) {
      revealBody.appendChild(buildPredictionComparison(metrics));
    }
  }

  function buildPredictionComparison(metrics) {
    var predictedBreadth = state.prediction.breadth;
    var actualBand =
      metrics.breadth <= 2 ? "one-or-two" : metrics.breadth === 3 ? "three" : "four-or-five";
    var breadthRight = predictedBreadth === actualBand;

    var predictedOutcome = state.prediction.outcome;
    var actualOutcomeBand =
      metrics.outcome < 0.45 ? "weak" : metrics.outcome < 0.55 ? "moderate" : "strong";
    var outcomeRight =
      predictedOutcome === actualOutcomeBand || predictedOutcome === "unknown";

    var text;
    if (predictedOutcome === "unknown") {
      text =
        "You predicted that alpha on its own would not tell you what " +
          "the scale correlates with. The observed correlation was " +
        formatStat(metrics.outcome) +
        ", and nothing about alpha would have let you anticipate it.";
    } else if (breadthRight && outcomeRight) {
      text =
        "Both of your predictions were borne out: " +
        metrics.breadth +
        " of five areas covered, and a correlation of " +
        formatStat(metrics.outcome) +
        " with the outcome.";
    } else {
      text =
        "Compare that with your prediction. You expected the scale to cover " +
        describeBreadthPrediction(predictedBreadth) +
        " and to correlate " +
        describeOutcomePrediction(predictedOutcome) +
        " with the outcome. It covered " +
        metrics.breadth +
        " of five, and correlated " +
        formatStat(metrics.outcome) +
        ".";
    }

    var node = make("p", "prediction__readback", text);
    return node;
  }

  function describeBreadthPrediction(value) {
    return value === "one-or-two"
      ? "one or two areas"
      : value === "three"
      ? "about three areas"
      : "four or five areas";
  }

  function describeOutcomePrediction(value) {
    return value === "weak"
      ? "weakly, around 0.2,"
      : value === "moderate"
      ? "moderately, around 0.4,"
      : "strongly, around 0.6,";
  }

  /* --- The comparison table --------------------------------------------- */

  function buildComparison(one, two) {
    while (comparisonBody.firstChild) {
      comparisonBody.removeChild(comparisonBody.firstChild);
    }

    [
      ["Items", String(one.k), String(two.k)],
      ["Cronbach's alpha", formatStat(one.alpha), formatStat(two.alpha)],
      [
        "Mean inter-item correlation",
        formatStat(one.meanCorrelation),
        formatStat(two.meanCorrelation)
      ],
      [
        "Content areas covered",
        one.breadth + " of " + FACETS.length,
        two.breadth + " of " + FACETS.length
      ],
      [
        "Near-duplicate pairs",
        String(one.duplicatePairs),
        String(two.duplicatePairs)
      ],
      [
        "Correlation with the simulated outcome",
        formatStat(one.outcome),
        formatStat(two.outcome)
      ]
    ].forEach(function (row) {
      var tr = make("tr");
      var th = make("th", null, row[0]);
      th.setAttribute("scope", "row");
      tr.appendChild(th);
      tr.appendChild(make("td", null, row[1]));
      tr.appendChild(make("td", null, row[2]));
      comparisonBody.appendChild(tr);
    });

    var alphaFell = two.alpha < one.alpha;
    var outcomeRose = two.outcome > one.outcome;

    comparisonVerdict.textContent = alphaFell && outcomeRose
      ? "Your Round 2 scale has the lower alpha and the higher correlation " +
        "with the outcome. If alpha were a measure of quality, that " +
        "combination could not happen."
      : outcomeRose
      ? "Your Round 2 scale correlates more strongly with the outcome. Alpha " +
        "did not have to fall for that to be true — the point is that the two " +
        "move independently."
      : "Compare the two columns row by row, and note which differences alpha " +
        "was sensitive to and which it was blind to.";
  }

  /* --- Challenge 1: diagnosis ------------------------------------------- */

  var DIAGNOSIS_FEEDBACK = {
    a: {
      tone: "caution",
      verdict: "Not quite.",
      text:
        "Scale A has the highest alpha in the table and is the weakest " +
        "measure in it. Seven of its twelve items are near-identical, which " +
        "is what produces the 0.94, and it leaves three of the five content " +
        "areas unmeasured. A total score from it is a precise measurement of " +
        "a fraction of the construct, reported as though it covered all of it."
    },
    b: {
      tone: "good",
      verdict: "Yes.",
      text:
        "Scale B is the only one that covers the construct without " +
          "buying its alpha through repetition. 0.79 clears the .70 " +
          "conventionally asked for, and it is being earned by ten items " +
          "that ask genuinely different questions."
    },
    c: {
      tone: "caution",
      verdict: "Not quite.",
      text:
        "Scale C covers the ground, and breadth matters — but 0.51 means " +
        "roughly half the variance in its total score is measurement error. " +
        "That is exactly what alpha is good at detecting. Low alpha is a " +
        "warning worth heeding; high alpha is not the reassurance it is " +
        "usually taken for."
    }
  };

  function checkDiagnosis(event) {
    event.preventDefault();
    var chosen = diagnosisForm.querySelector('input[name="diagnosis"]:checked');

    if (!chosen) {
      showFeedback(diagnosisFeedback, "caution", "Choose one first.", "");
      return;
    }

    var feedback = DIAGNOSIS_FEEDBACK[chosen.value];
    showFeedback(diagnosisFeedback, feedback.tone, feedback.verdict, feedback.text);
    shell.announce("Challenge 1 answered. " + feedback.verdict, {
      immediate: true
    });
  }

  function showFeedback(container, tone, verdict, text) {
    while (container.firstChild) {
      container.removeChild(container.firstChild);
    }
    container.setAttribute("data-tone", tone);
    var paragraph = make("p");
    paragraph.appendChild(make("strong", "feedback__verdict", verdict));
    if (text) {
      paragraph.appendChild(document.createTextNode(" " + text));
    }
    container.appendChild(paragraph);
    container.hidden = false;
  }

  /* --- Challenge 2: transfer -------------------------------------------- */

  function unlockTransferChallenge() {
    transferLocked.hidden = true;
    transferBody.hidden = false;
  }

  /**
   * The deadline paraphrases not already in the student's Round 2 scale.
   * @returns {string[]}
   */
  function transferAdditions() {
    return ITEMS.filter(function (item) {
      return (
        item.family === "deadline" && state.roundTwo.ids.indexOf(item.id) === -1
      );
    })
      .slice(0, 4)
      .map(function (item) {
        return item.id;
      });
  }

  function applyTransfer(event) {
    event.preventDefault();

    var alphaGuess = transferForm.querySelector(
      'input[name="transfer-alpha"]:checked'
    );
    var outcomeGuess = transferForm.querySelector(
      'input[name="transfer-outcome"]:checked'
    );

    if (!alphaGuess || !outcomeGuess) {
      transferError.textContent =
        "Answer both parts before applying the change.";
      transferError.hidden = false;
      return;
    }
    transferError.hidden = true;

    var before = state.roundTwo;
    var after = computeMetrics(before.ids.concat(transferAdditions()));

    var alphaDirection = direction(before.alpha, after.alpha);
    var outcomeDirection = direction(before.outcome, after.outcome);

    // Show the enlarged scale in the builder so the change is visible, not
    // merely asserted. The Round 2 snapshot behind the comparison table is
    // left untouched.
    setSelection(after.ids);

    var gotAlpha = alphaGuess.value === alphaDirection;
    var gotOutcome = outcomeGuess.value === outcomeDirection;
    var tone = gotAlpha && gotOutcome ? "good" : "caution";
    var verdict =
      gotAlpha && gotOutcome
        ? "Both right."
        : gotAlpha || gotOutcome
        ? "Half right."
        : "Not what happened.";

    showFeedback(
      transferFeedback,
      tone,
      verdict,
      "Alpha went from " +
        formatStat(before.alpha, 3) +
        " to " +
        formatStat(after.alpha, 3) +
        " (" +
        alphaDirection +
        "), while the correlation with the outcome went from " +
        formatStat(before.outcome, 3) +
        " to " +
        formatStat(after.outcome, 3) +
        " (" +
        outcomeDirection +
        "). Four items were added and the scale got worse at the job it " +
        "exists to do, while every conventional reliability statistic " +
        "improved. A reviewer who asks only for a higher alpha is asking for " +
        "this. The builder above now shows the enlarged scale; the comparison " +
        "table still shows your Round 2 scale as you submitted it."
    );

    shell.announce(
      "Applied. Alpha " +
        alphaDirection +
        " to " +
        formatStat(after.alpha) +
        "; outcome correlation " +
        outcomeDirection +
        " to " +
        formatStat(after.outcome) +
        ".",
      { immediate: true }
    );
  }

  /** Direction of travel, with a dead band so trivial moves read as "same". */
  function direction(before, after) {
    var change = after - before;
    if (Math.abs(change) < 0.005) {
      return "same";
    }
    return change > 0 ? "up" : "down";
  }

  /* --- Prediction gate --------------------------------------------------- */

  function recordPrediction(event) {
    event.preventDefault();

    var breadth = predictionForm.querySelector(
      'input[name="predict-breadth"]:checked'
    );
    var outcome = predictionForm.querySelector(
      'input[name="predict-outcome"]:checked'
    );

    if (!breadth || !outcome) {
      predictionError.textContent =
        "Answer both questions before you begin. Committing to an answer " +
        "first is what makes the result worth seeing.";
      predictionError.hidden = false;
      return;
    }

    predictionError.hidden = true;
    state.prediction = { breadth: breadth.value, outcome: outcome.value };

    predictionReadback.textContent =
      "Recorded: you expect the scale to cover " +
      describeBreadthPrediction(breadth.value) +
      ", and " +
      (outcome.value === "unknown"
        ? "you do not expect alpha to tell you what it correlates with."
        : "to correlate " +
          describeOutcomePrediction(outcome.value).replace(/,$/, "") +
          " with the outcome.") +
      " You will be reminded of this after Round 1.";
    predictionReadback.hidden = false;

    lockPredictionForm();
    startRoundOne();
    root.scrollIntoView({ block: "start" });
    root.querySelector("input[type=checkbox]").focus();
  }

  function skipPrediction() {
    predictionError.hidden = true;
    state.prediction = null;
    predictionReadback.textContent =
      "Prediction skipped — demonstration mode.";
    predictionReadback.hidden = false;
    lockPredictionForm();
    startRoundOne();
  }

  function lockPredictionForm() {
    Array.prototype.forEach.call(
      predictionForm.querySelectorAll("input, button"),
      function (control) {
        control.disabled = true;
      }
    );
  }

  function unlockPredictionForm() {
    Array.prototype.forEach.call(
      predictionForm.querySelectorAll("input, button"),
      function (control) {
        control.disabled = false;
      }
    );
    predictionForm.reset();
    predictionReadback.hidden = true;
    predictionReadback.textContent = "";
    predictionError.hidden = true;
  }

  /* --- Buttons ----------------------------------------------------------- */

  advanceButton.addEventListener("click", function () {
    if (state.stage === "round1") {
      revealRoundOne();
    } else if (state.stage === "reveal") {
      startRoundTwo();
    } else if (state.stage === "round2") {
      completeRoundTwo();
    }
  });

  exampleButton.addEventListener("click", function () {
    if (state.stage === "round1") {
      setSelection(EXAMPLES.round1);
      shell.announce(
        "Worked example loaded: five items, all paraphrases of one another " +
          "about meeting deadlines. Alpha " +
          formatStat(computeMetrics(EXAMPLES.round1).alpha) +
          " from a scale covering one of five content areas.",
        { immediate: true }
      );
    } else {
      setSelection(EXAMPLES.round2);
      shell.announce(
        "Worked example loaded: ten items covering all five content areas " +
          "with no repeated wording. Alpha " +
          formatStat(computeMetrics(EXAMPLES.round2).alpha) +
          ".",
        { immediate: true }
      );
    }
  });

  clearButton.addEventListener("click", function () {
    setSelection([]);
    shell.announce("Selection cleared.", { immediate: true });
  });

  predictionForm.addEventListener("submit", recordPrediction);
  skipPredictionButton.addEventListener("click", skipPrediction);
  diagnosisForm.addEventListener("submit", checkDiagnosis);
  transferForm.addEventListener("submit", applyTransfer);

  /* --- Reset ------------------------------------------------------------- */

  shell.onReset(function () {
    state = JSON.parse(JSON.stringify(INITIAL_STATE));

    syncCheckboxes();
    unlockPredictionForm();

    revealSection.hidden = true;
    comparisonSection.hidden = true;
    criterionPanel.hidden = true;
    outcomeCell.hidden = true;

    transferLocked.hidden = false;
    transferBody.hidden = true;
    transferForm.reset();
    transferFeedback.hidden = true;
    transferError.hidden = true;

    diagnosisForm.reset();
    diagnosisFeedback.hidden = true;

    setStage("predict");
  });

  /* --- Start-up ---------------------------------------------------------- */

  buildBank();
  shell.reset({ silent: true });
  shell.announce(
    "Ready. Record a prediction above to unlock the item bank.",
    { immediate: true }
  );
})();
