/* =========================================================================
   Emotional-Intelligence Claims Laboratory
   -------------------------------------------------------------------------
   Six fictional measures, one correlation matrix, and a set of marketing
   claims that students judge against it. Four of the measures carry the
   emotional-intelligence label or are the outcome it is sold on; two are the
   ordinary comparison measures any claim of added value has to beat.

   THE EDUCATIONAL MODEL
   ---------------------
   Every measure is written as a weighted sum of independent standard normal
   sources, scaled so the measure itself has unit variance:

       z(measure) = P·dispositional + A·emotion ability + G·general cognitive
                    + Q·questionnaire method + T·testing method + unique

   Because the sources are independent, the model-implied correlation between
   two measures is just the sum of the products of their shared coefficients:

       r(x, y) = Px·Py + Ax·Ay + Gx·Gy + Qx·Qy + Tx·Ty

   The two method coefficients are the reason two questionnaires correlate a
   little beyond what they have in common in content, and the reason two
   timed tests do. They are sliders because "it is all method variance" is a
   claim students should be able to test rather than assert: turning the
   questionnaire method effect to zero still leaves the self-report scale
   correlating strongly with the personality questionnaire, because that
   overlap is dispositional content, not shared format.

   THE ORGANISING THREAD
   ---------------------
   Self-report EI overlaps a personality questionnaire. Ability EI overlaps a
   reasoning test. Therefore the question worth asking is whether either adds
   anything beyond those. The activity is that sentence, in two steps.

   Step 1 shows the two overlaps as two bars, with a third bar for how little
   the two EI measures agree with each other - the contrast that makes the
   question bite. One control: the mix slider, which asks what the evidence
   would look like if the self-report label were honest. The full 6x6 matrix is
   the evidence behind the bars and sits in a disclosure; the two method sliders
   and their presets sit in another.

   Step 2 asks the question the overlaps raise: does either EI measure predict
   observed effectiveness once a personality questionnaire and a reasoning test
   are already in the model? One radio, one table, one sentence.

   THE ONE SLIDER THAT MATTERS MOST
   --------------------------------
   The self-report scale's content is a fixed amount of common variance split
   between two sources by one angle:

       P = 0.72·cos(theta),  A = 0.72·sin(theta),  theta = mix · 90 degrees

   At mix = 0 the scale is a personality questionnaire with a different name.
   At mix = 1 it is a genuine indicator of emotion ability, and correlates
   with the performance tasks accordingly. The total amount of construct
   variance never changes, so students cannot make the scale better simply by
   sliding — only differently pointed. That is the whole argument of the tool
   in one control.

   INCREMENTAL VALIDITY
   --------------------
   Regression is run properly on the model-implied correlation matrix:
   standardised weights come from solving R·b = r by Gaussian elimination and
   R-squared is b·r. The baseline is deliberately the pair a sceptical
   reviewer would demand — a broad personality questionnaire and a reasoning
   test — because "correlates with the outcome" and "adds anything you did
   not already have" are different claims.

   WHAT THIS IS NOT
   ----------------
   No published emotional-intelligence measure is reproduced, quoted,
   paraphrased or scored. The six measures are fictional descriptions of
   method types, the correlations are generated by the model above, and no
   number here is an estimate of any real quantity. The tool takes no view on
   whether emotional intelligence exists; it is about what a correlation
   matrix can and cannot license someone to advertise.

   No data leave the browser. There is no storage and no network request.
   ========================================================================= */

(function () {
  "use strict";

  /* Total common content variance available to the self-report scale. Fixed,
     so the mix slider redirects the scale rather than improving it. */
  var CONTENT = 0.72;

  /* The weakest correlation among the three labelled measures at which they
     are treated as converging on one construct. Used by the live verdict and
     by the fourth claim, so the two can never contradict each other. Note
     that the recognition task's own content loading caps this at about .43,
     which is why the threshold is not higher. */
  var CONVERGENT = 0.40;

  var MEASURES = [
    {
      id: "sr",
      name: "Emotional-tendencies questionnaire",
      short: "Self-report",
      method: "questionnaire",
      methodLabel: "self-report questionnaire",
      family: "ei",
      blurb: "Twenty statements about how you usually handle feelings, answered about yourself."
    },
    {
      id: "mp",
      name: "Emotion-management task",
      short: "Emotion task",
      method: "test",
      methodLabel: "timed test with scored answers",
      family: "ei",
      blurb: "Written scenarios with responses scored against an expert consensus key."
    },
    {
      id: "er",
      name: "Emotion-recognition accuracy",
      short: "Recognition",
      method: "test",
      methodLabel: "timed test with scored answers",
      family: "ei",
      blurb: "Accuracy at labelling briefly presented expressions and voice clips."
    },
    {
      id: "se",
      name: "Observed social effectiveness",
      short: "Effectiveness",
      method: "ratings",
      methodLabel: "ratings by other people",
      family: "outcome",
      blurb: "Averaged ratings from three colleagues who worked with the person for a term."
    },
    {
      id: "pq",
      name: "Broad personality questionnaire",
      short: "Personality",
      method: "questionnaire",
      methodLabel: "self-report questionnaire",
      family: "comparison",
      blurb: "An ordinary agreeableness and emotional-stability composite."
    },
    {
      id: "rt",
      name: "Verbal reasoning test",
      short: "Reasoning",
      method: "test",
      methodLabel: "timed test with scored answers",
      family: "comparison",
      blurb: "A conventional timed reasoning test, included as the comparison anybody would demand."
    }
  ];

  /* One order, shipped rather than offered. Grouping by method puts the two
     relationships the activity is about next to each other: the self-report EI
     scale beside the personality questionnaire, and the emotion task beside the
     reasoning test. */
  var ORDER = ["sr", "pq", "mp", "er", "rt", "se"];

  /* The whole argument, as three rows. The first two are the overlaps that
     make the third one matter; the third is the contrast, and it is marked as
     such so nobody reads it as a third overlap. */
  var OVERLAPS = [
    { a: "sr", b: "pq", kind: "overlap",
      label: "Self-report EI overlaps a personality questionnaire" },
    { a: "mp", b: "rt", kind: "overlap",
      label: "Ability EI overlaps a reasoning test" },
    { a: "sr", b: "mp", kind: "contrast",
      label: "The two EI measures overlap each other" }
  ];

  /* The two cells the argument turns on, marked in the full matrix for anyone
     who opens it. */
  var KEY_PAIRS = [
    { a: "sr", b: "pq" },
    { a: "mp", b: "rt" }
  ];

  var BASELINE = ["pq", "rt"];

  var PRESETS = {
    study: {
      name: "The study as collected",
      mix: 0.16, questionnaireMethod: 0.30, testMethod: 0.25,
      note:
        "The pattern the laboratory starts from. The self-report scale sits " +
        "close to the personality questionnaire and a long way from the two " +
        "performance tasks."
    },
    construct: {
      name: "If the label were true",
      mix: 1, questionnaireMethod: 0.12, testMethod: 0.25,
      note:
        "What the evidence would look like if the questionnaire really did " +
        "track the same ability the tasks do. Watch the top row change sides."
    },
    method: {
      name: "Method effects turned up",
      mix: 0.16, questionnaireMethod: 0.45, testMethod: 0.45,
      note:
        "Everything sharing a format correlates more. This inflates " +
          "correlations within a method and leaves the ones across " +
          "methods exactly where they were."
    },
    nomethod: {
      name: "Method effects removed",
      mix: 0.16, questionnaireMethod: 0, testMethod: 0,
      note:
        "The awkward result survives: with no shared format at all, the " +
        "self-report scale still overlaps the personality questionnaire " +
        "heavily. That overlap is content, not format."
    }
  };


  /* =======================================================================
     Seeded randomness — a documented seed keeps the scatterplot identical
     for every student and every projector.
     ===================================================================== */

  function clamp(v, lo, hi) { return Math.max(lo, Math.min(hi, v)); }

  /** Coefficient vector for every measure, given the three sliders. */
  function coefficients(state) {
    var theta = state.mix * Math.PI / 2;
    var q = state.questionnaireMethod;
    var t = state.testMethod;

    return {
      sr: { P: CONTENT * Math.cos(theta), A: CONTENT * Math.sin(theta), G: 0.05, Q: q, T: 0 },
      pq: { P: 0.75, A: 0.08, G: 0.05, Q: q, T: 0 },
      mp: { P: 0, A: 0.62, G: 0.38, Q: 0, T: t },
      er: { P: 0, A: 0.58, G: 0.22, Q: 0, T: t },
      rt: { P: 0, A: 0, G: 0.80, Q: 0, T: t },
      se: { P: 0.42, A: 0.34, G: 0.14, Q: 0, T: 0 }
    };
  }

  function communality(c) { return c.P * c.P + c.A * c.A + c.G * c.G + c.Q * c.Q + c.T * c.T; }

  function correlate(a, b) {
    return a.P * b.P + a.A * b.A + a.G * b.G + a.Q * b.Q + a.T * b.T;
  }

  /** Model-implied correlation between two measure ids. */
  function r(coef, x, y) {
    if (x === y) { return 1; }
    return correlate(coef[x], coef[y]);
  }

  /* --- Regression on the correlation matrix ------------------------------ */

  /** Solve A·x = b for small dense A. Returns null if A is singular. */
  function solve(A, b) {
    var n = b.length;
    var m = A.map(function (row, i) { return row.slice().concat([b[i]]); });

    for (var col = 0; col < n; col += 1) {
      var pivot = col;
      for (var row = col + 1; row < n; row += 1) {
        if (Math.abs(m[row][col]) > Math.abs(m[pivot][col])) { pivot = row; }
      }
      if (Math.abs(m[pivot][col]) < 1e-10) { return null; }
      var swap = m[col]; m[col] = m[pivot]; m[pivot] = swap;

      for (var below = col + 1; below < n; below += 1) {
        var factor = m[below][col] / m[col][col];
        for (var k = col; k <= n; k += 1) { m[below][k] -= factor * m[col][k]; }
      }
    }

    var x = new Array(n);
    for (var i = n - 1; i >= 0; i -= 1) {
      var sum = m[i][n];
      for (var j = i + 1; j < n; j += 1) { sum -= m[i][j] * x[j]; }
      x[i] = sum / m[i][i];
    }
    return x;
  }

  /** Variance in `outcome` accounted for by `predictors`, from the matrix. */
  function rSquared(coef, predictors, outcome) {
    if (!predictors.length) { return 0; }
    var R = predictors.map(function (a) {
      return predictors.map(function (b) { return r(coef, a, b); });
    });
    var rv = predictors.map(function (a) { return r(coef, a, outcome); });
    var b = solve(R, rv);
    if (!b) { return 0; }
    var total = 0;
    for (var i = 0; i < b.length; i += 1) { total += b[i] * rv[i]; }
    return clamp(total, 0, 1);
  }

  /* =======================================================================
     Formatting helpers
     ===================================================================== */

  function fmt(v) {
    var s = (Math.abs(v) < 0.005 ? 0 : v).toFixed(2);
    return s.charAt(0) === "0" ? s.slice(1) : (s.slice(0, 2) === "-0" ? "-" + s.slice(2) : s);
  }

  function pct(v) { return Math.round(v * 100) + "%"; }

  function band(value) {
    var a = Math.abs(value);
    if (a < 0.10) { return "near zero"; }
    if (a < 0.30) { return "small"; }
    if (a < 0.50) { return "moderate"; }
    return "large";
  }

  function measureById(id) {
    for (var i = 0; i < MEASURES.length; i += 1) {
      if (MEASURES[i].id === id) { return MEASURES[i]; }
    }
    return null;
  }

  function nameOf(id) { return measureById(id).name; }
  function shortOf(id) { return measureById(id).short; }

  function listNames(ids) {
    var names = ids.map(nameOf).map(function (n) { return n.toLowerCase(); });
    if (names.length === 1) { return names[0]; }
    return names.slice(0, -1).join(", ") + " and " + names[names.length - 1];
  }

  function make(tag, className, text) {
    var el = document.createElement(tag);
    if (className) { el.className = className; }
    if (text !== undefined && text !== null) { el.textContent = text; }
    return el;
  }

  function clear(node) { while (node.firstChild) { node.removeChild(node.firstChild); } }

  /* =======================================================================
     Wiring
     ===================================================================== */

  var shell = InteractiveShell.attach("#ei-lab");
  if (!shell) { return; }

  var page = document;
  var $ = function (s, scope) { return (scope || page).querySelector(s); };
  var $$ = function (s, scope) {
    return Array.prototype.slice.call((scope || page).querySelectorAll(s));
  };

  var matrixHead = $("[data-matrix-head]");
  var matrixBody = $("[data-matrix-body]");
  var matrixNote = $("[data-matrix-note]");
  var overlaps = $("[data-overlaps]");
  var overlapNote = $("[data-overlap-note]");
  var incrementalBody = $("[data-incremental-body]");
  var incrementalNote = $("[data-incremental-note]");
  var interpretation = $("[data-interpretation]");
  var presetNote = $("[data-preset-note]");

  var openingForm = $("#opening-form");
  var openingError = $("[data-opening-error]");
  var openingFeedback = $("[data-opening-feedback]");
  var mainSection = $("#lab-section");

  var claimsForm = $("#claims-form");
  var claimsFeedback = $("[data-claims-feedback]");

  var DEFAULT_NOTE =
    "Four ways of setting the study up. Each one is a different answer to " +
    "\"what are these four measures measuring?\"";

  /* Two questions, asked one at a time.
     Everything below was originally on screen at once: three sliders, a
     matrix, a scatterplot, an incremental-validity table and two orderings.
     The learner could not tell which output answered which control. The two
     steps ask one question each, and each shows only the controls and the
     result that belong to it. Nothing is removed — the model is shared, so
     what is set in step 1 is what step 2 analyses. */
  var STEPS = {
    "1": {
      hint:
        "Each bar is how far one measure overlaps another.",
      announce: "Step 1. What these measures overlap with."
    },
    "2": {
      hint:
        "The study is set as you left it in step 1. Now the question those " +
        "overlaps raise: does either measure predict anything the ordinary " +
        "ones did not?",
      announce: "Step 2. Whether either measure adds anything."
    }
  };

  var INITIAL = {
    step: "1",
    mix: 0.16,
    questionnaireMethod: 0.30,
    testMethod: 0.25,
    additions: ["sr"],
    stage: "predict"
  };

  var state = null;
  var rangeSyncs = [];

  function bindRange(input, options) {
    var settings = options || {};
    var output = page.querySelector('output[for="' + input.id + '"]');
    function sync() {
      var value = Number(input.value);
      if (output) {
        output.textContent = settings.format ? settings.format(value) : String(value);
      }
      input.setAttribute("aria-valuetext",
        (settings.describe || settings.format || String)(value));
      if (settings.onInput) { settings.onInput(value); }
    }
    input.addEventListener("input", sync);
    rangeSyncs.push(sync);
    return sync;
  }

  function syncRanges() { rangeSyncs.forEach(function (s) { s(); }); }

  function mixWords(v) {
    if (v <= 12) { return "almost entirely general dispositions — a personality questionnaire under another name"; }
    if (v <= 35) { return "mostly general dispositions, with a little emotion ability"; }
    if (v <= 65) { return "an even split between general dispositions and emotion ability"; }
    if (v < 95) { return "mostly emotion ability, with some general dispositions"; }
    return "almost entirely emotion ability — the questionnaire the marketing describes";
  }

  bindRange($("#mix-range"), {
    format: function (v) { return v + "% ability"; },
    describe: function (v) {
      return "What the self-report scale reflects: " + mixWords(v) + ".";
    },
    onInput: function (v) { state.mix = v / 100; render(); }
  });

  bindRange($("#questionnaire-range"), {
    format: function (v) { return fmt(v / 100); },
    describe: function (v) {
      return "Shared questionnaire method effect " + fmt(v / 100) +
        ", the amount two self-report scales have in common purely because " +
        "both are self-report.";
    },
    onInput: function (v) { state.questionnaireMethod = v / 100; render(); }
  });

  bindRange($("#test-range"), {
    format: function (v) { return fmt(v / 100); },
    describe: function (v) {
      return "Shared testing method effect " + fmt(v / 100) +
        ", the amount two timed scored tests have in common purely because " +
        "both are timed scored tests.";
    },
    onInput: function (v) { state.testMethod = v / 100; render(); }
  });


  $$('input[name="addition"]').forEach(function (input) {
    input.addEventListener("change", function () {
      /* One radio, one choice; "sr,mp" is the both-measures option. */
      state.additions = this.value.split(",");
      render();
    });
  });

  $$('input[name="lab-step"]').forEach(function (input) {
    input.addEventListener("change", function () {
      if (!input.checked) { return; }
      state.step = input.value;
      applyStep();
      shell.announce(STEPS[state.step].announce + " " + STEPS[state.step].hint,
        { immediate: true });
    });
  });

  function applyStep() {
    $$("[data-step]").forEach(function (el) {
      el.hidden = el.getAttribute("data-step") !== state.step;
    });
    $("[data-step-hint]").hidden = false;
    $("[data-step-hint]").textContent = STEPS[state.step].hint;
  }

  $$("[data-preset]").forEach(function (button) {
    button.addEventListener("click", function () {
      var preset = PRESETS[button.getAttribute("data-preset")];
      state.mix = preset.mix;
      state.questionnaireMethod = preset.questionnaireMethod;
      state.testMethod = preset.testMethod;
      presetNote.textContent = preset.note;
      applyState();
      render();
      shell.announce(preset.name + " loaded. " + preset.note, { immediate: true });
    });
  });

  function applyState() {
    $('input[name="lab-step"][value="' + state.step + '"]').checked = true;
    applyStep();
    $("#mix-range").value = String(Math.round(state.mix * 100));
    $("#questionnaire-range").value = String(Math.round(state.questionnaireMethod * 100));
    $("#test-range").value = String(Math.round(state.testMethod * 100));
    var addition = $('input[name="addition"][value="' + state.additions.join(",") + '"]');
    if (addition) { addition.checked = true; }
    syncRanges();
  }

  /* =======================================================================
     Rendering
     ===================================================================== */

  function render() {
    if (mainSection.hidden) { return; }
    var coef = coefficients(state);
    renderMatrix(coef);
    renderOverlaps(coef);
    renderIncremental(coef);
    renderInterpretation(coef);
  }

  function isKeyPair(x, y) {
    return KEY_PAIRS.some(function (pair) {
      return (pair.a === x && pair.b === y) || (pair.a === y && pair.b === x);
    });
  }

  function renderMatrix(coef) {
    var order = ORDER;

    clear(matrixHead);
    var head = make("tr");
    var corner = make("th", null, "Measure");
    corner.setAttribute("scope", "col");
    head.appendChild(corner);
    order.forEach(function (id) {
      var th = make("th", null, shortOf(id));
      th.setAttribute("scope", "col");
      head.appendChild(th);
    });
    matrixHead.appendChild(head);

    clear(matrixBody);
    order.forEach(function (rowId) {
      var row = make("tr");
      var th = make("th", null, nameOf(rowId) + " (" + measureById(rowId).method + ")");
      th.setAttribute("scope", "row");
      th.setAttribute("data-family", measureById(rowId).family);
      row.appendChild(th);

      order.forEach(function (colId) {
        var value = r(coef, rowId, colId);
        var cell = make("td", null, rowId === colId ? "—" : fmt(value));
        if (rowId !== colId) {
          cell.setAttribute("data-strength",
            value >= 0.5 ? "high" : value >= 0.25 ? "mid" : "low");
          if (measureById(rowId).method === measureById(colId).method) {
            cell.setAttribute("data-samemethod", "yes");
          }
          if (isKeyPair(rowId, colId)) {
            cell.setAttribute("data-emphasis", "yes");
            /* Named in words as well as tinted, so the emphasis never depends
               on colour alone. */
            cell.appendChild(make("span", "visually-hidden",
              " (one of the two relationships this activity is about)"));
          }
        }
        row.appendChild(cell);
      });
      matrixBody.appendChild(row);
    });

    matrixNote.textContent =
      "Rows are grouped by how each measure was collected. The two marked cells " +
      "are the ones the bars above are drawn from.";
  }

  /* Three rows: two overlaps and the contrast between them. The bar is
     decorative and hidden from assistive technology - the label and the figure
     beside it say the same thing in text, so this needs no separate
     alternative. */
  function renderOverlaps(coef) {
    clear(overlaps);
    OVERLAPS.forEach(function (row) {
      var value = r(coef, row.a, row.b);
      var item = make("li", "overlap");
      item.setAttribute("data-kind", row.kind);

      item.appendChild(make("span", "overlap__label", row.label));

      var track = make("span", "overlap__track");
      track.setAttribute("aria-hidden", "true");
      var bar = make("span", "overlap__bar");
      bar.style.width = Math.round(Math.max(0, Math.min(1, value)) * 100) + "%";
      track.appendChild(bar);
      item.appendChild(track);

      item.appendChild(make("span", "overlap__value",
        fmt(value) + " (" + band(value) + ")"));
      overlaps.appendChild(item);
    });

    var srPq = r(coef, "sr", "pq");
    var srMp = r(coef, "sr", "mp");
    overlapNote.textContent = srMp >= srPq
      ? "The two measures sold as emotional intelligence now agree with each " +
        "other more than the self-report scale agrees with personality. That " +
        "is what the label would need in order to be doing honest work."
      : "Each measure agrees more with an ordinary measure than the two of " +
        "them agree with each other.";
  }

  function renderIncremental(coef) {
    var baseR2 = rSquared(coef, BASELINE, "se");
    var full = BASELINE.concat(state.additions);
    var fullR2 = rSquared(coef, full, "se");
    var change = fullR2 - baseR2;

    clear(incrementalBody);
    [
      ["Personality questionnaire and reasoning test alone", pct(baseR2)],
      ["Adding " + listNames(state.additions), pct(fullR2)],
      ["Change", (change >= 0 ? "+" : "") + pct(change)]
    ].forEach(function (pair, index) {
      var row = make("tr");
      var th = make("th", null, pair[0]);
      th.setAttribute("scope", "row");
      row.appendChild(th);
      var td = make("td", null, pair[1]);
      if (index === 2) { td.setAttribute("data-emphasis", "yes"); }
      row.appendChild(td);
      incrementalBody.appendChild(row);
    });

    var text;
    if (change < 0.02) {
      text =
        "Adding " + listNames(state.additions) + " moves the variance " +
        "accounted for by " + (change >= 0 ? "+" : "") + pct(change) +
        ". On this evidence the measure is very nearly redundant: almost " +
        "everything it knows about the outcome was already in the two " +
        "ordinary measures.";
    } else if (change < 0.05) {
      text =
        "Adding " + listNames(state.additions) + " gains " + pct(change) +
        " of variance over the baseline. Small, real, and a long way from " +
        "what the advertising implies.";
    } else {
      text =
        "Adding " + listNames(state.additions) + " gains " + pct(change) +
        " of variance over a personality questionnaire and a reasoning test. " +
        "That is the kind of result that would justify the extra testing " +
        "time — and it is worth noticing which measures produce it.";
    }
    incrementalNote.textContent = text;
  }

  function renderInterpretation(coef) {
    var withinPairs = [["sr", "pq"], ["mp", "er"], ["mp", "rt"], ["er", "rt"]];
    var acrossPairs = [["sr", "mp"], ["sr", "er"], ["sr", "rt"], ["pq", "mp"], ["pq", "er"], ["pq", "rt"]];
    var mean = function (pairs) {
      return pairs.reduce(function (total, pair) {
        return total + r(coef, pair[0], pair[1]);
      }, 0) / pairs.length;
    };
    var within = mean(withinPairs);
    var across = mean(acrossPairs);

    var eiPairs = [["sr", "mp"], ["sr", "er"], ["mp", "er"]];
    var lowest = eiPairs.reduce(function (low, pair) {
      return Math.min(low, r(coef, pair[0], pair[1]));
    }, 1);

    var srPq = r(coef, "sr", "pq");
    var text, tone;

    /* CONVERGENT is the threshold at which the three labelled measures are
       treated as converging. It is deliberately the same number the fourth
       claim is judged against, so the verdict and the claim never disagree. */
    if (lowest >= CONVERGENT) {
      tone = "good";
      text =
        "On these settings the three measures behave like indicators of one " +
        "construct: the weakest correlation among them is " + fmt(lowest) +
        ", and the self-report scale sits with the performance tasks rather " +
        "than with the personality questionnaire (" + fmt(srPq) + "). This " +
        "is what the evidence would have to look like for a single " +
        "emotional-intelligence label to be doing honest work. It is not " +
        "what the study as collected looks like.";
    } else if (within - across > 0.30) {
      tone = "caution";
      text =
        "Method is doing a great deal of the work here. Measures sharing a " +
        "format correlate " + fmt(within) + " on average against " +
        fmt(across) + " for measures collected differently. A student who " +
        "read this matrix as \"two constructs\" would partly be reading two " +
        "questionnaires and three tests. Turn both method sliders to zero " +
        "and see how much of the pattern survives — the answer is: most of it.";
    } else {
      tone = "caution";
      text =
        "The three measures sold under one label are related but clearly not " +
        "interchangeable: the weakest correlation among them is " +
        fmt(lowest) + " (" + band(lowest) + "). Meanwhile the self-report " +
        "scale correlates " + fmt(srPq) + " with an ordinary personality " +
        "questionnaire. The label is doing more work than the data: what is " +
        "being measured depends on which method you chose, and calling all " +
        "three \"emotional intelligence\" hides that.";
    }

    interpretation.textContent = text;
    interpretation.setAttribute("data-tone", tone);
  }

  /* =======================================================================
     Opening prediction
     ===================================================================== */

  var OPENING = {
    high: {
      tone: "caution",
      verdict: "That is the assumption the laboratory is built to test.",
      text:
        "Measures with the same name on the box are not thereby measures of " +
        "the same thing. In the matrix you are about to open, the self-report " +
        "scale and the emotion-management task — both sold as emotional " +
        "intelligence — correlate about as weakly as two measures can while " +
        "still being positively related."
    },
    moderate: {
      tone: "good",
      verdict: "Closer than most first answers.",
      text:
        "Moderate correlations all round would be the comfortable outcome. " +
        "What you will actually find is more awkward and more interesting: " +
        "the correlations are not moderate all round, they are large within " +
        "a method and small across it."
    },
    method: {
      tone: "good",
      verdict: "That is the pattern.",
      text:
        "The measures cluster by how they were collected rather than by the " +
        "label they carry. Two questionnaires agree; two performance tasks " +
        "agree; a questionnaire and a performance task barely do. Your job " +
        "in the laboratory is to work out how much of that is method and how " +
        "much is content — the two method sliders let you find out."
    },
    zero: {
      tone: "caution",
      verdict: "Too strong the other way.",
      text:
        "The correlations are not zero. Every measure here relates positively " +
        "to the outcome, and the performance tasks relate substantially to " +
        "each other. The problem is not that nothing predicts anything; it is " +
        "that one name is being attached to measures that behave differently."
    }
  };

  openingForm.addEventListener("submit", function (event) {
    event.preventDefault();
    var answer = $('input[name="opening"]:checked', openingForm);
    if (!answer) {
      openingError.textContent = "Choose an answer before opening the laboratory.";
      openingError.hidden = false;
      return;
    }
    openingError.hidden = true;
    var feedback = OPENING[answer.value];
    showFeedback(openingFeedback, feedback.tone, feedback.verdict, feedback.text);
    lockForm(openingForm);
    unlockLab();
    $("#lab-heading").focus();
  });

  $('[data-action="skip-opening"]').addEventListener("click", function () {
    openingError.hidden = true;
    showFeedback(openingFeedback, "neutral", "Prediction skipped — demonstration mode.", "");
    lockForm(openingForm);
    unlockLab();
  });

  function unlockLab() {
    state.stage = "explore";
    mainSection.hidden = false;
    applyState();
    render();
    shell.announce("Laboratory unlocked.", { immediate: true });
  }

  /* =======================================================================
     The claims
     -------------------------------------------------------------------
     Each claim is judged against the matrix as currently set, not against a
     stored answer key, so a student who changes the settings changes what
     the evidence supports — which is the point.
     ===================================================================== */

  var CLAIMS = [
    {
      id: "distinct",
      judge: function (coef) {
        var overlap = r(coef, "sr", "pq");
        var gain = rSquared(coef, BASELINE.concat(["sr"]), "se") - rSquared(coef, BASELINE, "se");
        var verdict = overlap >= 0.45 && gain < 0.05 ? "no"
          : overlap < 0.30 && gain >= 0.05 ? "yes" : "partly";
        return {
          verdict: verdict,
          evidence:
            "The scale correlates " + fmt(overlap) + " with an ordinary " +
            "personality questionnaire, and adding it to a personality " +
            "questionnaire and a reasoning test changes the variance " +
            "accounted for in observed effectiveness by " +
            (gain >= 0 ? "+" : "") + pct(gain) + ".",
          teaching:
            "\"Measures something else\" is a claim about discriminant and " +
            "incremental validity, and both are testable. A questionnaire " +
            "that overlaps heavily with existing questionnaires and adds " +
            "little to prediction has not earned a new name, however good " +
            "the name is."
        };
      }
    },
    {
      id: "beatsiq",
      judge: function (coef) {
        var ei = r(coef, "sr", "se");
        var iq = r(coef, "rt", "se");
        var gain = rSquared(coef, BASELINE.concat(["sr"]), "se") - rSquared(coef, BASELINE, "se");
        var verdict = ei > iq + 0.10 && gain >= 0.05 ? "yes"
          : ei > iq + 0.05 ? "partly" : "no";
        return {
          verdict: verdict,
          evidence:
            "The self-report scale correlates " + fmt(ei) + " with observed " +
            "effectiveness and the reasoning test " + fmt(iq) + ". Once the " +
            "personality questionnaire is also in the model, the self-report " +
            "scale adds " + (gain >= 0 ? "+" : "") + pct(gain) + ".",
          teaching:
            "Two comparisons are being run together. A measure can have the " +
            "larger raw correlation and still add almost nothing, because " +
            "what it predicts was already predicted more cheaply. Beating " +
            "the reasoning test is not beating the questionnaire."
        };
      }
    },
    {
      id: "ability",
      /* The comparison has to be against a measure that is unambiguously
         about self-image, which is the personality questionnaire — not the
         self-report EI scale, whose own content the student can change. */
      judge: function (coef) {
        var withQuestionnaire = r(coef, "mp", "pq");
        var withReasoning = r(coef, "mp", "rt");
        var verdict = withQuestionnaire < 0.25 && withReasoning >= 0.25 ? "yes"
          : withQuestionnaire >= 0.45 ? "no" : "partly";
        return {
          verdict: verdict,
          evidence:
            "The emotion-management task correlates " + fmt(withQuestionnaire) +
            " with a self-description questionnaire and " + fmt(withReasoning) +
            " with a verbal reasoning test.",
          teaching:
            "A task sitting with the reasoning test rather than with the " +
            "questionnaire is behaving like a test. Two cautions either way: " +
            "it shares variance with ordinary reasoning, and a consensus key " +
            "defines the right answer by what most people say."
        };
      }
    },
    {
      id: "oneconstruct",
      judge: function (coef) {
        var pairs = [["sr", "mp"], ["sr", "er"], ["mp", "er"]];
        var lowest = pairs.reduce(function (low, pair) {
          return Math.min(low, r(coef, pair[0], pair[1]));
        }, 1);
        var verdict = lowest >= CONVERGENT ? "yes" : lowest >= 0.25 ? "partly" : "no";
        return {
          verdict: verdict,
          evidence:
            "The weakest correlation among the three measures carrying the " +
            "label is " + fmt(lowest) + " (" + band(lowest) + ").",
          teaching:
            "Convergence is decided by the weakest link, which is why the " +
            "number above is the minimum of the three. A small minimum means " +
            "a family of loosely related things sharing a name."
        };
      }
    },
    {
      id: "predicts",
      judge: function (coef) {
        var value = r(coef, "er", "se");
        var verdict = value >= 0.50 ? "yes" : value >= 0.35 ? "partly" : "no";
        return {
          verdict: verdict,
          evidence:
            "Emotion-recognition accuracy correlates " + fmt(value) +
            " with observed effectiveness, which is " + pct(value * value) +
            " of the variance in it.",
          teaching:
            "Two problems, and the second is the serious one. The " +
            "association leaves most differences between people unexplained " +
            "— and \"shows you will be\" turns an average across a sample " +
            "into a claim about one person, which no correlation licenses at " +
            "any size."
        };
      }
    }
  ];

  var VERDICT_WORDS = {
    yes: "Supported by this evidence",
    partly: "Partly supported",
    no: "Not supported by this evidence"
  };

  claimsForm.addEventListener("submit", function (event) {
    event.preventDefault();

    if (state.stage === "predict") {
      showFeedback(claimsFeedback, "caution", "Open the laboratory first.",
        "These claims are judged against the evidence in the matrix above, " +
        "so the laboratory needs to be open before the answers mean anything.");
      return;
    }

    var answers = CLAIMS.map(function (claim) {
      var picked = $('input[name="claim-' + claim.id + '"]:checked', claimsForm);
      return picked ? picked.value : null;
    });

    if (answers.indexOf(null) !== -1) {
      showFeedback(claimsFeedback, "caution", "One judgement per claim, please.",
        "Every claim needs an answer before the evidence is worth going " +
        "through — a blank is not a verdict.");
      return;
    }

    var coef = coefficients(state);
    var results = CLAIMS.map(function (claim, index) {
      var judged = claim.judge(coef);
      return { claim: claim, judged: judged, answer: answers[index] };
    });
    var agreed = results.filter(function (item) {
      return item.answer === item.judged.verdict;
    }).length;

    clear(claimsFeedback);
    claimsFeedback.setAttribute("data-tone", agreed >= 4 ? "good" : "caution");

    var lead = make("p");
    lead.appendChild(make("strong", "feedback__verdict",
      agreed + " of your 5 judgements match what the current evidence supports."));
    lead.appendChild(document.createTextNode(
      " The verdicts below are worked out from the matrix as you have it set, " +
      "not from a stored answer key. Change the settings and some of them change."));
    claimsFeedback.appendChild(lead);

    var list = make("ol", "claims__results");
    results.forEach(function (item, index) {
      var li = make("li");
      li.setAttribute("data-agreed", item.answer === item.judged.verdict ? "yes" : "no");

      var heading = make("p", "claims__result-head");
      heading.appendChild(make("strong", null,
        "Claim " + (index + 1) + ": " + VERDICT_WORDS[item.judged.verdict] + "."));
      heading.appendChild(document.createTextNode(
        item.answer === item.judged.verdict
          ? " That is what you said."
          : " You said: " + VERDICT_WORDS[item.answer].toLowerCase() + "."));
      li.appendChild(heading);

      li.appendChild(make("p", "claims__evidence", item.judged.evidence));
      li.appendChild(make("p", null, item.judged.teaching));
      list.appendChild(li);
    });
    claimsFeedback.appendChild(list);
    claimsFeedback.hidden = false;

    shell.announce("Five claims judged. " + agreed + " of your answers match the evidence.",
      { immediate: true });
  });

  /* =======================================================================
     Feedback plumbing, reset, start-up
     ===================================================================== */

  function showFeedback(container, tone, verdict, text) {
    clear(container);
    container.setAttribute("data-tone", tone);
    var p = make("p");
    p.appendChild(make("strong", "feedback__verdict", verdict));
    if (text) { p.appendChild(document.createTextNode(" " + text)); }
    container.appendChild(p);
    container.hidden = false;
  }

  function lockForm(form) {
    $$("input, button, select", form).forEach(function (c) { c.disabled = true; });
  }

  function unlockForm(form) {
    $$("input, button, select", form).forEach(function (c) { c.disabled = false; });
    form.reset();
  }

  shell.onReset(function () {
    state = JSON.parse(JSON.stringify(INITIAL));
    unlockForm(openingForm);
    openingFeedback.hidden = true;
    openingError.hidden = true;
    mainSection.hidden = true;
    claimsForm.reset();
    claimsFeedback.hidden = true;
    presetNote.textContent = DEFAULT_NOTE;
    applyState();
  });

  shell.reset({ silent: true });
  shell.announce(
    "Ready. Answer the question above to open the laboratory.",
    { immediate: true });
})();
