#!/usr/bin/env python3
"""Generate the Simplified Edition catalogue and its browsing pages.

    python3 scripts/build-simplified-catalogue.py
    python3 scripts/build-simplified-catalogue.py --check    # verify, do not write

The 75 `simplified/modules/*/tools/*/metadata.json` files are the source of
truth. This script reads them, validates the edition's structure, and writes:

    data/catalogue-simplified.json      the machine-readable index
    simplified/index.html               the edition landing page
    simplified/modules/<slug>/index.html  five module pages

Nothing here is hand-maintained. Editing a generated file directly is a
mistake the `--check` mode is there to catch: it regenerates everything in
memory and reports any file whose contents differ, so a stale page cannot be
committed unnoticed.

Why the module pages are generated rather than rendered in the browser
----------------------------------------------------------------------
The original edition's module pages fetch `data/catalogue.json` and fall back
to a static "in preparation" message. That is right for a collection which is
still filling up. This edition is complete, and its activities are built to
keep working from a downloaded folder with no server, so its module pages are
written out in full instead: they need no JavaScript, no fetch and no origin,
and they cannot disagree with the catalogue because both come from the same
run of this script.

The catalogue is still a real, loadable artefact. `simplified/assets/js/
edition-nav.js` reads it at runtime for the previous/next links inside an
activity, which is the one place a lookup genuinely needs to happen live.

Status
------
`assets/js/main.js` renders an original-edition tool only when its status is
exactly "published". This script applies the equivalent gate at generation
time: an activity whose status is "planned" or "in-progress" is a hard error
rather than a silent omission, because a Simplified Edition activity that
exists on disk but is missing from its module page is a worse failure than a
loud one. See the report in docs/simplified-edition-integration.md for the
recommendation on moving the edition off "draft" before deployment.
"""

import argparse
import html
import json
import pathlib
import sys
from collections import Counter

REPO = pathlib.Path(__file__).resolve().parent.parent
SIMPLIFIED = REPO / "simplified"
CATALOGUE = REPO / "data" / "catalogue-simplified.json"
ORIGINAL_CATALOGUE = REPO / "data" / "catalogue.json"

# Module order follows the main site's "Module 01" to "Module 05" numbering in
# index.html, so a reader moving between the two editions meets the same
# sequence. The display names are the edition's own, from its metadata.
MODULES = [
    {
        "moduleSlug": "cognitive",
        "number": "01",
        "blurb": "Attention, memory and judgement: what the system does with "
                 "limited capacity, and what that costs.",
    },
    {
        "moduleSlug": "research-methods",
        "number": "02",
        "blurb": "Sampling, estimation, error and power: the reasoning behind "
                 "a result rather than the arithmetic of one.",
    },
    {
        "moduleSlug": "neuropsychology",
        "number": "03",
        "blurb": "Paradigms run first and read about second, plus the logic "
                 "that turns a pattern of deficits into a claim.",
    },
    {
        "moduleSlug": "social-critical-psychology",
        "number": "04",
        "blurb": "Influence, categories and power, and the question of where "
                 "a finding ends and an interpretation of it begins.",
    },
    {
        "moduleSlug": "personality-individual-differences",
        "number": "05",
        "blurb": "Traits, structure and measurement: what a score supports, "
                 "and what it cannot be asked to carry.",
    },
]

EXPECTED_COUNTS = {
    "research-methods": 21,
    "cognitive": 12,
    "neuropsychology": 12,
    "personality-individual-differences": 18,
    "social-critical-psychology": 12,
}

TOTAL = 75

RENDERABLE_STATUSES = {"draft", "published"}

FAVICON = ("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' "
           "viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' "
           "fill='%231C7293'/%3E%3C/svg%3E")

GENERATED_NOTE = (
    "Generated by scripts/build-simplified-catalogue.py from the 75\n"
    "     simplified/modules/*/tools/*/metadata.json files. Do not edit by\n"
    "     hand: run the script instead, and use --check to verify."
)

# ------------------------------------------------------------------- motifs

# One small editorial illustration per module page.
#
# WHAT THEY ARE. A quick visual flavour of the module, read in about two
# seconds, sitting beside the module's name and stats. They are not teaching
# figures: the activities are the teaching, and a navigation page that opens
# with a lecture diagram pushes the thing a reader came for below the fold.
#
# THE RULES THEY FOLLOW, all learned from getting them wrong first:
#
#   * Small. A 240x140 viewBox rendered at about a third of the hero's width.
#   * Short labels only, two or three words. Every explanatory sentence lives
#     in the HTML caption beneath, never inside the SVG, where it cannot wrap,
#     cannot be selected, and silently overruns the viewBox.
#   * Nothing may exceed the viewBox. `.hero` sets `overflow: hidden`, so text
#     that overruns is not merely untidy, it is cut off mid-word. There is a
#     check for this in scripts/check-browsing-layer.py.
#   * Every shape carries a `fill` attribute as well as its class. The class
#     is the truth and comes from the design tokens; the attribute is the
#     fallback. An SVG shape with no fill of any kind paints BLACK, so a
#     stylesheet that fails to apply turns a diagram into black boxes over the
#     labels. Naming a colour twice is cheap; that failure is not.
#   * Animation moves data marks only, never a label, and no animated state
#     may cover text. Where movement adds nothing, the figure is static: the
#     social and critical figure is a branching diagram and stays still.
#
# All inert SVG animated by CSS in edition.css. No script, no image file, no
# network request, so a module page still works from a downloaded folder.

MOTIFS = {
    "cognitive": {
        "caption": "A cue in the right place gets you there sooner. The first "
                   "activities measure that difference.",
        "title": "A valid cue shortens the response",
        "desc": "Two boxes either side of a fixation cross, with the left one "
                "cued and holding the target. Below, two response bars: the "
                "bar for a validly cued target is about half the length of "
                "the bar for an invalidly cued one.",
        "svg": """
      <rect class="motif__box motif__box--cued" x="16" y="12" width="52" height="34" rx="7"
            fill="none" stroke="#1C7293" stroke-width="2"/>
      <rect class="motif__box" x="172" y="12" width="52" height="34" rx="7"
            fill="none" stroke="#DDD8CF" stroke-width="2"/>
      <path class="motif__cross" d="M120 21v16M112 29h16" stroke="#5F6878" stroke-width="2" fill="none"/>
      <circle class="motif__target" cx="42" cy="29" r="7" fill="#9E7318"/>
      <text class="motif__label" x="16" y="70" fill="#5F6878">Valid cue</text>
      <rect class="motif__bar motif__bar--h" x="16" y="76" width="68" height="9" rx="4.5" fill="#1C7293"/>
      <text class="motif__label" x="16" y="104" fill="#5F6878">Invalid cue</text>
      <rect class="motif__bar motif__bar--h motif__bar--slow" x="16" y="110" width="126" height="9" rx="4.5" fill="#3D5A80"/>
""",
    },
    "research-methods": {
        "caption": "Single observations scatter widely. The means of samples "
                   "drawn from them do not.",
        "title": "Sample means vary far less than single observations",
        "desc": "A wide, even scatter of individual observations across the "
                "full width. Below, the means of samples drawn from the same "
                "population form a narrow hump near the centre.",
        "svg": """
      <text class="motif__label" x="12" y="15" fill="#5F6878">Individual observations</text>
      <g class="motif__scatter" fill="#5F6878" opacity="0.5">
        <rect x="14" y="23" width="3" height="15" rx="1.5"/>
        <rect x="36" y="23" width="3" height="15" rx="1.5"/>
        <rect x="57" y="23" width="3" height="15" rx="1.5"/>
        <rect x="79" y="23" width="3" height="15" rx="1.5"/>
        <rect x="96" y="23" width="3" height="15" rx="1.5"/>
        <rect x="116" y="23" width="3" height="15" rx="1.5"/>
        <rect x="131" y="23" width="3" height="15" rx="1.5"/>
        <rect x="151" y="23" width="3" height="15" rx="1.5"/>
        <rect x="172" y="23" width="3" height="15" rx="1.5"/>
        <rect x="193" y="23" width="3" height="15" rx="1.5"/>
        <rect x="215" y="23" width="3" height="15" rx="1.5"/>
      </g>
      <text class="motif__label" x="12" y="63" fill="#5F6878">Sample means</text>
      <g class="motif__hump">
        <rect class="motif__bar" x="53" y="118" width="12" height="6" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="68" y="110" width="12" height="14" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="83" y="98" width="12" height="26" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="98" y="86" width="12" height="38" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="113" y="80" width="12" height="44" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="128" y="88" width="12" height="36" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="143" y="100" width="12" height="24" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="158" y="112" width="12" height="12" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="173" y="118" width="12" height="6" rx="2" fill="#1C7293"/>
      </g>
      <line class="motif__axis" x1="12" y1="124.5" x2="228" y2="124.5" stroke="#DDD8CF" stroke-width="1.5"/>
""",
    },
    "neuropsychology": {
        "caption": "Two people, two tasks, and the pattern crossing over. One "
                   "case could not show this.",
        "title": "A double dissociation: the pattern crosses over",
        "desc": "Two people are each tested on two tasks. The first is near "
                "ceiling on naming and near floor on route finding; the "
                "second shows exactly the reverse.",
        "svg": """
      <rect class="motif__swatch" x="12" y="10" width="9" height="9" rx="2" fill="#1C7293"/>
      <text class="motif__label" x="26" y="18" fill="#5F6878">Naming</text>
      <rect class="motif__swatch--alt" x="82" y="10" width="9" height="9" rx="2" fill="#9E7318"/>
      <text class="motif__label" x="96" y="18" fill="#5F6878">Route</text>
      <g class="motif__pair">
        <rect class="motif__bar" x="34" y="46" width="20" height="58" rx="3" fill="#1C7293"/>
        <rect class="motif__bar motif__bar--alt" x="58" y="88" width="20" height="16" rx="3" fill="#9E7318"/>
      </g>
      <g class="motif__pair">
        <rect class="motif__bar" x="162" y="90" width="20" height="14" rx="3" fill="#1C7293"/>
        <rect class="motif__bar motif__bar--alt" x="186" y="50" width="20" height="54" rx="3" fill="#9E7318"/>
      </g>
      <line class="motif__axis" x1="12" y1="104.5" x2="228" y2="104.5" stroke="#DDD8CF" stroke-width="1.5"/>
      <text class="motif__label motif__label--mid" x="56" y="122" fill="#5F6878">Patient A</text>
      <text class="motif__label motif__label--mid" x="184" y="122" fill="#5F6878">Patient B</text>
""",
    },
    "social-critical-psychology": {
        "caption": "One thing happened. Which account you reach for decides "
                   "what there is to explain.",
        "title": "One event, two accounts that both fit it",
        "desc": "A single recorded event on the left branches to two "
                "accounts of it on the right: one an account of the person, "
                "the other an account of the setting. Neither is marked as "
                "the correct one.",
        # Static. The idea is a branch, and a branch is legible at a glance;
        # the earlier animated version alternated two blocks and bought
        # nothing for the risk of a frame landing on top of a label.
        "svg": """
      <path class="motif__link" d="M92 70 C112 70 112 30 130 30" fill="none" stroke="#DDD8CF" stroke-width="1.5"/>
      <path class="motif__link" d="M92 70 C112 70 112 110 130 110" fill="none" stroke="#DDD8CF" stroke-width="1.5"/>
      <rect x="12" y="57" width="80" height="26" rx="8" fill="#EDF1F7" stroke="#DDD8CF" stroke-width="1.5"/>
      <text class="motif__label motif__label--mid" x="52" y="74" fill="#1A2744">The event</text>
      <rect x="130" y="17" width="98" height="26" rx="8" fill="#FFFFFF" stroke="#1C7293" stroke-width="1.5"/>
      <text class="motif__label motif__label--mid" x="179" y="34" fill="#5F6878">About her</text>
      <rect x="130" y="97" width="98" height="26" rx="8" fill="#FFFFFF" stroke="#1C7293" stroke-width="1.5"/>
      <text class="motif__label motif__label--mid" x="179" y="114" fill="#5F6878">About the room</text>
""",
    },
    "personality-individual-differences": {
        "caption": "Two people, four sub-scores each. The dashed line is "
                   "their average, and it is the same one.",
        "title": "Two different profiles with the same average",
        "desc": "Two people shown as four sub-scores each. The first "
                "profile is spiky, with two high sub-scores and two low ones; "
                "the second is almost flat. A dashed line marks the average, "
                "which falls in the same place for both.",
        # The heights are chosen so the two genuinely average to the same
        # number: 28 + 54 + 22 + 60 and 40 + 42 + 40 + 42 both come to 164, so
        # the dashed line at a height of 41 is true of both rather than merely
        # drawn where it looks right. The dash is broken either side of its
        # label so the two never overlap.
        "svg": """
      <g class="motif__profile">
        <rect class="motif__bar" x="26" y="76" width="14" height="28" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="44" y="50" width="14" height="54" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="62" y="82" width="14" height="22" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="80" y="44" width="14" height="60" rx="2" fill="#1C7293"/>
      </g>
      <g class="motif__profile motif__profile--two">
        <rect class="motif__bar" x="146" y="64" width="14" height="40" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="164" y="62" width="14" height="42" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="182" y="64" width="14" height="40" rx="2" fill="#1C7293"/>
        <rect class="motif__bar" x="200" y="62" width="14" height="42" rx="2" fill="#1C7293"/>
      </g>
      <line class="motif__axis" x1="12" y1="104.5" x2="228" y2="104.5" stroke="#DDD8CF" stroke-width="1.5"/>
      <line class="motif__mean" x1="12" y1="63" x2="228" y2="63" stroke="#9E7318" stroke-width="2" stroke-dasharray="5 4"/>
      <text class="motif__label motif__label--mid" x="60" y="122" fill="#5F6878">Person A</text>
      <text class="motif__label motif__label--mid" x="180" y="122" fill="#5F6878">Person B</text>
""",
    },
}

# --------------------------------------------------------------------- read

def read_activities():
    """Every simplified activity's metadata, keyed by module slug, in order."""
    files = sorted(SIMPLIFIED.glob("modules/*/tools/*/metadata.json"))
    out = []
    for path in files:
        with path.open(encoding="utf-8") as handle:
            data = json.load(handle)
        data["_path"] = path
        data["_dirModule"] = path.parts[-4]
        data["_dirTool"] = path.parts[-2]
        out.append(data)
    return out


# ----------------------------------------------------------------- validate

class Invalid(Exception):
    """A structural problem that must stop generation."""


def validate(activities):
    """Every check the edition's structure has to pass. Raises on the first
    complete pass that found anything, reporting all of it at once."""
    problems = []

    def bad(message):
        problems.append(message)

    # --- counts
    if len(activities) != TOTAL:
        bad("expected %d activities, found %d" % (TOTAL, len(activities)))

    per_module = Counter(a["moduleSlug"] for a in activities)
    for slug, expected in EXPECTED_COUNTS.items():
        if per_module.get(slug, 0) != expected:
            bad("module %s: expected %d activities, found %d"
                % (slug, expected, per_module.get(slug, 0)))
    for slug in per_module:
        if slug not in EXPECTED_COUNTS:
            bad("unknown module slug: %s" % slug)

    # --- identity
    ids = Counter(a["id"] for a in activities)
    for value, count in ids.items():
        if count > 1:
            bad("duplicate id: %s (%d times)" % (value, count))

    paths = Counter("simplified/modules/%s/tools/%s/index.html"
                    % (a["moduleSlug"], a["toolSlug"]) for a in activities)
    for value, count in paths.items():
        if count > 1:
            bad("duplicate path: %s (%d times)" % (value, count))

    # --- metadata agrees with where the file actually is
    for a in activities:
        if a["moduleSlug"] != a["_dirModule"]:
            bad("%s: moduleSlug %r but lives in modules/%s"
                % (a["_dirTool"], a["moduleSlug"], a["_dirModule"]))
        if a["toolSlug"] != a["_dirTool"]:
            bad("%s: toolSlug %r but directory is %s"
                % (a["_dirTool"], a["toolSlug"], a["_dirTool"]))
        if a.get("edition") != "simplified":
            bad("%s: edition is %r, expected 'simplified'"
                % (a["toolSlug"], a.get("edition")))
        page = a["_path"].parent / "index.html"
        if not page.exists():
            bad("%s: no index.html beside its metadata" % a["toolSlug"])

    # --- status, gated the way main.js gates the original edition
    for a in activities:
        if a.get("status") not in RENDERABLE_STATUSES:
            bad("%s: status %r cannot be listed (allowed: %s)"
                % (a["toolSlug"], a.get("status"),
                   ", ".join(sorted(RENDERABLE_STATUSES))))

    # --- pairing against the original edition
    originals = read_original_index()
    seen = Counter()
    for a in activities:
        paired = a.get("pairedWith")
        if not paired or not isinstance(paired, str):
            bad("%s: pairedWith is missing or not a string" % a["toolSlug"])
            continue
        key = (a["moduleSlug"], paired)
        seen[key] += 1
        if key not in originals:
            bad("%s: pairedWith %r does not resolve to an original in %s"
                % (a["toolSlug"], paired, a["moduleSlug"]))
        expected_path = "modules/%s/tools/%s/index.html" % (a["moduleSlug"], paired)
        if a.get("originalPath") != expected_path:
            bad("%s: originalPath %r does not match pairedWith (%r)"
                % (a["toolSlug"], a.get("originalPath"), expected_path))
        if not (REPO / expected_path).exists():
            bad("%s: the original it pairs with is not on disk: %s"
                % (a["toolSlug"], expected_path))

    for key, count in seen.items():
        if count > 1:
            bad("original %s/%s is claimed by %d simplified activities"
                % (key[0], key[1], count))
    for key in originals:
        if key not in seen:
            bad("original %s/%s has no simplified twin" % key)

    if problems:
        raise Invalid("\n".join("  " + p for p in problems))


def read_original_index():
    """{(moduleSlug, toolSlug): entry} for every tool in the original
    catalogue."""
    with ORIGINAL_CATALOGUE.open(encoding="utf-8") as handle:
        data = json.load(handle)
    out = {}
    for module in data.get("modules", []):
        for tool in module.get("tools", []):
            out[(module["moduleSlug"], tool["toolSlug"])] = tool
    return out


# ------------------------------------------------------------------ build

def build_catalogue(activities):
    by_module = {}
    for a in activities:
        by_module.setdefault(a["moduleSlug"], []).append(a)
    for entries in by_module.values():
        entries.sort(key=lambda a: a["toolSlug"])

    modules = []
    for spec in MODULES:
        slug = spec["moduleSlug"]
        entries = by_module[slug]
        modules.append({
            "id": slug,
            "moduleSlug": slug,
            "module": entries[0]["module"],
            "number": spec["number"],
            "path": "simplified/modules/%s/index.html" % slug,
            "activitiesDirectory": "simplified/modules/%s/tools/" % slug,
            "summary": spec["blurb"],
            "activityCount": len(entries),
            "activities": [catalogue_entry(a) for a in entries],
        })

    return {
        "$comment": [
            "Machine-readable index of the Simplified Edition.",
            "",
            "GENERATED FILE. Do not edit by hand. It is written by",
            "scripts/build-simplified-catalogue.py from the 75",
            "simplified/modules/*/tools/*/metadata.json files, which are the",
            "source of truth. Run the script with --check to verify that this",
            "file and the edition's browsing pages are up to date.",
            "",
            "Each activity carries `pairedWith`, the toolSlug of the original",
            "it simplifies, in the same module. The pairing is 1:1 in both",
            "directions and scripts/check-edition-pairing.py enforces it.",
            "",
            "Unlike data/catalogue.json this file is not read by",
            "assets/js/main.js. The module pages are generated in full, so",
            "they need no fetch; simplified/assets/js/edition-nav.js reads",
            "this file at runtime for the previous/next links in an activity,",
            "and degrades to a plain link back to the module when it cannot.",
        ],
        "schemaVersion": 1,
        "edition": "simplified",
        "generatedBy": "scripts/build-simplified-catalogue.py",
        "project": {
            "name": "Open Psychology Interactives — Simplified Edition",
            "description": (
                "Shorter, single-purpose versions of the 75 Open Psychology "
                "Interactives. Each keeps the mechanism of the activity it "
                "pairs with and reduces the lesson around it to one teaching "
                "job, at roughly 3 to 7 minutes rather than 15 to 30."),
            "repository": "https://github.com/utman5454/open-psychology-interactives",
            "basePath": "/open-psychology-interactives/",
            "landingPage": "simplified/index.html",
            "pairedEdition": "data/catalogue.json",
            "licence": "MIT",
            "accessibilityTarget": "WCAG 2.2 AA",
        },
        "activityCount": len(activities),
        "modules": modules,
    }


def catalogue_entry(a):
    """One activity, carrying what a listing or a navigation link needs and
    nothing else. The full metadata stays in the activity's own file."""
    return {
        "id": a["id"],
        "title": a["title"],
        "module": a["module"],
        "moduleSlug": a["moduleSlug"],
        "toolSlug": a["toolSlug"],
        "path": "simplified/modules/%s/tools/%s/index.html"
                % (a["moduleSlug"], a["toolSlug"]),
        "summary": a["summary"],
        "teachingJob": a["readmeTopic"],
        "topics": a["topics"],
        "estimatedMinutes": a["estimatedMinutes"],
        "difficulty": a["difficulty"],
        "status": a["status"],
        "version": a["version"],
        "lastUpdated": a["lastUpdated"],
        "pairedWith": a["pairedWith"],
        "originalPath": a["originalPath"],
    }


# ------------------------------------------------------------------- pages

def esc(text):
    return html.escape(str(text), quote=True)


def opening_capital(text):
    """`readmeTopic` is written as a phrase that completes "this is about ...",
    so it starts lowercase. Standing on its own under a title it reads as an
    unfinished sentence, so the first letter is raised for display only. The
    catalogue keeps the metadata's own wording untouched.

    Checked against all 75: the only entry that does not begin with an
    ordinary word is "p-values as tail areas", and "P-values" is correct at
    the start of a sentence."""
    return text[:1].upper() + text[1:] if text else text


def number_of(tool_slug):
    """The leading number in a tool slug, for display. Every slug in both
    editions is `NN-name`; anything else is shown as it is."""
    head = tool_slug.split("-", 1)[0]
    return head if head.isdigit() else ""


def page_shell(title, description, css_prefix, body, root_class="workbook"):
    return """<!doctype html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="icon" href="{favicon}">
<link rel="stylesheet" href="{css}simplified.css">
<link rel="stylesheet" href="{css}edition.css">
</head>
<body>
<a class="skip-link" href="#main">Skip to the list</a>

<!-- {generated} -->
<main class="{root_class}" id="main">
{body}</main>
</body>
</html>
""".format(title=esc(title), description=esc(description), favicon=FAVICON,
           css=css_prefix, generated=GENERATED_NOTE, body=body,
           root_class=root_class)


# A chevron for the "open this" affordance on a card. Inline SVG rather than a
# character, because the arrow glyphs that render well are not all present in
# every system font stack, and a missing one leaves a tofu box in the corner of
# every card. aria-hidden throughout: the card's link already says where it
# goes, and "Open, arrow, Posner Spatial Cueing" is worse than "Posner Spatial
# Cueing" for anyone listening to it.
ARROW = ('<svg class="go-arrow" viewBox="0 0 16 16" width="13" height="13" '
         'aria-hidden="true" focusable="false"><path d="M6 3.5 10.5 8 6 12.5" '
         'fill="none" stroke="currentColor" stroke-width="2" '
         'stroke-linecap="round" stroke-linejoin="round"/></svg>')


def minutes_span(activities):
    """`5 to 7` for a module whose activities vary, `6` for one that does not."""
    low = min(a["estimatedMinutes"] for a in activities)
    high = max(a["estimatedMinutes"] for a in activities)
    return "%d" % low if low == high else "%d to %d" % (low, high)


def chip(text, figure=None):
    """A small count. The figure is a separate span so it can be sized up
    without the word beside it growing too."""
    if figure is None:
        return '<li class="chip">%s</li>' % esc(text)
    return ('<li class="chip"><span class="chip__figure">%s</span> %s</li>'
            % (esc(str(figure)), esc(text)))


def motif_figure(module_slug):
    """The module's own small figure, or nothing if it has none.

    Wrapped in a <figure> with a visible caption, so the point it makes is
    also made in words. The SVG is labelled rather than hidden: it is carrying
    an idea, not ornamenting one.
    """
    motif = MOTIFS.get(module_slug)
    if not motif:
        return ""
    ident = "motif-%s" % module_slug
    return """  <figure class="module-motif">
    <svg class="motif motif--{slug}" viewBox="0 0 240 140" role="img"
         aria-labelledby="{id}-title {id}-desc">
      <title id="{id}-title">{title}</title>
      <desc id="{id}-desc">{desc}</desc>{svg}    </svg>
    <figcaption class="module-motif__caption">{caption}</figcaption>
  </figure>
""".format(slug=esc(module_slug), id=ident, title=esc(motif["title"]),
           desc=esc(motif["desc"]), svg=motif["svg"],
           caption=esc(motif["caption"]))


def render_landing(catalogue):
    rows = []
    for module in catalogue["modules"]:
        activities = module["activities"]
        chips = "".join([
            chip("activities", module["activityCount"]),
            chip("%s minutes each" % minutes_span(activities)),
        ])
        rows.append(
            '      <li class="module-row">\n'
            '        <span class="module-row__badge" aria-hidden="true">{number}</span>\n'
            '        <h3 class="module-row__title">\n'
            '          <a href="modules/{slug}/index.html">{name}</a>\n'
            '        </h3>\n'
            '        <p class="module-row__body">{blurb}</p>\n'
            '        <ul class="chip-row" role="list">{chips}</ul>\n'
            '        <p class="module-row__preview">'
            '<span class="module-row__span">Module {number}. Opens with '
            '<b>{first}</b>, closes with <b>{last}</b>.</span>'
            '<span class="module-row__go" aria-hidden="true">Browse{arrow}</span></p>\n'
            '      </li>'.format(
                arrow=ARROW,
                number=esc(module["number"]), slug=esc(module["moduleSlug"]),
                name=esc(module["module"]), blurb=esc(module["summary"]),
                chips=chips, first=esc(activities[0]["title"]),
                last=esc(activities[-1]["title"])))

    spans = sorted({a["estimatedMinutes"] for m in catalogue["modules"]
                    for a in m["activities"]})
    hero_chips = "".join([
        chip("activities", catalogue["activityCount"]),
        chip("modules", len(catalogue["modules"])),
        chip("minutes each", "%d to %d" % (spans[0], spans[-1])),
        chip("No account, nothing saved"),
    ])

    body = """  <section class="hero">
    <p class="eyebrow">Open Psychology Interactives</p>
    <h1>Simplified Edition</h1>
    <p class="hero__lead">Seventy-five short activities, one teaching job
      each. Every one keeps the working model from its full-length twin and
      cuts the lesson around it.</p>
    <ul class="chip-row chip-row--hero" role="list">{hero_chips}</ul>
  </section>

  <section class="card" aria-labelledby="about-heading">
    <h2 id="about-heading">What this edition is</h2>
    <div class="prose-cols">
      <p class="lead">Each activity takes roughly three to seven minutes. You
        predict something, change something, see what follows, and read a
        short account of what it did and did not show. There is one idea to
        take away rather than five.</p>
      <p class="lead">The mechanism is never the thing that was simplified. A
        simulation stays a simulation and a manipulable model stays
        manipulable; what was cut is the number of things being taught at
        once. Every activity links to its full-length version, which runs
        longer and asks more.</p>
    </div>
    <p class="small">Nothing here needs an account, a plugin or a network
      connection. Nothing you do in an activity is saved or sent anywhere.</p>
  </section>

  <section class="card" aria-labelledby="modules-heading">
    <div class="card-head">
      <h2 id="modules-heading">Five modules</h2>
      <p class="card-head__note">{total} activities, in teaching order</p>
    </div>
    <ul class="module-rail" role="list">
{rows}
    </ul>
  </section>

  <section class="card" aria-labelledby="original-heading">
    <h2 id="original-heading">The full-length collection</h2>
    <p class="lead">The original {total} interactives run 15 to 30 minutes
      each and carry the complete treatment: more stages, more controls, and
      the challenge and transfer tasks this edition leaves out. They are the
      right choice for a lab session or independent study.</p>
    <div class="actions">
      <a class="btn btn-secondary" href="../index.html">Go to the full
        collection</a>
    </div>
  </section>
""".format(rows="\n".join(rows), total=catalogue["activityCount"],
           hero_chips=hero_chips)

    return page_shell(
        "Simplified Edition | Open Psychology Interactives",
        "Seventy-five short psychology teaching activities, one teaching job "
        "each, paired with the full-length Open Psychology Interactives.",
        "assets/css/", body)


def render_module(catalogue, module):
    items = []
    for activity in module["activities"]:
        number = number_of(activity["toolSlug"])
        items.append(
            '      <li class="activity-card">\n'
            '        <span class="activity-card__badge" aria-hidden="true">{num}</span>\n'
            '        <h3 class="activity-card__title">\n'
            '          <a href="tools/{slug}/index.html">{title}</a>\n'
            '        </h3>\n'
            '        <p class="activity-card__job">{job}</p>\n'
            '        <p class="activity-card__foot">\n'
            '          <span class="activity-card__time">{minutes} min</span>\n'
            '          <span class="activity-card__go" aria-hidden="true">Open{arrow}</span>\n'
            '        </p>\n'
            '      </li>'.format(arrow=ARROW, 
                num=esc(number), slug=esc(activity["toolSlug"]),
                title=esc(activity["title"]),
                job=esc(opening_capital(activity["teachingJob"])),
                minutes=activity["estimatedMinutes"]))

    activities = module["activities"]
    total_minutes = sum(a["estimatedMinutes"] for a in activities)
    chips = "".join([
        chip("activities", module["activityCount"]),
        chip("minutes each", minutes_span(activities)),
        chip("minutes end to end", total_minutes),
    ])

    body = """  <nav class="edition-bar" aria-label="Breadcrumb">
    <a href="../../index.html">Simplified Edition</a>
    <span class="edition-bar__sep" aria-hidden="true">/</span>
    <span>{name}</span>
  </nav>

  <section class="hero hero--split">
    <div class="hero__text">
      <p class="eyebrow">Simplified Edition &middot; Module {number}</p>
      <h1>{name}</h1>
      <p class="hero__lead">{blurb}</p>
      <ul class="chip-row chip-row--hero" role="list">{chips}</ul>
    </div>
{motif}  </section>

  <section class="card" aria-labelledby="list-heading">
    <div class="card-head">
      <h2 id="list-heading">The activities</h2>
      <p class="card-head__note">In teaching order</p>
    </div>
    <ol class="activity-grid" role="list">
{items}
    </ol>
  </section>

  <section class="card" aria-labelledby="more-heading">
    <h2 id="more-heading">Elsewhere</h2>
    <p class="lead">Every activity here has a full-length twin in the main
      collection, linked from the foot of the activity itself.</p>
    <div class="actions">
      <a class="btn btn-secondary" href="../../index.html">All five
        modules</a>
      <a class="btn btn-secondary" href="../../../modules/{slug}/index.html">{name}
        in the full collection</a>
    </div>
  </section>
""".format(name=esc(module["module"]), number=esc(module["number"]),
           blurb=esc(module["summary"]), chips=chips,
           motif=motif_figure(module["moduleSlug"]),
           items="\n".join(items), slug=esc(module["moduleSlug"]))

    return page_shell(
        "%s | Simplified Edition" % module["module"],
        "%d short activities in %s, Simplified Edition of Open Psychology "
        "Interactives." % (module["activityCount"], module["module"]),
        "../../assets/css/", body)


# ------------------------------------------------------------------- write

def outputs(catalogue):
    """{path: text} for everything this script owns."""
    out = {
        CATALOGUE: json.dumps(catalogue, indent=2, ensure_ascii=False) + "\n",
        SIMPLIFIED / "index.html": render_landing(catalogue),
    }
    for module in catalogue["modules"]:
        target = SIMPLIFIED / "modules" / module["moduleSlug"] / "index.html"
        out[target] = render_module(catalogue, module)
    return out


def main():
    ap = argparse.ArgumentParser(
        description=__doc__.split("\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="verify the generated files are up to date, write nothing")
    ap.add_argument("--quiet", action="store_true", help="only report problems")
    args = ap.parse_args()

    activities = read_activities()
    try:
        validate(activities)
    except Invalid as error:
        print("Simplified Edition structure is invalid:\n%s" % error, file=sys.stderr)
        return 1

    catalogue = build_catalogue(activities)
    files = outputs(catalogue)

    if args.check:
        stale = []
        for path, text in sorted(files.items()):
            rel = path.relative_to(REPO)
            if not path.exists():
                stale.append("%s: missing" % rel)
            elif path.read_text(encoding="utf-8") != text:
                stale.append("%s: out of date" % rel)
            elif not args.quiet:
                print("ok: %s" % rel)
        if stale:
            print("\nStale generated files:", file=sys.stderr)
            for line in stale:
                print("  %s" % line, file=sys.stderr)
            print("\nRun: python3 scripts/build-simplified-catalogue.py",
                  file=sys.stderr)
            return 1
        print("\nAll %d generated files are up to date. %d activities across "
              "%d modules." % (len(files), catalogue["activityCount"],
                               len(catalogue["modules"])))
        return 0

    for path, text in sorted(files.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        if not args.quiet:
            print("wrote: %s" % path.relative_to(REPO))

    counts = ", ".join("%s %d" % (m["moduleSlug"], m["activityCount"])
                       for m in catalogue["modules"])
    print("\n%d activities: %s" % (catalogue["activityCount"], counts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
