/**
 * Chasing Alpha  (Simplified Edition)
 *
 * Teaching job: Cronbach's alpha can be pushed as high as you like by adding
 * near-duplicate items, and doing so makes the scale worse. High alpha is
 * therefore not evidence that a scale is a good measure.
 *
 * The model is the one from the full Alpha Trap. Every item is standardised
 * and generated by four independent standard-normal sources:
 *
 *     X_i = g_i*G + f_i*F(area) + w_i*W(wording family) + e_i
 *
 * so the correlation between two items is
 *
 *     r_ij = g_i*g_j + f_i*f_j [same area] + w_i*w_j [same wording family]
 *
 * and, because the items are standardised so that the item variances sum to k,
 *
 *     alpha = (k / (k - 1)) * (1 - k / Var(T))
 *
 * The criterion, a fictional tutor rating of dependability, is
 *
 *     Y = a*G + b*(F1 + ... + F5)/sqrt(5) + noise
 *
 * with the noise sized to give Y unit variance. Y therefore responds to the
 * general factor and to breadth of content coverage, and is entirely
 * indifferent to wording-specific variance. That single asymmetry is the whole
 * demonstration: a near-duplicate contributes to Var(T), which is the
 * denominator of the validity coefficient, without contributing anything to
 * its numerator beyond what the item it displaced already contributed.
 *
 * ONE CHANGE FROM THE ORIGINAL, AND IT MATTERS. In the full version items are
 * added to the scale. Adding near-duplicates raises alpha sharply but leaves
 * the validity coefficient almost flat, because nothing is lost: coverage is
 * still there, merely diluted. Here the scale is a FIXED TEN ITEMS and each
 * duplicate replaces an item covering something else, which is how scale
 * construction actually works when a questionnaire has a length budget. That
 * makes the cost real, and the two lines genuinely diverge.
 *
 * The paraphrase's general loading is set at 0.54 against a distinct item's
 * 0.55, deliberately close. A near-duplicate is a perfectly good item on its
 * own; what is wrong with it is that it is redundant, not that it is weak. It
 * also makes alpha rise monotonically across the whole range, so a learner
 * moving the control one step never sees alpha fall and draw the wrong
 * conclusion from an artefact of the loadings.
 *
 * Deliberate simplifications, stated in the caution:
 *   - No sampling error. Every figure is a population value the model implies,
 *     not an estimate, so nothing here carries a confidence interval.
 *   - Items are continuous and standardised, so no distinction is drawn
 *     between alpha, standardised alpha and ordinal alpha.
 *   - One wording family only, which keeps the structure legible.
 */
(function (global) {
  "use strict";

  var wb = null;

  /* ---------------------------------------------------------------- model */

  /* Squares must not exceed 1; the remainder is item-specific error.
       distinct:   0.55^2 + 0.32^2          = 0.405, error 0.595
       duplicate:  0.54^2 + 0.30^2 + 0.62^2 = 0.766, error 0.234 */
  var DISTINCT = { general: 0.55, area: 0.32, wording: 0 };
  var DUPLICATE = { general: 0.54, area: 0.30, wording: 0.62 };

  /* The criterion's loadings. `areas` is spread across the five content
     factors, so an item earns outcome-relevant variance only through the
     general factor and through its own content area. */
  var CRITERION = { general: 0.55, areas: 0.55 };

  var AREAS = ["Planning", "Orderliness", "Persistence", "Punctuality", "Resisting distraction"];
  var DUPLICATE_AREA = 3;
  var LENGTH = 10;
  var MAX_DUPES = 8;

  /* Two items per area to begin with. */
  var LAYOUT = [0, 1, 2, 3, 4, 0, 1, 2, 3, 4];

  /* Which slot each successive duplicate takes over. The two punctuality
     slots, 3 and 8, are never replaced: the duplicates are paraphrases of a
     punctuality item, so that area is the one thing the scale keeps. Second
     copies go first, then first copies, so coverage narrows gradually rather
     than losing a whole area on the first move. */
  var REPLACEMENT_ORDER = [5, 6, 7, 9, 0, 1, 2, 4];

  function scale(duplicates) {
    var items = LAYOUT.map(function (area) {
      return { area: area, duplicate: false, loadings: DISTINCT };
    });
    for (var i = 0; i < duplicates; i += 1) {
      items[REPLACEMENT_ORDER[i]] = {
        area: DUPLICATE_AREA, duplicate: true, loadings: DUPLICATE
      };
    }
    return items;
  }

  function correlation(a, b) {
    var r = a.loadings.general * b.loadings.general;
    if (a.area === b.area) { r += a.loadings.area * b.loadings.area; }
    if (a.duplicate && b.duplicate) { r += a.loadings.wording * b.loadings.wording; }
    return r;
  }

  /** Variance of the total score, which is the sum of the whole correlation
      matrix because the items are standardised. */
  function totalVariance(items) {
    var v = 0;
    items.forEach(function (a, i) {
      items.forEach(function (b, j) {
        v += (i === j) ? 1 : correlation(a, b);
      });
    });
    return v;
  }

  function alpha(items) {
    var k = items.length;
    return (k / (k - 1)) * (1 - k / totalVariance(items));
  }

  /** Correlation between the total score and the criterion. The criterion has
      unit variance by construction, so this is the covariance over the total
      score's standard deviation. */
  function validity(items) {
    var covariance = 0;
    items.forEach(function (item) {
      covariance += item.loadings.general * CRITERION.general +
        item.loadings.area * CRITERION.areas / Math.sqrt(AREAS.length);
    });
    return covariance / Math.sqrt(totalVariance(items));
  }

  function areasCovered(items) {
    var seen = {};
    items.forEach(function (item) { seen[item.area] = true; });
    return Object.keys(seen).length;
  }

  /** Share of the total score's variance that comes from the wording factor,
      which is variance about how a question is phrased and nothing else. */
  function wordingShare(items) {
    var sum = 0;
    items.forEach(function (item) {
      if (item.duplicate) { sum += item.loadings.wording; }
    });
    return (sum * sum) / totalVariance(items);
  }

  function countByArea(items) {
    var counts = AREAS.map(function () { return 0; });
    items.forEach(function (item) { counts[item.area] += 1; });
    return counts;
  }

  /* ------------------------------------------------------------------ dom */

  var options, verdict, verdictText, revealBtn, cardBuild;
  var dupesInput, readout, contents, chart, chartDesc;
  var chaseBtn, explainBtn, note, noteText, synthesis, resultLead;

  var REVEAL_AFTER = 2;
  var answered = false;
  var movesMade = 0;

  function dupes() { return Number(dupesInput.value); }

  var VERDICTS = {
    falls: { state: "correct", text:
      "Correct, and by more than most people expect. Watch the two lines " +
      "come apart as you move the control: alpha climbs the whole way while " +
      "the correlation with the tutor rating drops by about a quarter of its " +
      "starting value." },
    rises: { state: "incorrect", text:
      "This is the reasoning that makes alpha dangerous. It is true that " +
      "unreliable measurement limits how well anything can predict, so " +
      "better reliability ought to help. What is missing is that alpha can " +
      "be raised by repetition, and repetition adds no information about the " +
      "construct while costing a question about something else." },
    flat: { state: "incorrect", text:
      "Half right. Alpha and prediction really are separate questions, so " +
      "expecting no relation is more defensible than expecting a rise. But " +
      "they are not merely unrelated here: the specific thing being done to " +
      "raise alpha, replacing content with repetition, actively damages what " +
      "the scale predicts." },
    cannot: { state: "partial", text:
      "Right as a general principle, and worth holding onto: internal " +
      "consistency is evidence about the inside of a scale, and validity is a " +
      "question about its relation to something outside it. In this " +
      "particular case we can say more, because the model is fully specified " +
      "and we can compute what happens. Watch what it does." }
  };

  function answer(key) {
    if (answered) { return; }
    answered = true;
    wb.choices.mark(options.querySelector('[data-choice="' + key + '"]'), VERDICTS[key].state);
    if (key !== "falls") {
      wb.choices.mark(options.querySelector('[data-choice="falls"]'), "correct");
    }
    wb.choices.lock(options);
    verdict.setAttribute("data-state", VERDICTS[key].state);
    verdictText.textContent = VERDICTS[key].text;
    wb.show(verdict);
    revealBtn.disabled = false;
    wb.announce("Answer recorded.");
  }

  function reveal() {
    wb.show(cardBuild);
    render();
    wb.scrollTo(cardBuild);
    wb.focus(dupesInput);
    wb.announce("The scale is open. Use the slider to swap items for near-duplicates.");
  }

  /* --------------------------------------------------------------- figure */

  function svg(tag, attrs) {
    var node = global.document.createElementNS("http://www.w3.org/2000/svg", tag);
    Object.keys(attrs || {}).forEach(function (k) { node.setAttribute(k, attrs[k]); });
    return node;
  }

  var LEFT = 96, RIGHT = 700, TOP = 56, BOTTOM = 300;
  var ALPHA_COLOUR = "#C0434F";
  var VALID_COLOUR = "#1C7293";

  /* The vertical scale starts at 0.3 rather than 0: both quantities live in
     the top half of their range, and a full 0 to 1 axis would squash the whole
     phenomenon into a third of the figure. The axis is labelled so the reader
     can see it does not start at zero. */
  var Y_MIN = 0.3, Y_MAX = 1.0;

  function render() {
    var d = dupes();
    wb.clearFigure(chart);
    chart.setAttribute("viewBox", "0 0 900 " + (BOTTOM + 96));

    var xOf = function (n) { return LEFT + (n / MAX_DUPES) * (RIGHT - LEFT); };
    var yOf = function (v) {
      return BOTTOM - ((v - Y_MIN) / (Y_MAX - Y_MIN)) * (BOTTOM - TOP);
    };

    [0.3, 0.5, 0.7, 0.9].forEach(function (v) {
      chart.appendChild(svg("line", {
        x1: LEFT, y1: yOf(v).toFixed(1), x2: RIGHT, y2: yOf(v).toFixed(1),
        class: "plot__axis", opacity: 0.55
      }));
      var tick = svg("text", {
        x: LEFT - 10, y: (yOf(v) + 4).toFixed(1), "text-anchor": "end", class: "plot__tick"
      });
      tick.textContent = v.toFixed(1);
      chart.appendChild(tick);
    });

    var yTitle = svg("text", { x: 8, y: TOP - 24, class: "plot__label" });
    yTitle.textContent = "Coefficient, on a scale starting at 0.3";
    chart.appendChild(yTitle);

    /* The 0.7 line, because it is the number a reviewer asks for and the
       activity is partly about what asking for it encourages. */
    var seventy = svg("text", {
      x: RIGHT + 12, y: (yOf(0.7) + 4).toFixed(1), class: "plot__tick"
    });
    seventy.textContent = "0.70";
    chart.appendChild(seventy);

    [
      { colour: ALPHA_COLOUR, name: "Alpha", fn: alpha },
      { colour: VALID_COLOUR, name: "Predicts the tutor rating", fn: validity }
    ].forEach(function (series) {
      var points = [];
      for (var n = 0; n <= MAX_DUPES; n += 1) {
        points.push(xOf(n).toFixed(1) + "," + yOf(series.fn(scale(n))).toFixed(1));
      }
      chart.appendChild(svg("polyline", {
        points: points.join(" "), fill: "none",
        stroke: series.colour, "stroke-width": 3, "stroke-linejoin": "round"
      }));
      var label = svg("text", {
        x: RIGHT + 12, y: (yOf(series.fn(scale(MAX_DUPES))) + 4).toFixed(1),
        class: "plot__sub", fill: series.colour
      });
      label.textContent = series.name;
      chart.appendChild(label);
    });

    var markX = xOf(d);
    chart.appendChild(svg("line", {
      x1: markX.toFixed(1), y1: TOP, x2: markX.toFixed(1), y2: BOTTOM,
      stroke: "#1A2744", "stroke-width": 2
    }));
    [
      { colour: ALPHA_COLOUR, value: alpha(scale(d)) },
      { colour: VALID_COLOUR, value: validity(scale(d)) }
    ].forEach(function (point) {
      chart.appendChild(svg("circle", {
        cx: markX.toFixed(1), cy: yOf(point.value).toFixed(1), r: 6, fill: point.colour
      }));
    });

    [0, 2, 4, 6, 8].forEach(function (n) {
      var tick = svg("text", {
        x: xOf(n).toFixed(1), y: BOTTOM + 22, "text-anchor": "middle", class: "plot__tick"
      });
      tick.textContent = String(n);
      chart.appendChild(tick);
    });
    var axis = svg("text", {
      x: ((LEFT + RIGHT) / 2).toFixed(1), y: BOTTOM + 46, "text-anchor": "middle", class: "plot__tick"
    });
    axis.textContent = "Near-duplicates among the ten items";
    chart.appendChild(axis);

    describe(d);
    readouts(d);
  }

  function describe(d) {
    chartDesc.textContent =
      "Two lines across the nine possible versions of the scale, from no " +
      "near-duplicates to eight. Alpha rises the whole way, from " +
      alpha(scale(0)).toFixed(2) + " to " + alpha(scale(MAX_DUPES)).toFixed(2) +
      ". The correlation with the tutor rating falls the whole way, from " +
      validity(scale(0)).toFixed(2) + " to " +
      validity(scale(MAX_DUPES)).toFixed(2) + ". At the version currently " +
      "built, with " + d + (d === 1 ? " duplicate" : " duplicates") +
      ", alpha is " + alpha(scale(d)).toFixed(2) + " and the correlation is " +
      validity(scale(d)).toFixed(2) + ", and the scale covers " +
      areasCovered(scale(d)) + " of the five content areas.";
  }

  function tile(label, value, noteText) {
    var li = global.document.createElement("li");
    li.className = "result";
    var l = global.document.createElement("p");
    l.className = "result__label";
    l.textContent = label;
    var v = global.document.createElement("p");
    v.className = "result__value big";
    v.textContent = value;
    var n = global.document.createElement("span");
    n.className = "result__note";
    n.textContent = noteText;
    li.appendChild(l); li.appendChild(v); li.appendChild(n);
    return li;
  }

  function readouts(d) {
    var items = scale(d);
    var a = alpha(items);
    var v = validity(items);
    readout.textContent = "";
    readout.appendChild(tile("Cronbach's alpha", a.toFixed(2),
      a >= 0.9 ? "a reviewer would call this excellent" :
        (a >= 0.7 ? "comfortably past the usual threshold" : "below the usual threshold")));
    readout.appendChild(tile("Predicts the tutor rating", v.toFixed(2),
      d === 0 ? "this is where it started" :
        "down from " + validity(scale(0)).toFixed(2) + " at the start"));
    readout.appendChild(tile("Content areas covered", areasCovered(items) + " of 5",
      d === 0 ? "two items on each of the five" : "the duplicates cost the rest"));

    var counts = countByArea(items);
    var parts = [];
    AREAS.forEach(function (name, i) {
      if (counts[i] > 0) { parts.push(name.toLowerCase() + " " + counts[i]); }
    });
    contents.textContent =
      "Your ten items are now: " + parts.join(", ") + ". " +
      (d === 0
        ? "None of them is a near-duplicate of another, so nothing in the " +
          "total score is about how a question happens to be worded."
        : Math.round(wordingShare(items) * 100) + " per cent of the total " +
          "score is now variance shared by the duplicates alone, which is " +
          "variance about how a question is worded rather than about " +
          "academic conscientiousness.");
  }

  /* ------------------------------------------------------------- guidance */

  function chase() {
    dupesInput.value = String(MAX_DUPES);
    movesMade = REVEAL_AFTER;
    onSlide();
    var items = scale(MAX_DUPES);
    noteText.textContent =
      "Alpha is now " + alpha(items).toFixed(2) + ", which almost any " +
      "reviewer would accept without a second look, and eight of the ten " +
      "items ask about meeting deadlines in slightly different words. The " +
      "scale covers " + areasCovered(items) + " of the five content areas it " +
      "set out to measure. Its correlation with the tutor rating has fallen " +
      "from " + validity(scale(0)).toFixed(2) + " to " +
      validity(items).toFixed(2) + ". Every one of those four statements is " +
      "true of the same questionnaire, and only the first one usually gets " +
      "reported.";
    wb.show(note);
    wb.announce("Alpha is now " + alpha(items).toFixed(2) +
      " and the correlation with the tutor rating is " + validity(items).toFixed(2) + ".");
  }

  function onSlide() {
    var output = wb.root.querySelector('output[for="dupes"]');
    if (output) { output.textContent = dupesInput.value; }
    movesMade += 1;
    if (movesMade >= REVEAL_AFTER) { explainBtn.disabled = false; }
    render();
  }

  function explain() {
    var d = dupes();
    var items = scale(d);
    resultLead.textContent =
      "With " + d + (d === 1 ? " near-duplicate" : " near-duplicates") +
      " among the ten items, alpha is " + alpha(items).toFixed(2) +
      " against " + alpha(scale(0)).toFixed(2) + " at the start, and the " +
      "correlation with the tutor rating is " + validity(items).toFixed(2) +
      " against " + validity(scale(0)).toFixed(2) + ". The two numbers moved " +
      "in opposite directions because they answer different questions.";
    wb.show(synthesis);
    wb.scrollTo(synthesis);
  }

  /* ---------------------------------------------------------------- setup */

  function start() {
    wb = global.Workbook.attach("[data-workbook]");
    if (!wb) { return; }

    options = wb.root.querySelector("#options");
    verdict = wb.root.querySelector("#verdict");
    verdictText = wb.root.querySelector("#verdict-text");
    revealBtn = wb.root.querySelector("#reveal");
    cardBuild = wb.root.querySelector("#card-build");
    dupesInput = wb.root.querySelector("#dupes");
    readout = wb.root.querySelector("#readout");
    contents = wb.root.querySelector("#contents");
    chart = wb.root.querySelector("#chart");
    chartDesc = wb.root.querySelector("#chart-desc");
    chaseBtn = wb.root.querySelector("#chase");
    explainBtn = wb.root.querySelector("#explain");
    note = wb.root.querySelector("#note");
    noteText = wb.root.querySelector("#note-text");
    synthesis = wb.root.querySelector("#synthesis");
    resultLead = wb.root.querySelector("#result-lead");

    Array.prototype.forEach.call(options.querySelectorAll("[data-choice]"), function (button) {
      button.addEventListener("click", function () {
        answer(button.getAttribute("data-choice"));
      });
    });
    revealBtn.addEventListener("click", reveal);
    dupesInput.addEventListener("input", onSlide);
    dupesInput.addEventListener("change", onSlide);
    chaseBtn.addEventListener("click", chase);
    explainBtn.addEventListener("click", explain);

    wb.onReset(function () {
      answered = false;
      movesMade = 0;
      wb.choices.unlock(options);
      Array.prototype.forEach.call(options.querySelectorAll("[data-choice]"), function (button) {
        wb.choices.mark(button, null);
      });
      wb.hide(verdict);
      revealBtn.disabled = true;
      wb.hide(cardBuild);
      wb.hide(note);
      wb.hide(synthesis);
      explainBtn.disabled = true;
      dupesInput.value = "0";
      var output = wb.root.querySelector('output[for="dupes"]');
      if (output) { output.textContent = "0"; }
      render();
    });

    render();
  }

  if (global.document.readyState === "loading") {
    global.document.addEventListener("DOMContentLoaded", start);
  } else {
    start();
  }
}(window));
